#!/usr/bin/env python3
import json,re
from pathlib import Path
from html import escape
R=Path(__file__).resolve().parents[1]; D='2026-09-08'; BASE='https://epochlex.justathoughtblog.org'
B=[
{'term':'Retrieval Precision','slug':'retrieval-precision','pronunciation':'ree-TREE-vul preh-SIZH-un','definition':'An information-retrieval metric measuring the fraction of retrieved items that are relevant to the query or task.','example':'The RAG evaluation tracked retrieval precision to see how much irrelevant context the retriever was returning.','categories':['AI Systems & Technical Concepts'],'aliases':['Precision at k','Precision@k'],'status':'Established retrieval metric','partOfSpeech':'noun','related':['rag','reranker','contextual-retrieval'],'sources':[{'id':'scikit-precision-recall','type':'reference','publisher':'scikit-learn','title':'Precision-Recall','published':'2026','url':'https://scikit-learn.org/stable/auto_examples/model_selection/plot_precision_recall.html','supports':['definition','usage','technical-definition']}]},
{'term':'Retrieval Recall','slug':'retrieval-recall','pronunciation':'ree-TREE-vul ree-KAWL','definition':'An information-retrieval metric measuring the fraction of all relevant items that a retrieval system successfully returns.','example':'The team improved retrieval recall so the search step was less likely to miss passages needed to answer the question.','categories':['AI Systems & Technical Concepts'],'aliases':['Recall at k','Recall@k'],'status':'Established retrieval metric','partOfSpeech':'noun','related':['rag','retrieval-precision','contextual-retrieval'],'sources':[{'id':'scikit-precision-recall','type':'reference','publisher':'scikit-learn','title':'Precision-Recall','published':'2026','url':'https://scikit-learn.org/stable/auto_examples/model_selection/plot_precision_recall.html','supports':['definition','usage','technical-definition']}]},
{'term':'Latency','slug':'latency','pronunciation':'LAY-tun-see','definition':'The elapsed time required for an AI system or inference service to respond to a request or complete a defined stage of processing.','example':'The team measured latency separately from throughput because a service can process many requests overall while still responding slowly to an individual user.','categories':['AI Systems & Technical Concepts'],'aliases':['Inference latency'],'status':'Established performance term','partOfSpeech':'noun','related':['inference','time-to-first-token','model-serving'],'sources':[{'id':'nvidia-nim-metrics-2026','type':'reference','publisher':'NVIDIA','title':'NIM LLMs Benchmarking — Metrics','published':'2026-07-20','url':'https://docs.nvidia.com/nim/benchmarking/llm/latest/metrics.html','supports':['definition','usage','technical-definition']}]},
{'term':'Throughput','slug':'throughput','pronunciation':'THROO-put','definition':'The amount of inference work an AI serving system completes over a unit of time, such as requests, samples, or tokens processed per second.','example':'The serving benchmark measured throughput under increasing concurrency to see how much work the system could sustain.','categories':['AI Systems & Technical Concepts'],'aliases':['Inference throughput'],'status':'Established performance term','partOfSpeech':'noun','related':['inference','tokens-per-second','model-serving'],'sources':[{'id':'nvidia-nim-benchmarking-2026','type':'reference','publisher':'NVIDIA','title':'A Comprehensive Guide to NIM LLM Latency-Throughput Benchmarking','published':'2026-07-20','url':'https://docs.nvidia.com/nim/benchmarking/llm/latest/','supports':['definition','usage','technical-definition']}]},
{'term':'Proximal Policy Optimization','slug':'proximal-policy-optimization','pronunciation':'PROK-suh-mul POL-uh-see op-tuh-muh-ZAY-shun','definition':'A reinforcement-learning algorithm that updates a policy while constraining each update so the new policy does not move too far from the previous one; it has been widely used in reinforcement learning from human feedback for language-model post-training.','example':'The RLHF pipeline used Proximal Policy Optimization to update the language model against reward-model scores while limiting overly large policy changes.','categories':['AI Systems & Technical Concepts'],'aliases':['PPO'],'status':'Established reinforcement-learning term','partOfSpeech':'noun','related':['ai-alignment','reinforcement-learning-with-verifiable-rewards','group-relative-policy-optimization'],'sources':[{'id':'hf-ppo-trainer-2026','type':'reference','publisher':'Hugging Face','title':'PPO Trainer','published':'2026','url':'https://huggingface.co/docs/trl/ppo_trainer','supports':['definition','usage','technical-definition']}]},
{'term':'Agent Identity','slug':'agent-identity','pronunciation':'AY-jent eye-DEN-tuh-tee','definition':'A distinct digital identity assigned to an AI agent so its authentication, access, ownership, activity, and policy enforcement can be managed and audited separately from human users or other applications.','example':'The organization assigned each production agent an agent identity so its permissions and actions could be traced independently.','categories':['AI Risks, Safety & Governance','AI Systems & Technical Concepts'],'aliases':['AI agent identity'],'status':'Established emerging security term','partOfSpeech':'noun','related':['ai-agent','agent-permission','least-privilege-agent'],'sources':[{'id':'microsoft-agent-identity-2026','type':'primary','publisher':'Microsoft Learn','title':'What are agent identities?','published':'2026-06-15','url':'https://learn.microsoft.com/en-us/entra/agent-id/what-are-agent-identities','supports':['definition','usage','risk']}]},
{'term':'AI Audit','slug':'ai-audit','pronunciation':'A-I AW-dit','definition':'A structured examination of an AI system and its surrounding governance, data, performance, and monitoring practices to assess accountability, controls, risks, or compliance against defined criteria.','example':'The agency conducted an AI audit that reviewed governance, data quality, model performance, and ongoing monitoring evidence.','categories':['AI Risks, Safety & Governance','AI Ways of Working'],'aliases':['Artificial intelligence audit'],'status':'Established governance term','partOfSpeech':'noun','related':['ai-governance','ai-assurance','safety-evaluation'],'sources':[{'id':'gao-ai-accountability-framework','type':'primary','publisher':'U.S. Government Accountability Office','title':'Artificial Intelligence: An Accountability Framework for Federal Agencies and Other Entities','published':'2021-06-30','url':'https://www.gao.gov/products/gao-21-519sp','supports':['definition','usage','governance']}]},
{'term':'AI Risk Assessment','slug':'ai-risk-assessment','pronunciation':'A-I risk uh-SESS-ment','definition':'A structured process for identifying, analyzing, and evaluating risks associated with an AI system, its intended use, affected people or organizations, and the conditions in which it operates.','example':'The team completed an AI risk assessment before deployment to identify likely harms, affected stakeholders, and controls that needed to be strengthened.','categories':['AI Risks, Safety & Governance','AI Ways of Working'],'aliases':['Artificial intelligence risk assessment'],'status':'Established governance term','partOfSpeech':'noun','related':['ai-governance','ai-assurance','ai-safety-case'],'sources':[{'id':'nist-ai-rmf-2026','type':'primary','publisher':'NIST','title':'AI Risk Management Framework','published':'2026','url':'https://www.nist.gov/itl/ai-risk-management-framework','supports':['definition','usage','governance']}]},
{'term':'MCP Client','slug':'mcp-client','pronunciation':'em-see-PEE KLY-ent','definition':'A Model Context Protocol component within a host application that communicates with an MCP server, negotiates supported capabilities, and exchanges protocol messages on the host’s behalf.','example':'The desktop application created an MCP client to connect to the documentation server and use its exposed resources and tools.','categories':['AI Systems & Technical Concepts'],'aliases':['Model Context Protocol client'],'status':'Established protocol term','partOfSpeech':'noun','related':['mcp','mcp-server','mcp-tool','mcp-resource'],'sources':[{'id':'mcp-architecture-2025','type':'primary','publisher':'Model Context Protocol','title':'Architecture','published':'2025-06-18','url':'https://modelcontextprotocol.io/specification/2025-06-18/architecture','supports':['definition','usage','technical-definition']}]},
{'term':'Model License','slug':'model-license','pronunciation':'MOD-ul LYE-sens','definition':'The license or terms attached to an AI model that specify permissions, restrictions, conditions, or obligations governing how the model or its associated files may be used, modified, or redistributed.','example':'Before deploying the open-weight model commercially, the team reviewed its model license for redistribution and use restrictions.','categories':['AI Risks, Safety & Governance','AI Systems & Technical Concepts'],'aliases':['AI model license'],'status':'Established distribution and governance term','partOfSpeech':'noun','related':['open-weight-model','model-card','local-ai'],'sources':[{'id':'hf-repository-licenses-2026','type':'reference','publisher':'Hugging Face','title':'Licenses','published':'2026','url':'https://huggingface.co/docs/hub/en/repositories-licenses','supports':['definition','usage']}]}
]
def page(t):
 u=f'{BASE}/terms/{t["slug"]}/'; n=escape(t['term']); d=escape(t['definition'],quote=True); p=escape(t['pronunciation']); ld=json.dumps({'@context':'https://schema.org','@type':'DefinedTerm','name':t['term'],'description':t['definition'],'url':u,'inDefinedTermSet':BASE+'/','inLanguage':'en'},ensure_ascii=False)
 return f'<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{n} | EpochLex</title><meta name="description" content="{d}"><link rel="canonical" href="{u}"><script type="application/ld+json">{ld}</script><link rel="stylesheet" href="../../assets/css/styles.css"><link rel="stylesheet" href="../../assets/css/term-pages.css"><link rel="stylesheet" href="../../assets/css/brand-theme.css"></head><body><main id="term-page" class="term-page shell" data-term-slug="{t["slug"]}"><div id="term-fallback" class="term-fallback"><nav class="term-breadcrumb"><a href="../../">Browse</a><span>/</span><span>{n}</span></nav><p class="eyebrow">EpochLex entry</p><h1>{n}</h1><p class="fallback-pronunciation">{p}</p><p class="fallback-definition">{escape(t["definition"])}</p></div></main><script src="../../assets/js/app.js"></script><script src="../../assets/js/term-page.js"></script></body></html>\n'
tp=R/'data/terms.json'; terms=json.loads(tp.read_text()); existing={x['slug'] for x in terms}
for b in B:
 if b['slug'] in existing: raise SystemExit('already published: '+b['slug'])
 rec={k:v for k,v in b.items() if k not in ('related','sources')}; rec.update({'added':D,'lastReviewed':D,'sources':[]}); terms.append(rec)
terms.sort(key=lambda x:x['term'].lower()); tp.write_text(json.dumps(terms,ensure_ascii=False,separators=(',',':'))+'\n')
pp=R/'data/provenance.json'; prov=json.loads(pp.read_text())
for b in B: prov[b['slug']]={'researchStatus':'pending','origin':None,'firstKnownUse':None,'history':[],'relatedTerms':b['related'],'sources':b['sources']}
pp.write_text(json.dumps(prov,ensure_ascii=False,indent=2)+'\n')
for b in B:
 p=R/'terms'/b['slug']; p.mkdir(parents=True,exist_ok=True); (p/'index.html').write_text(page(b))
cp=R/'docs/CORPUS-CANDIDATES.md'; text=cp.read_text(); labels={'Retrieval Precision':'Retrieval Precision','Retrieval Recall':'Retrieval Recall','Latency':'Latency','Throughput':'Throughput','Proximal Policy Optimization':'Proximal Policy Optimization (PPO)','Agent Identity':'Agent Identity','AI Audit':'AI Audit','AI Risk Assessment':'AI Risk Assessment','MCP Client':'MCP Client','Model License':'Model License'}
for b in B: text=re.sub(r'^- '+re.escape(labels[b['term']])+r'\s*$','',text,flags=re.M)
text=re.sub(r'\n{3,}','\n\n',text); st=text.index('## Repository roadmap candidates'); en=text.index('## Related documentation'); count=sum(1 for line in text[st:en].splitlines() if line.startswith('- ')); text=re.sub(r'\*\*Current unpublished inventory: \d+ candidates\.\*\*',f'**Current unpublished inventory: {count} candidates.**',text,count=1); cp.write_text(text)
ap=R/'docs/CORPUS-AUDIT-2026-09.md'; a=ap.read_text(); sec='\n## Research Further promotion pass 7 — Batch K (published September 8, 2026)\n\nThis batch is the seventh evidence-based promotion from **Research Further**. Promotion records an audit decision for these entries; it does not create a permanent lifecycle state or automatic promotion rule.\n\n'
for b in B:
 src='; '.join(f"[{s['publisher']}: {s['title']}]({s['url']})" for s in b['sources']); sec+=f"### {b['term']}\n\n**Why promote and publish:** {b['definition']}\n\n**Usage evidence:** {src}\n\n**Provenance state:** `pending` — meaning/usage evidence is recorded; origin, first-known-use, and fuller history research remain open.\n\n"
a=a.replace('## Research Further',sec+'## Research Further',1); a=re.sub(r'This audit has now published \d+ candidates across Batches A–J and added 172 new research candidates\.', 'This audit has now published 103 candidates across Batches A–K and added 172 new research candidates.', a); ap.write_text(re.sub(r'\n{3,}','\n\n',a))
rp=R/'docs/ROADMAP.md'; r=rp.read_text().replace('- 215 published dictionary entries;','- 225 published dictionary entries;').replace('- 122 researched provenance records and 93 pending provenance records in the current published corpus;','- 122 researched provenance records and 103 pending provenance records in the current published corpus;'); rp.write_text(r)
sp=R/'sitemap.xml'; sm=sp.read_text(); blocks=''.join(f'  <url>\n    <loc>{BASE}/terms/{b["slug"]}/</loc>\n    <lastmod>{D}</lastmod>\n  </url>\n' for b in B); sp.write_text(sm.replace('</urlset>',blocks+'</urlset>'))
terms=json.loads(tp.read_text()); prov=json.loads(pp.read_text()); slugs={x['slug'] for x in terms}
assert len(terms)==225, len(terms); assert slugs==set(prov); assert sum(x.get('researchStatus')=='pending' for x in prov.values())==103
for rec in prov.values():
 for s in rec.get('relatedTerms',[]): assert s in slugs, s
for b in B: assert (R/'terms'/b['slug']/'index.html').exists()
assert count==647, count
print('Validated Batch K: 225 published, 103 pending, 647 candidates, related-term parity.')
