#!/usr/bin/env python3
import json,re
from pathlib import Path
from html import escape
R=Path(__file__).resolve().parents[1]; D='2026-09-08'; BASE='https://epochlex.justathoughtblog.org'
B=[
{'term':'Agent Sandbox','slug':'agent-sandbox','pronunciation':'AY-jent SAND-boks','definition':'An isolated or constrained execution environment that limits what an AI agent can access or change, reducing the potential impact of unsafe, unintended, or compromised actions.','example':'The coding agent ran inside an agent sandbox that restricted filesystem and network access.','categories':['AI Risks, Safety & Governance','AI Systems & Technical Concepts'],'aliases':['AI agent sandbox'],'status':'Established emerging security term','partOfSpeech':'noun','related':['ai-agent','agentic-workflow','computer-use'],'sources':[{'id':'anthropic-agent-sandbox-2025','type':'primary','publisher':'Anthropic','title':'Beyond permission prompts: making Claude Code more secure and autonomous','published':'2025-10-20','url':'https://www.anthropic.com/engineering/claude-code-sandboxing','supports':['definition','usage','risk']}]},
{'term':'Agent Permission','slug':'agent-permission','pronunciation':'AY-jent per-MISH-un','definition':'A configured rule or grant that determines which resources, tools, commands, data, or actions an AI agent is allowed to access or use.','example':'The administrator reduced the agent permissions so it could read the repository but could not deploy changes.','categories':['AI Risks, Safety & Governance','AI Ways of Working'],'aliases':['Agent permissions','AI agent permission'],'status':'Established emerging security term','partOfSpeech':'noun','related':['ai-agent','agent-sandbox','tool-approval','mcp-authorization'],'sources':[{'id':'anthropic-auto-mode-permissions-2026','type':'primary','publisher':'Anthropic','title':'How we built Claude Code auto mode: a safer way to skip permissions','published':'2026-03-25','url':'https://www.anthropic.com/engineering/claude-code-auto-mode','supports':['definition','usage','risk']}]},
{'term':'Tool Approval','slug':'tool-approval','pronunciation':'tool uh-PROO-vul','definition':'A human or policy-controlled checkpoint that must authorize an AI system or agent before it invokes a particular tool or performs a tool-mediated action.','example':'The assistant paused for tool approval before allowing the connected service to modify production data.','categories':['AI Risks, Safety & Governance','AI Ways of Working'],'aliases':['Tool approval request'],'status':'Established emerging agent-control term','partOfSpeech':'noun','related':['tool-calling','ai-agent','agent-permission','human-in-the-loop'],'sources':[{'id':'anthropic-tool-approval-remote-mcp','type':'primary','publisher':'Anthropic','title':'Getting Started with Custom Connectors Using Remote MCP','published':'2025','url':'https://support.anthropic.com/en/articles/11175166-about-custom-integrations-using-remote-mcp','supports':['definition','usage','risk']}]},
{'term':'MCP Server','slug':'mcp-server','pronunciation':'em-see-PEE SUR-ver','definition':'A server-side implementation of the Model Context Protocol that exposes tools, resources, prompts, or other supported capabilities for MCP clients to discover and use.','example':'The team deployed an MCP server that exposed internal documentation and search tools to compatible AI clients.','categories':['AI Systems & Technical Concepts'],'aliases':['Model Context Protocol server'],'status':'Established protocol term','partOfSpeech':'noun','related':['mcp','mcp-tool','mcp-resource','mcp-authorization'],'sources':[{'id':'mcp-java-server','type':'primary','publisher':'Model Context Protocol','title':'MCP Server','published':'2026','url':'https://java.sdk.modelcontextprotocol.io/latest/server/','supports':['definition','usage']}]},
{'term':'MCP Resource','slug':'mcp-resource','pronunciation':'em-see-PEE REE-sors','definition':'A URI-identified item of data or context that an MCP server exposes for clients to discover or read, such as a file, schema, document, or application-specific resource.','example':'The client read an MCP resource containing the project schema before answering the user’s question.','categories':['AI Systems & Technical Concepts'],'aliases':['Model Context Protocol resource'],'status':'Established protocol term','partOfSpeech':'noun','related':['mcp','mcp-server','mcp-tool','context-engineering'],'sources':[{'id':'mcp-resources-spec','type':'primary','publisher':'Model Context Protocol','title':'Resources','published':'2025-11-25','url':'https://modelcontextprotocol.io/specification/2025-11-25/server/resources','supports':['definition','usage','technical-definition']}]},
{'term':'MCP Apps','slug':'mcp-apps','pronunciation':'em-see-PEE apps','definition':'An MCP extension that lets servers provide interactive user interfaces to host applications by linking UI resources with MCP tools and enabling communication between the embedded interface and the host.','example':'The analytics server used MCP Apps to display an interactive chart instead of returning only structured data.','categories':['AI Systems & Technical Concepts','AI Ways of Working'],'aliases':['MCP Apps Extension'],'status':'Established emerging protocol extension','partOfSpeech':'noun','related':['mcp','mcp-server','mcp-resource','mcp-tool'],'sources':[{'id':'mcp-apps-2025','type':'primary','publisher':'Model Context Protocol','title':'MCP Apps: Extending servers with interactive user interfaces','published':'2025-11-21','url':'https://blog.modelcontextprotocol.io/posts/2025-11-21-mcp-apps/','supports':['definition','usage','history']}]},
{'term':'MCP Tasks','slug':'mcp-tasks','pronunciation':'em-see-PEE tasks','definition':'An MCP extension for representing and tracking longer-running server work through task handles and task lifecycle operations such as getting status, updating, or cancelling work.','example':'The MCP server returned a task handle so the client could poll the long-running operation until it completed.','categories':['AI Systems & Technical Concepts','AI Ways of Working'],'aliases':['MCP Tasks Extension'],'status':'Established protocol extension','partOfSpeech':'noun','related':['mcp','mcp-server','agentic-workflow'],'sources':[{'id':'mcp-spec-2026-tasks','type':'primary','publisher':'Model Context Protocol','title':'The 2026-07-28 Specification','published':'2026-07-28','url':'https://blog.modelcontextprotocol.io/posts/2026-07-28/','supports':['definition','usage','history']}]},
{'term':'On-Device AI','slug':'on-device-ai','pronunciation':'on dih-VYSS A-I','definition':'AI processing in which a model runs directly on an end-user device rather than sending each inference request to a remote cloud service.','example':'The app used on-device AI so speech analysis could continue offline without sending audio to a server.','categories':['AI Systems & Technical Concepts'],'aliases':['On-device artificial intelligence'],'status':'Established deployment term','partOfSpeech':'noun','related':['local-ai','edge-inference','npu','ai-pc'],'sources':[{'id':'apple-core-ai-on-device-2026','type':'primary','publisher':'Apple','title':'Integrating on-device AI models in your app with Core AI','published':'2026','url':'https://developer.apple.com/documentation/CoreAI/integrating-on-device-ai-models-in-your-app-with-core-ai','supports':['definition','usage']}]},
{'term':'QLoRA','slug':'qlora','pronunciation':'cue-LOHR-uh','definition':'A parameter-efficient fine-tuning technique that keeps a pretrained model quantized, commonly at 4-bit precision, while training low-rank adapter weights instead of updating the full model.','example':'The team used QLoRA to fine-tune a large model on a single workstation with much lower memory requirements.','categories':['AI Systems & Technical Concepts'],'aliases':['Quantized Low-Rank Adaptation'],'status':'Established technical term','partOfSpeech':'noun','related':['lora','peft','fine-tuning','open-weight-model'],'sources':[{'id':'hf-qlora-bitsandbytes','type':'reference','publisher':'Hugging Face','title':'bitsandbytes','published':'2026','url':'https://huggingface.co/docs/transformers/main/quantization/bitsandbytes','supports':['definition','usage']}]},
{'term':'Direct Preference Optimization','slug':'direct-preference-optimization','pronunciation':'dih-REKT PREF-er-ens op-tuh-muh-ZAY-shun','definition':'A post-training method that fine-tunes a language model directly on preferred and rejected response pairs without first training a separate explicit reward model.','example':'The team used Direct Preference Optimization to align the model with preference data collected from human reviewers.','categories':['AI Systems & Technical Concepts'],'aliases':['DPO'],'status':'Established post-training term','partOfSpeech':'noun','related':['fine-tuning','ai-alignment','training-data','loss-function'],'sources':[{'id':'hf-dpo-trainer','type':'reference','publisher':'Hugging Face','title':'DPO Trainer','published':'2026','url':'https://huggingface.co/docs/trl/dpo_trainer','supports':['definition','usage','technical-definition']}]}]
def page(t):
 u=f'{BASE}/terms/{t["slug"]}/'; n=escape(t['term']); d=escape(t['definition'],quote=True); p=escape(t['pronunciation']); ld=json.dumps({'@context':'https://schema.org','@type':'DefinedTerm','name':t['term'],'description':t['definition'],'url':u,'inDefinedTermSet':BASE+'/','inLanguage':'en'},ensure_ascii=False)
 return f'<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{n} | EpochLex</title><meta name="description" content="{d}"><link rel="canonical" href="{u}"><script type="application/ld+json">{ld}</script><link rel="stylesheet" href="../../assets/css/styles.css"><link rel="stylesheet" href="../../assets/css/term-pages.css"><link rel="stylesheet" href="../../assets/css/brand-theme.css"></head><body><main id="term-page" class="term-page shell" data-term-slug="{t["slug"]}"><div id="term-fallback" class="term-fallback"><nav class="term-breadcrumb"><a href="../../">Browse</a><span>/</span><span>{n}</span></nav><p class="eyebrow">EpochLex entry</p><h1>{n}</h1><p class="fallback-pronunciation">{p}</p><p class="fallback-definition">{escape(t["definition"])}</p></div></main><script src="../../assets/js/app.js"></script><script src="../../assets/js/term-page.js"></script></body></html>\n'
tp=R/'data/terms.json'; terms=json.loads(tp.read_text()); existing={x['slug'] for x in terms}
for b in B:
 if b['slug'] in existing: raise SystemExit('already published: '+b['slug'])
 rec={k:v for k,v in b.items() if k not in ('related','sources')}; rec.update({'added':D,'lastReviewed':D,'sources':[]}); terms.append(rec)
terms.sort(key=lambda x:x['term'].lower()); tp.write_text(json.dumps(terms,ensure_ascii=False,separators=(',',':'))+'\n')
pp=R/'data/provenance.json'; prov=json.loads(pp.read_text())
for b in B: prov[b['slug']]={'researchStatus':'pending','origin':None,'firstKnownUse':None,'history':[],'relatedTerms':b['related'],'sources':b['sources']}
pp.write_text(json.dumps(prov,ensure_ascii=False,indent=2)+'\n')
for b in B:
 p=R/'terms'/b['slug']; p.mkdir(parents=True,exist_ok=True); (p/'index.html').write_text(page(b))
cp=R/'docs/CORPUS-CANDIDATES.md'; text=cp.read_text(); labels={b['term']:b['term'] for b in B}; labels['Direct Preference Optimization']='Direct Preference Optimization (DPO)'
for b in B: text=re.sub(r'^- '+re.escape(labels[b['term']])+r'\s*$','',text,flags=re.M)
text=re.sub(r'\n{3,}','\n\n',text); st=text.index('## Repository roadmap candidates'); en=text.index('## Related documentation'); count=sum(1 for line in text[st:en].splitlines() if line.startswith('- ')); text=re.sub(r'\*\*Current unpublished inventory: \d+ candidates\.\*\*',f'**Current unpublished inventory: {count} candidates.**',text,count=1); cp.write_text(text)
ap=R/'docs/CORPUS-AUDIT-2026-09.md'; a=ap.read_text(); sec='\n## Research Further promotion pass 4 — Batch H (published September 8, 2026)\n\nThis batch is the fourth evidence-based promotion from **Research Further**. Promotion records an audit decision for these entries; it does not create a permanent lifecycle state or automatic promotion rule.\n\n'
for b in B:
 src='; '.join(f"[{s['publisher']}: {s['title']}]({s['url']})" for s in b['sources']); sec+=f"### {b['term']}\n\n**Why promote and publish:** {b['definition']}\n\n**Usage evidence:** {src}\n\n**Provenance state:** `pending` — meaning/usage evidence is recorded; origin, first-known-use, and fuller history research remain open.\n\n"
a=a.replace('## Research Further',sec+'## Research Further',1); a=a.replace('This audit has now published 63 candidates across Batches A–G and added 172 new research candidates.','This audit has now published 73 candidates across Batches A–H and added 172 new research candidates.'); ap.write_text(re.sub(r'\n{3,}','\n\n',a))
rp=R/'docs/ROADMAP.md'; r=rp.read_text().replace('- 185 published dictionary entries;','- 195 published dictionary entries;').replace('- 122 researched provenance records and 63 pending provenance records in the current published corpus;','- 122 researched provenance records and 73 pending provenance records in the current published corpus;'); rp.write_text(r)
sp=R/'sitemap.xml'; sm=sp.read_text(); blocks=''.join(f'  <url>\n    <loc>{BASE}/terms/{b["slug"]}/</loc>\n    <lastmod>{D}</lastmod>\n  </url>\n' for b in B); sp.write_text(sm.replace('</urlset>',blocks+'</urlset>'))
terms=json.loads(tp.read_text()); prov=json.loads(pp.read_text()); slugs={x['slug'] for x in terms}
assert len(terms)==195, len(terms); assert slugs==set(prov); assert sum(x.get('researchStatus')=='pending' for x in prov.values())==73
for rec in prov.values():
 for s in rec.get('relatedTerms',[]): assert s in slugs, s
for b in B: assert (R/'terms'/b['slug']/'index.html').exists()
assert count==677, count
print('Validated Batch H: 195 published, 73 pending, 677 candidates, related-term parity.')
