#!/usr/bin/env python3
import json,re
from pathlib import Path
from html import escape
R=Path(__file__).resolve().parents[1]; D='2026-09-08'; BASE='https://epochlex.justathoughtblog.org'
B=[
{'term':'RAG Pipeline','slug':'rag-pipeline','pronunciation':'RAG PIPE-line','definition':'The end-to-end workflow of a retrieval-augmented generation system, typically covering content ingestion and chunking, embedding and indexing, query-time retrieval, context assembly, and generation of an answer grounded in retrieved content.','example':'The team traced the bad answer through the RAG pipeline from document chunking to retrieval and final generation.','categories':['AI Systems & Technical Concepts'],'aliases':['Retrieval-augmented generation pipeline'],'status':'Established RAG architecture term','partOfSpeech':'noun','related':['rag','retrieval-pipeline','embedding'],'sources':[{'id':'microsoft-azure-files-rag-overview-2026','type':'primary','publisher':'Microsoft Learn','title':'Retrieval-Augmented Generation (RAG) with Azure Files','published':'2026-04-23','url':'https://learn.microsoft.com/en-us/azure/storage/files/artificial-intelligence/retrieval-augmented-generation/overview','supports':['definition','usage','technical-definition']},{'id':'microsoft-rag-design-guide-2026','type':'primary','publisher':'Microsoft Learn','title':'Design and Develop a RAG Solution on Azure','published':'2026-06-30','url':'https://learn.microsoft.com/en-us/azure/architecture/ai-ml/guide/rag/rag-solution-design-and-evaluation-guide','supports':['usage','technical-definition']}]},
{'term':'RAG Chunking','slug':'rag-chunking','pronunciation':'RAG CHUNK-ing','definition':'The preparation phase in a retrieval-augmented generation system where source documents are divided into smaller retrieval units whose size and boundaries are chosen to preserve useful context while improving retrieval precision and efficiency.','example':'The team changed its RAG chunking strategy after finding that oversized chunks were diluting relevant context.','categories':['AI Systems & Technical Concepts'],'aliases':['RAG document chunking'],'status':'Established RAG implementation term','partOfSpeech':'noun','related':['rag-pipeline','semantic-chunking','retrieval-pipeline'],'sources':[{'id':'microsoft-rag-chunking-2026','type':'primary','publisher':'Microsoft Learn','title':'Develop a RAG Solution on Azure - Chunking Phase','published':'2026-06-18','url':'https://learn.microsoft.com/en-us/azure/architecture/ai-ml/guide/rag/rag-chunking-phase','supports':['definition','usage','technical-definition']},{'id':'microsoft-fabric-rag-chunking-2025','type':'primary','publisher':'Microsoft Learn','title':'How to Use Fabric for Retrieval Augmented Generation','published':'2025','url':'https://learn.microsoft.com/en-us/fabric/data-science/quickstart-building-retrieval-augmented-generation','supports':['usage','technical-definition']}]},
{'term':'Needle-in-a-Haystack Evaluation','slug':'needle-in-a-haystack-evaluation','pronunciation':'NEE-dul in uh HAY-stak ih-val-yoo-AY-shun','definition':'A long-context evaluation that places one or more target facts or passages inside a much larger body of context and tests whether a model can locate and use the hidden information.','example':'The team used a needle-in-a-haystack evaluation to test whether the model could retrieve a buried requirement from a very long document set.','categories':['AI Systems & Technical Concepts','AI Ways of Working'],'aliases':['Needle-in-the-haystack evaluation','Needle-in-a-haystack eval','NIAH evaluation'],'status':'Established long-context evaluation pattern','partOfSpeech':'noun','related':['long-context-evaluation','eval','capability-evaluation'],'sources':[{'id':'anthropic-opus46-needle-2026','type':'primary','publisher':'Anthropic','title':'Claude Opus 4.6','published':'2026','url':'https://www.anthropic.com/news/claude-opus-4-6','supports':['definition','usage','evaluation']},{'id':'anthropic-niah-realism-2026','type':'research','publisher':'Anthropic','title':'Measuring and improving coding audit realism with deployment resources','published':'2026','url':'https://alignment.anthropic.com/2026/coding-audit-realism/','supports':['usage','evaluation']}]},
{'term':'Human Preference Evaluation','slug':'human-preference-evaluation','pronunciation':'HYOO-mun PREF-er-ens ih-val-yoo-AY-shun','definition':'An evaluation in which people compare or rate model responses according to which output they prefer, often on open-ended tasks where a single objective answer is insufficient.','example':'The release report included a human preference evaluation in which reviewers chose between anonymized responses from two models.','categories':['AI Ways of Working','AI Systems & Technical Concepts'],'aliases':['Human preference eval'],'status':'Established evaluation method','partOfSpeech':'noun','related':['human-evaluation','pairwise-evaluation','rubric'],'sources':[{'id':'openai-o1-human-preference-2024','type':'primary','publisher':'OpenAI','title':'Learning to reason with LLMs','published':'2024-09-12','url':'https://openai.com/index/learning-to-reason-with-llms/','supports':['definition','usage','evaluation']},{'id':'openai-o1mini-human-preference-2024','type':'primary','publisher':'OpenAI','title':'OpenAI o1-mini','published':'2024','url':'https://openai.com/index/openai-o1-mini-advancing-cost-efficient-reasoning/','supports':['usage','evaluation']}]},
{'term':'Agent Risk Assessment','slug':'agent-risk-assessment','pronunciation':'AY-jent RISK uh-SESS-ment','definition':'A risk assessment focused on an AI agent’s capabilities, tool access, permissions, operating environment, autonomy, and possible harms in a specific deployment.','example':'The deployment team performed an agent risk assessment before granting the coding agent write access to production repositories.','categories':['AI Risks, Safety & Governance','AI Ways of Working'],'aliases':['AI agent risk assessment'],'status':'Established agent-governance practice','partOfSpeech':'noun','related':['ai-risk-assessment','agent-security','agent-permission'],'sources':[{'id':'nist-agent-tool-risk-2025','type':'primary','publisher':'NIST','title':'Lessons Learned from the Consortium: Tool Use in Agent Systems','published':'2025-08-05','url':'https://www.nist.gov/news-events/news/2025/08/lessons-learned-consortium-tool-use-agent-systems','supports':['definition','usage','governance']}]},
{'term':'Training Data Extraction','slug':'training-data-extraction','pronunciation':'TRAY-ning DAY-tuh ek-STRAK-shun','definition':'A privacy attack in which an adversary attempts to recover examples or information from a generative model’s training data by interacting with or prompting the model.','example':'The privacy test checked whether carefully chosen prompts could reproduce memorized records from the model’s training data.','categories':['AI Risks, Safety & Governance','AI Systems & Technical Concepts'],'aliases':['Training-data extraction'],'status':'Established adversarial-ML privacy term','partOfSpeech':'noun','related':['membership-inference','model-inversion','ai-security'],'sources':[{'id':'nist-training-data-extraction-2025','type':'primary','publisher':'NIST CSRC','title':'training data extraction - Glossary','published':'2025','url':'https://csrc.nist.gov/glossary/term/training_data_extraction','supports':['definition','technical-definition','security']},{'id':'nist-aml-100-2e2025-training-extraction','type':'primary','publisher':'NIST','title':'Adversarial Machine Learning: A Taxonomy and Terminology of Attacks and Mitigations','published':'2025-03','url':'https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.100-2e2025.pdf','supports':['usage','technical-definition','security']}]},
{'term':'Tool Poisoning','slug':'tool-poisoning','pronunciation':'TOOL POY-zuh-ning','definition':'An attack in which an AI agent is given malicious or manipulated tool definitions, schemas, metadata, or tool outputs that cause the agent to misuse a tool, follow injected instructions, or perform unintended actions.','example':'The security review detected tool poisoning after a third-party MCP server returned hidden instructions inside an otherwise normal tool response.','categories':['AI Risks, Safety & Governance','AI Systems & Technical Concepts'],'aliases':['MCP tool poisoning'],'status':'Established agent-security attack term','partOfSpeech':'noun','related':['mcp-tool','prompt-injection','ai-security'],'sources':[{'id':'owasp-mcp-tool-poisoning','type':'primary','publisher':'OWASP','title':'MCP Tool Poisoning','published':'2026','url':'https://owasp.org/www-community/attacks/MCP_Tool_Poisoning','supports':['definition','usage','security']},{'id':'owasp-mcp03-tool-poisoning-2025','type':'primary','publisher':'OWASP','title':'MCP03:2025 - Tool Poisoning','published':'2025','url':'https://owasp.org/www-project-mcp-top-10/2025/MCP03-2025%E2%80%93Tool-Poisoning','supports':['usage','security','technical-definition']}]},
{'term':'RAG Poisoning','slug':'rag-poisoning','pronunciation':'RAG POY-zuh-ning','definition':'An attack that contaminates documents, embeddings, indexes, or other retrieval data used by a retrieval-augmented generation system so malicious or misleading content is retrieved as grounding context.','example':'The attacker used RAG poisoning by adding a malicious document to the shared knowledge base so it would later be retrieved into the agent’s context.','categories':['AI Risks, Safety & Governance','AI Systems & Technical Concepts'],'aliases':['Retrieval-augmented generation poisoning'],'status':'Established RAG security term','partOfSpeech':'noun','related':['rag','data-poisoning','ai-security'],'sources':[{'id':'microsoft-memory-context-poisoning-2026','type':'primary','publisher':'Microsoft Learn','title':'AI Memory / Context Poisoning (Corruption)','published':'2026-08-01','url':'https://learn.microsoft.com/en-us/security/zero-trust/catalog-ai-attack-techniques/ai-memory-context-poisoning','supports':['definition','usage','security']},{'id':'owasp-rag-security-2026','type':'primary','publisher':'OWASP Cheat Sheet Series','title':'Retrieval-Augmented Generation (RAG) Security Cheat Sheet','published':'2026','url':'https://cheatsheetseries.owasp.org/cheatsheets/RAG_Security_Cheat_Sheet.html','supports':['usage','security','technical-definition']}]},
{'term':'Sensitive Information Disclosure','slug':'sensitive-information-disclosure','pronunciation':'SEN-suh-tiv in-fer-MAY-shun dis-KLOH-zher','definition':'An AI security failure in which a model or AI application reveals confidential, personal, proprietary, or otherwise sensitive information through its outputs or connected data flows.','example':'The review classified the exposure of another customer’s private record in the assistant response as sensitive information disclosure.','categories':['AI Risks, Safety & Governance'],'aliases':['Sensitive data disclosure'],'status':'Established AI security risk term','partOfSpeech':'noun','related':['ai-security','prompt-injection','membership-inference'],'sources':[{'id':'owasp-sensitive-disclosure-2025','type':'primary','publisher':'OWASP GenAI Security Project','title':'LLM02:2025 Sensitive Information Disclosure','published':'2025','url':'https://genai.owasp.org/llmrisk/llm022025-sensitive-information-disclosure/','supports':['definition','usage','security']}]},
{'term':'Constitutional Classifier','slug':'constitutional-classifier','pronunciation':'kon-stuh-TOO-shuh-nul CLASS-uh-fye-er','definition':'A safety classifier trained from a natural-language constitution or rule set to detect and block model inputs or outputs that violate specified behavioral constraints.','example':'The model used a constitutional classifier to screen prompts and responses for disallowed CBRN assistance.','categories':['AI Risks, Safety & Governance','AI Systems & Technical Concepts'],'aliases':['Constitutional Classifiers'],'status':'Established AI safety technique','partOfSpeech':'noun','related':['jailbreak','safety-evaluation','ai-security'],'sources':[{'id':'anthropic-constitutional-classifiers-2026','type':'primary','publisher':'Anthropic','title':'Next-generation Constitutional Classifiers: More efficient protection against universal jailbreaks','published':'2026-01-09','url':'https://www.anthropic.com/research/next-generation-constitutional-classifiers','supports':['definition','usage','technical-definition','security']},{'id':'anthropic-frontier-safety-roadmap-2026','type':'primary','publisher':'Anthropic','title':'Frontier Safety Roadmap','published':'2026','url':'https://www.anthropic.com/responsible-scaling-policy/roadmap','supports':['usage','governance']}]}
]
def page(t):
 u=f'{BASE}/terms/{t["slug"]}/'; n=escape(t['term']); d=escape(t['definition'],quote=True); p=escape(t['pronunciation']); ld=json.dumps({'@context':'https://schema.org','@type':'DefinedTerm','name':t['term'],'description':t['definition'],'url':u,'inDefinedTermSet':BASE+'/','inLanguage':'en'},ensure_ascii=False)
 return f'<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{n} | EpochLex</title><meta name="description" content="{d}"><link rel="canonical" href="{u}"><script type="application/ld+json">{ld}</script><link rel="stylesheet" href="../../assets/css/styles.css"><link rel="stylesheet" href="../../assets/css/term-pages.css"><link rel="stylesheet" href="../../assets/css/brand-theme.css"></head><body><main id="term-page" class="term-page shell" data-term-slug="{t["slug"]}"><div id="term-fallback" class="term-fallback"><nav class="term-breadcrumb"><a href="../../">Browse</a><span>/</span><span>{n}</span></nav><p class="eyebrow">EpochLex entry</p><h1>{n}</h1><p class="fallback-pronunciation">{p}</p><p class="fallback-definition">{escape(t["definition"])}</p></div></main><script src="../../assets/js/app.js"></script><script src="../../assets/js/term-page.js"></script></body></html>\n'
tp=R/'data/terms.json'; terms=json.loads(tp.read_text()); existing={x['slug'] for x in terms}
for b in B:
 if b['slug'] in existing: raise SystemExit('already published: '+b['slug'])
 rec={k:v for k,v in b.items() if k not in ('related','sources')}; rec.update({'added':D,'lastReviewed':D,'sources':[]}); terms.append(rec)
for t in terms:
 if t['slug']=='model-extraction':
  a=t.setdefault('aliases',[])
  if 'Model Stealing' not in a: a.append('Model Stealing')
terms.sort(key=lambda x:x['term'].lower()); tp.write_text(json.dumps(terms,ensure_ascii=False,separators=(',',':'))+'\n')
pp=R/'data/provenance.json'; prov=json.loads(pp.read_text())
for b in B: prov[b['slug']]={'researchStatus':'pending','origin':None,'firstKnownUse':None,'history':[],'relatedTerms':b['related'],'sources':b['sources']}
pp.write_text(json.dumps(prov,ensure_ascii=False,indent=2)+'\n')
for b in B:
 p=R/'terms'/b['slug']; p.mkdir(parents=True,exist_ok=True); (p/'index.html').write_text(page(b))
cp=R/'docs/CORPUS-CANDIDATES.md'; text=cp.read_text()
for label in [b['term'] for b in B]+['Model Stealing']:
 text=re.sub(r'^- '+re.escape(label)+r'\s*$','',text,flags=re.M)
text=re.sub(r'\n{3,}','\n\n',text); st=text.index('## Repository roadmap candidates'); en=text.index('## Related documentation'); count=sum(1 for line in text[st:en].splitlines() if line.startswith('- ')); text=re.sub(r'\*\*Current unpublished inventory: \d+ candidates\.\*\*',f'**Current unpublished inventory: {count} candidates.**',text,count=1); cp.write_text(text)
ap=R/'docs/CORPUS-AUDIT-2026-09.md'; a=ap.read_text(); sec='\n## Research Further promotion pass 20 — Batch X (published September 8, 2026)\n\nThis batch is the twentieth evidence-based promotion from **Research Further**. Promotion records an audit decision for these entries; it does not create a permanent lifecycle state or automatic promotion rule.\n\n'
for b in B:
 src='; '.join(f"[{s['publisher']}: {s['title']}]({s['url']})" for s in b['sources']); sec+=f"### {b['term']}\n\n**Why promote and publish:** {b['definition']}\n\n**Usage evidence:** {src}\n\n**Provenance state:** `pending` — meaning/usage evidence is recorded; origin, first-known-use, and fuller history research remain open.\n\n"
sec+='### Alias disposition: Model Stealing\n\n**Disposition:** Represent as an alias of the published **Model Extraction** entry rather than as a separate page. NIST discusses model stealing attacks within its Model Extraction taxonomy, and a separate EpochLex page would duplicate the same attack family without enough distinct reader value.\n\n'
a=a.replace('## Research Further',sec+'## Research Further',1); a=re.sub(r'This audit has now published \d+ candidates across Batches A–W and added 172 new research candidates\.', 'This audit has now published 233 candidates across Batches A–X and added 172 new research candidates.', a); ap.write_text(re.sub(r'\n{3,}','\n\n',a))
rp=R/'docs/ROADMAP.md'; r=rp.read_text().replace('- 345 published dictionary entries;','- 355 published dictionary entries;').replace('- 122 researched provenance records and 223 pending provenance records in the current published corpus;','- 122 researched provenance records and 233 pending provenance records in the current published corpus;'); rp.write_text(r)
sp=R/'sitemap.xml'; sm=sp.read_text(); blocks=''.join(f'  <url>\n    <loc>{BASE}/terms/{b["slug"]}/</loc>\n    <lastmod>{D}</lastmod>\n  </url>\n' for b in B); sm=sm.replace('</urlset>',blocks+'</urlset>'); sp.write_text(sm)
slugs={t['slug'] for t in terms}; assert len(terms)==355,len(terms); assert set(prov)==slugs,(len(prov),len(slugs)); pending=sum(1 for p in prov.values() if p.get('researchStatus')=='pending'); assert pending==233,pending
assert count==511,count
for b in B: assert (R/'terms'/b['slug']/'index.html').exists()
mx=next(t for t in terms if t['slug']=='model-extraction'); assert 'Model Stealing' in mx.get('aliases',[])
for slug,p in prov.items():
 for rel in p.get('relatedTerms',[]): assert rel in slugs,(slug,rel)
print(f'validated: {len(terms)} terms, {pending} pending, {count} candidates')
