#!/usr/bin/env python3
import json,re
from pathlib import Path
from html import escape
R=Path(__file__).resolve().parents[1]; D='2026-09-08'; BASE='https://epochlex.justathoughtblog.org'
B=[
{'term':'Batch Inference','slug':'batch-inference','pronunciation':'batch IN-fer-ens','definition':'A mode of model inference that processes many inputs together, typically asynchronously and without a requirement for immediate per-request responses, so predictions can be generated efficiently at high throughput.','example':'The team used batch inference overnight to score millions of records and store the results for later use.','categories':['AI Systems & Technical Concepts'],'aliases':['Offline Inference','Static Inference'],'status':'Established deployment term','partOfSpeech':'noun','related':['online-inference','inference','throughput'],'sources':[{'id':'google-batch-inference-2026','type':'primary','publisher':'Google Cloud','title':'What is batch inference?','published':'2026','url':'https://cloud.google.com/discover/what-is-batch-inference','supports':['definition','usage','technical-definition']},{'id':'google-static-dynamic-inference-2025','type':'primary','publisher':'Google for Developers','title':'Production ML systems: Static versus dynamic inference','published':'2025-12-02','url':'https://developers.google.com/machine-learning/crash-course/production-ml-systems/static-vs-dynamic-inference','supports':['aliases','usage']}]},
{'term':'Inference Provider','slug':'inference-provider','pronunciation':'IN-fer-ens proh-VY-der','definition':'A service provider that hosts AI models and exposes infrastructure or APIs for running inference, allowing applications to request model outputs without operating the underlying model-serving stack themselves.','example':'The application switched inference providers to compare latency, pricing, and model availability without changing its core workflow.','categories':['AI Systems & Technical Concepts','AI Ways of Working'],'aliases':['Model inference provider'],'status':'Established deployment ecosystem term','partOfSpeech':'noun','related':['model-serving','inference-server','inference'],'sources':[{'id':'hf-inference-providers-2026','type':'primary','publisher':'Hugging Face','title':'Inference Providers','published':'2026','url':'https://huggingface.co/docs/inference-providers/index','supports':['definition','usage','technical-definition']}]},
{'term':'Inference Engine','slug':'inference-engine','pronunciation':'IN-fer-ens EN-jin','definition':'An optimized executable representation or execution component produced for running a trained model efficiently on a target inference stack or hardware platform.','example':'The deployment pipeline compiled the ONNX model into a TensorRT inference engine before running it on the GPU.','categories':['AI Systems & Technical Concepts'],'aliases':['Model inference engine'],'status':'Established deployment term','partOfSpeech':'noun','related':['inference-runtime','inference-backend','model-serving'],'sources':[{'id':'nvidia-tensorrt-engine-2026','type':'primary','publisher':'NVIDIA','title':'NVIDIA TensorRT Documentation','published':'2026-08','url':'https://docs.nvidia.com/deeplearning/tensorrt/latest/','supports':['definition','usage','technical-definition']},{'id':'nvidia-build-engine-2026','type':'primary','publisher':'NVIDIA','title':'Build Your First Engine','published':'2026-08','url':'https://docs.nvidia.com/deeplearning/tensorrt/latest/getting-started/build-your-first-engine.html','supports':['usage','technical-definition']}]},
{'term':'Approximate Nearest Neighbor','slug':'approximate-nearest-neighbor','pronunciation':'uh-PROK-suh-mut NEER-est NAY-bor','definition':'A similarity-search approach that finds items likely to be among the nearest neighbors of a query vector without exhaustively comparing every candidate, trading some exactness for much faster search at scale.','example':'The vector index used approximate nearest-neighbor search to retrieve semantically similar passages with lower latency than brute-force comparison.','categories':['AI Systems & Technical Concepts'],'aliases':['ANN search','Approximate k-nearest neighbor','Approximate kNN'],'status':'Established retrieval term','partOfSpeech':'noun','related':['hnsw','vector-database','embedding'],'sources':[{'id':'elastic-approx-knn-2026','type':'primary','publisher':'Elastic','title':'k-nearest neighbor (kNN) search','published':'2026','url':'https://www.elastic.co/guide/en/elasticsearch/reference/8.19/knn-search.html','supports':['definition','usage','technical-definition']}]},
{'term':'Hybrid Retrieval','slug':'hybrid-retrieval','pronunciation':'HY-brid ree-TREE-vul','definition':'A retrieval approach that combines results or scores from different retrieval methods—commonly lexical and semantic or vector retrieval—to produce a single ranked result set.','example':'The RAG system used hybrid retrieval so exact product codes and semantically similar descriptions could both influence ranking.','categories':['AI Systems & Technical Concepts'],'aliases':['Hybrid search retrieval'],'status':'Established retrieval term','partOfSpeech':'noun','related':['hybrid-search','dense-retrieval','sparse-retrieval'],'sources':[{'id':'elastic-hybrid-search-2026','type':'primary','publisher':'Elastic','title':'Hybrid search with semantic_text','published':'2026','url':'https://www.elastic.co/docs/solutions/search/hybrid-semantic-text','supports':['definition','usage','technical-definition']}]},
{'term':'Evals Framework','slug':'evals-framework','pronunciation':'ee-VALZ FRAME-wurk','definition':'A software or methodological framework for defining evaluation cases, running them against AI models or systems, applying grading logic, and inspecting results in a repeatable way.','example':'The team used an evals framework to run the same regression tests across several model versions and compare failures sample by sample.','categories':['AI Ways of Working','AI Systems & Technical Concepts'],'aliases':['Evaluation framework','AI evals framework'],'status':'Established evaluation term','partOfSpeech':'noun','related':['eval','evaluation-harness','evaluation-dataset'],'sources':[{'id':'openai-evals-framework-2023','type':'primary','publisher':'OpenAI','title':'GPT-4 — OpenAI Evals','published':'2023-03-14','url':'https://openai.com/index/gpt-4-research/','supports':['definition','usage','technical-definition']},{'id':'openai-evals-primer-2025','type':'primary','publisher':'OpenAI','title':'How evals drive the next chapter in AI for businesses','published':'2025-11-19','url':'https://openai.com/index/evals-drive-next-chapter-of-ai/','supports':['usage','evaluation']}]},
{'term':'Golden Dataset','slug':'golden-dataset','pronunciation':'GOHL-den DAY-tuh-set','definition':'A curated set of representative examples with trusted expected outputs, labels, judgments, or success criteria that serves as a reference for evaluating and improving an AI system.','example':'The product team maintained a golden dataset of expert-reviewed support requests and expected resolutions for regression testing.','categories':['AI Ways of Working','AI Systems & Technical Concepts'],'aliases':['Golden Set','Gold Dataset'],'status':'Established evaluation term','partOfSpeech':'noun','related':['evaluation-dataset','human-evaluation','eval'],'sources':[{'id':'openai-golden-set-2025','type':'primary','publisher':'OpenAI','title':'How evals drive the next chapter in AI for businesses','published':'2025-11-19','url':'https://openai.com/index/evals-drive-next-chapter-of-ai/','supports':['definition','usage','evaluation']}]},
{'term':'Algorithmic Impact Assessment','slug':'algorithmic-impact-assessment','pronunciation':'al-guh-RITH-mik IM-pakt uh-SESS-ment','definition':'A structured assessment used to identify and evaluate the potential impacts and risks of an automated decision system so required safeguards, review, transparency, and mitigation measures can be determined.','example':'The department completed an Algorithmic Impact Assessment before deploying the automated decision system into production.','categories':['AI Risks, Safety & Governance','AI Ways of Working'],'aliases':['AIA'],'status':'Established governance assessment term','partOfSpeech':'noun','related':['ai-impact-assessment','ai-risk-management','human-oversight'],'sources':[{'id':'canada-aia-2026','type':'primary','publisher':'Government of Canada','title':'Algorithmic Impact Assessment tool','published':'2026-05-28','url':'https://www.canada.ca/en/government/system/digital-government/digital-government-innovations/responsible-use-ai/algorithmic-impact-assessment.html','supports':['definition','usage','governance','risk']}]},
{'term':'General-Purpose AI Model','slug':'general-purpose-ai-model','pronunciation':'JEN-er-ul PUR-pus A-I MOD-ul','definition':'Under the EU AI Act, an AI model that displays significant generality, can competently perform a wide range of distinct tasks, and can be integrated into a variety of downstream systems or applications.','example':'The provider assessed whether its foundation model met the EU AI Act definition of a general-purpose AI model and therefore triggered provider obligations.','categories':['AI Risks, Safety & Governance','AI Systems & Technical Concepts'],'aliases':['GPAI Model','General-purpose artificial intelligence model'],'status':'Established EU regulatory term','partOfSpeech':'noun','related':['general-purpose-ai','ai-act','systemic-risk'],'sources':[{'id':'eu-gpai-model-2025','type':'primary','publisher':'European Commission','title':'General-Purpose AI Models in the AI Act — Questions & Answers','published':'2025','url':'https://digital-strategy.ec.europa.eu/en/faqs/general-purpose-ai-models-ai-act-questions-answers','supports':['definition','usage','regulation']}]},
{'term':'AI Transparency','slug':'ai-transparency','pronunciation':'A-I trans-PAIR-en-see','definition':'The quality and practice of making relevant information about an AI system, its operation, governance, limitations, decisions, and impacts available in ways that help affected people and responsible actors understand what happened and how the system is being managed.','example':'The organization improved AI transparency by publishing model limitations, ownership information, evaluation results, and explanations of how automated decisions were reviewed.','categories':['AI Risks, Safety & Governance'],'aliases':['Artificial intelligence transparency'],'status':'Established governance concept','partOfSpeech':'noun','related':['ai-governance','responsible-ai','model-card'],'sources':[{'id':'nist-ai-transparency-2026','type':'primary','publisher':'NIST AI Resource Center','title':'AI Risks and Trustworthiness','published':'2026','url':'https://airc.nist.gov/airmf-resources/airmf/3-sec-characteristics/','supports':['definition','usage','governance']},{'id':'nist-transparency-playbook-2026','type':'primary','publisher':'NIST AI Resource Center','title':'AI RMF Playbook — Measure','published':'2026','url':'https://airc.nist.gov/airmf-resources/playbook/measure/','supports':['usage','governance']}]}
]
def page(t):
 u=f'{BASE}/terms/{t["slug"]}/'; n=escape(t['term']); d=escape(t['definition'],quote=True); p=escape(t['pronunciation']); ld=json.dumps({'@context':'https://schema.org','@type':'DefinedTerm','name':t['term'],'description':t['definition'],'url':u,'inDefinedTermSet':BASE+'/','inLanguage':'en'},ensure_ascii=False)
 return f'<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{n} | EpochLex</title><meta name="description" content="{d}"><link rel="canonical" href="{u}"><script type="application/ld+json">{ld}</script><link rel="stylesheet" href="../../assets/css/styles.css"><link rel="stylesheet" href="../../assets/css/term-pages.css"><link rel="stylesheet" href="../../assets/css/brand-theme.css"></head><body><main id="term-page" class="term-page shell" data-term-slug="{t["slug"]}"><div id="term-fallback" class="term-fallback"><nav class="term-breadcrumb"><a href="../../">Browse</a><span>/</span><span>{n}</span></nav><p class="eyebrow">EpochLex entry</p><h1>{n}</h1><p class="fallback-pronunciation">{p}</p><p class="fallback-definition">{escape(t["definition"])}</p></div></main><script src="../../assets/js/app.js"></script><script src="../../assets/js/term-page.js"></script></body></html>\n'
tp=R/'data/terms.json'; terms=json.loads(tp.read_text()); existing={x['slug'] for x in terms}
for b in B:
 if b['slug'] in existing: raise SystemExit('already published: '+b['slug'])
 rec={k:v for k,v in b.items() if k not in ('related','sources')}; rec.update({'added':D,'lastReviewed':D,'sources':[]}); terms.append(rec)
terms.sort(key=lambda x:x['term'].lower()); tp.write_text(json.dumps(terms,ensure_ascii=False,separators=(',',':'))+'\n')
pp=R/'data/provenance.json'; prov=json.loads(pp.read_text())
for b in B: prov[b['slug']]={'researchStatus':'pending','origin':None,'firstKnownUse':None,'history':[],'relatedTerms':b['related'],'sources':b['sources']}
pp.write_text(json.dumps(prov,ensure_ascii=False,indent=2)+'\n')
for b in B:
 p=R/'terms'/b['slug']; p.mkdir(parents=True,exist_ok=True); (p/'index.html').write_text(page(b))
cp=R/'docs/CORPUS-CANDIDATES.md'; text=cp.read_text()
labels={
'Batch Inference':'Batch Inference','Inference Provider':'Inference Provider','Inference Engine':'Inference Engine','Approximate Nearest Neighbor':'Approximate Nearest Neighbor (ANN)','Hybrid Retrieval':'Hybrid Retrieval','Evals Framework':'Evals Framework','Golden Dataset':'Golden Dataset','Algorithmic Impact Assessment':'Algorithmic Impact Assessment','General-Purpose AI Model':'General-Purpose AI Model','AI Transparency':'AI Transparency'}
for b in B: text=re.sub(r'^- '+re.escape(labels[b['term']])+r'\s*$','',text,flags=re.M)
text=re.sub(r'^- Offline Inference\s*$','',text,flags=re.M)
text=re.sub(r'\n{3,}','\n\n',text); st=text.index('## Repository roadmap candidates'); en=text.index('## Related documentation'); count=sum(1 for line in text[st:en].splitlines() if line.startswith('- ')); text=re.sub(r'\*\*Current unpublished inventory: \d+ candidates\.\*\*',f'**Current unpublished inventory: {count} candidates.**',text,count=1); cp.write_text(text)
ap=R/'docs/CORPUS-AUDIT-2026-09.md'; a=ap.read_text(); sec='\n## Research Further promotion pass 15 — Batch S (published September 8, 2026)\n\nThis batch is the fifteenth evidence-based promotion from **Research Further**. Promotion records an audit decision for these entries; it does not create a permanent lifecycle state or automatic promotion rule.\n\n'
for b in B:
 src='; '.join(f"[{s['publisher']}: {s['title']}]({s['url']})" for s in b['sources']); sec+=f"### {b['term']}\n\n**Why promote and publish:** {b['definition']}\n\n**Usage evidence:** {src}\n\n**Provenance state:** `pending` — meaning/usage evidence is recorded; origin, first-known-use, and fuller history research remain open.\n\n"
sec+='### Offline Inference\n\n**Disposition:** Alias of **Batch Inference**, consistent with current Google documentation that uses offline/static inference for the same batch-prediction pattern. It is removed from the unpublished candidate inventory rather than published as a duplicate entry.\n\n'
a=a.replace('## Research Further',sec+'## Research Further',1); a=re.sub(r'This audit has now published \d+ candidates across Batches A–R and added 172 new research candidates\.', 'This audit has now published 183 candidates across Batches A–S and added 172 new research candidates.', a); ap.write_text(re.sub(r'\n{3,}','\n\n',a))
rp=R/'docs/ROADMAP.md'; r=rp.read_text().replace('- 295 published dictionary entries;','- 305 published dictionary entries;').replace('- 122 researched provenance records and 173 pending provenance records in the current published corpus;','- 122 researched provenance records and 183 pending provenance records in the current published corpus;'); rp.write_text(r)
sp=R/'sitemap.xml'; sm=sp.read_text(); blocks=''.join(f'  <url>\n    <loc>{BASE}/terms/{b["slug"]}/</loc>\n    <lastmod>{D}</lastmod>\n  </url>\n' for b in B); sp.write_text(sm.replace('</urlset>',blocks+'</urlset>'))
terms=json.loads(tp.read_text()); prov=json.loads(pp.read_text()); slugs={x['slug'] for x in terms}
assert len(terms)==305, len(terms); assert slugs==set(prov); assert sum(x.get('researchStatus')=='pending' for x in prov.values())==183
assert count==566, count
for b in B: assert (R/'terms'/b['slug']/'index.html').exists()
for slug,p in prov.items():
 for rel in p.get('relatedTerms',[]): assert rel in slugs,(slug,rel)
print('Validated Batch S: 305 published, 183 pending, 566 candidates; Offline Inference dispositioned as alias.')
