#!/usr/bin/env python3
import json,re
from pathlib import Path
from html import escape
R=Path(__file__).resolve().parents[1]; D='2026-09-08'; BASE='https://epochlex.justathoughtblog.org'
B=[
{'term':'Local Inference','slug':'local-inference','pronunciation':'LOH-kul IN-fer-ens','definition':'AI model inference performed on a user-controlled local machine or local network endpoint rather than by sending the request to a third-party cloud inference service.','example':'The workstation used local inference through an Ollama server so prompts and model execution stayed on the local system.','categories':['AI Systems & Technical Concepts'],'aliases':['Local model inference'],'status':'Established deployment term','partOfSpeech':'noun','related':['local-ai','inference','on-device-ai'],'sources':[{'id':'nvidia-local-inference-2026','type':'primary','publisher':'NVIDIA','title':'Use a Local Inference Server','published':'2026','url':'https://docs.nvidia.com/nemoclaw/latest/inference/use-local-inference.html','supports':['definition','usage','technical-definition']}]},
{'term':'Agent Telemetry','slug':'agent-telemetry','pronunciation':'AY-jent tuh-LEM-uh-tree','definition':'Operational data emitted or collected from AI agents—such as traces, metrics, logs, tool activity, and execution context—to support monitoring, troubleshooting, security analysis, and performance assessment.','example':'The observability pipeline collected agent telemetry so operators could investigate tool failures and unusual execution patterns.','categories':['AI Systems & Technical Concepts','AI Ways of Working'],'aliases':['AI agent telemetry'],'status':'Established emerging observability term','partOfSpeech':'noun','related':['agent-trace','llm-observability','ai-agent'],'sources':[{'id':'microsoft-agent-telemetry-2026','type':'primary','publisher':'Microsoft Learn','title':'Microsoft OpenTelemetry Distro','published':'2026-06-15','url':'https://learn.microsoft.com/en-us/microsoft-agent-365/developer/microsoft-opentelemetry','supports':['definition','usage','technical-definition']}]},
{'term':'Evaluation Trace','slug':'evaluation-trace','pronunciation':'ih-val-yoo-AY-shun trays','definition':'A recorded sequence of an AI system or agent trial—including outputs, tool calls, intermediate actions, and other interactions—used as evidence for evaluating how the system behaved, not only what final result it produced.','example':'The evaluator inspected the evaluation trace to see whether the agent used the correct tool even though the final answer was accurate.','categories':['AI Ways of Working','AI Systems & Technical Concepts'],'aliases':['Eval trace','Evaluation trajectory'],'status':'Established emerging evaluation term','partOfSpeech':'noun','related':['eval','agent-trace','evaluation-harness'],'sources':[{'id':'anthropic-agent-evals-trace-2026','type':'primary','publisher':'Anthropic','title':'Demystifying evals for AI agents','published':'2026-01-09','url':'https://www.anthropic.com/engineering/demystifying-evals-for-ai-agents','supports':['definition','usage','evaluation']},{'id':'openai-agents-tracing-2026','type':'primary','publisher':'OpenAI','title':'OpenAI Agents SDK — Tracing','published':'2026','url':'https://openai.github.io/openai-agents-python/tracing/','supports':['usage','technical-definition']}]},
{'term':'MCP Progress Notification','slug':'mcp-progress-notification','pronunciation':'em-see-PEE PROG-res noh-tuh-fuh-KAY-shun','definition':'A Model Context Protocol notification that reports incremental progress for a long-running request, associated with the originating request through a progress token.','example':'The server sent MCP Progress Notifications while a long-running import advanced through each processing stage.','categories':['AI Systems & Technical Concepts'],'aliases':['MCP progress','Model Context Protocol progress notification'],'status':'Established protocol term','partOfSpeech':'noun','related':['mcp','mcp-client','mcp-server'],'sources':[{'id':'mcp-progress-schema-2025','type':'primary','publisher':'Model Context Protocol','title':'Schema Reference — notifications/progress','published':'2025-11-25','url':'https://modelcontextprotocol.io/specification/2025-11-25/schema','supports':['definition','usage','technical-definition']}]},
{'term':'Cross-Encoder','slug':'cross-encoder','pronunciation':'KROSS en-KOH-der','definition':'A model that jointly processes a pair of inputs—such as a query and candidate document—to produce a relevance or similarity score, commonly used as a second-stage reranker after faster retrieval.','example':'The search pipeline used a cross-encoder to rescore the top documents returned by the initial retriever.','categories':['AI Systems & Technical Concepts'],'aliases':['Cross Encoder'],'status':'Established retrieval model term','partOfSpeech':'noun','related':['reranker','embedding','dense-retrieval'],'sources':[{'id':'sentence-transformers-cross-encoder','type':'reference','publisher':'Sentence Transformers','title':'Cross Encoder — Usage','published':'2026','url':'https://www.sbert.net/docs/cross_encoder/usage/usage.html','supports':['definition','usage','technical-definition']}]},
{'term':'Dense Retrieval','slug':'dense-retrieval','pronunciation':'dens ree-TREE-vul','definition':'A retrieval approach that represents queries and documents as dense vector embeddings and retrieves items whose vectors are close in the embedding space.','example':'The RAG system used dense retrieval to find semantically similar passages even when they did not share the same keywords as the query.','categories':['AI Systems & Technical Concepts'],'aliases':['Dense vector retrieval'],'status':'Established retrieval term','partOfSpeech':'noun','related':['embedding','vector-database','reranker'],'sources':[{'id':'sentence-transformers-dense-retrieval','type':'reference','publisher':'Sentence Transformers','title':'Retrieve & Re-Rank','published':'2026','url':'https://www.sbert.net/examples/sentence_transformer/applications/retrieve_rerank/README.html','supports':['definition','usage','technical-definition']}]},
{'term':'AI Bill of Materials','slug':'ai-bill-of-materials','pronunciation':'A-I bill of muh-TEER-ee-uls','definition':'A structured inventory of components, models, data-related artifacts, dependencies, and other supply-chain information associated with an AI system, intended to improve transparency, security, and traceability.','example':'The security review requested an AI Bill of Materials so the team could identify the models and dependencies included in the deployed system.','categories':['AI Risks, Safety & Governance','AI Systems & Technical Concepts'],'aliases':['AIBOM','AI BOM'],'status':'Established emerging supply-chain governance term','partOfSpeech':'noun','related':['ai-governance','ai-security','model-card'],'sources':[{'id':'owasp-aibom-2026','type':'primary','publisher':'OWASP GenAI Security Project','title':'AI Bill of Materials','published':'2026','url':'https://genai.owasp.org/initiatives/ai-sbom-initiative/','supports':['definition','usage','risk','governance']}]},
{'term':'Model Risk Management','slug':'model-risk-management','pronunciation':'MOD-ul risk MAN-ij-ment','definition':'The governance, validation, monitoring, and control practices used to identify and manage risks arising from the development, use, limitations, and outputs of models. In current U.S. banking guidance, generative and agentic AI are explicitly outside that guidance’s scope.','example':'The bank updated its model risk management process to require independent validation and ongoing monitoring for models within the supervisory framework’s scope.','categories':['AI Risks, Safety & Governance','AI Ways of Working'],'aliases':['MRM'],'status':'Established risk-management term','partOfSpeech':'noun','related':['ai-risk-management','ai-governance','model-card'],'sources':[{'id':'fed-model-risk-management-2026','type':'primary','publisher':'Federal Reserve','title':'Supervisory Guidance on Model Risk Management','published':'2026-04-17','url':'https://www.federalreserve.gov/frrs/guidance/supervisory-guidance-on-model-risk-management.htm','supports':['definition','usage','governance','scope']}]},
{'term':'AI Accountability','slug':'ai-accountability','pronunciation':'A-I uh-kown-tuh-BIL-uh-tee','definition':'The principle and practice of assigning responsibility to AI actors and organizations for the proper functioning, governance, risk management, and consequences of AI systems according to their roles and ability to act.','example':'The governance framework strengthened AI accountability by naming responsible owners for risk decisions and escalation.','categories':['AI Risks, Safety & Governance'],'aliases':['Artificial intelligence accountability'],'status':'Established governance principle','partOfSpeech':'noun','related':['ai-governance','responsible-ai','human-oversight'],'sources':[{'id':'oecd-ai-accountability','type':'primary','publisher':'OECD','title':'OECD AI Principles — Accountability','published':'2024','url':'https://oecd.ai/en/ai-principles','supports':['definition','governance']},{'id':'nist-govern-accountability','type':'primary','publisher':'NIST AI Resource Center','title':'AI RMF Playbook — Govern','published':'2026','url':'https://airc.nist.gov/airmf-resources/playbook/govern/','supports':['usage','governance']}]},
{'term':'AI Compliance','slug':'ai-compliance','pronunciation':'A-I kum-PLY-uns','definition':'The organizational practice of determining, documenting, and maintaining whether AI systems and related activities satisfy applicable legal, regulatory, contractual, and internal-policy requirements.','example':'The company’s AI compliance review mapped the system to the obligations that applied under the EU AI Act.','categories':['AI Risks, Safety & Governance','AI Ways of Working'],'aliases':['Artificial intelligence compliance'],'status':'Established emerging governance term','partOfSpeech':'noun','related':['ai-governance','ai-act','ai-risk-management'],'sources':[{'id':'eu-ai-act-compliance-platform','type':'primary','publisher':'European Commission AI Office','title':'AI Act Single Information Platform','published':'2026','url':'https://ai-act-service-desk.ec.europa.eu/en','supports':['definition','usage','regulation']},{'id':'nist-ai-legal-requirements','type':'primary','publisher':'NIST AI Resource Center','title':'AI RMF Playbook — Govern','published':'2026','url':'https://airc.nist.gov/airmf-resources/playbook/govern/','supports':['usage','governance']}]}
]
def page(t):
 u=f'{BASE}/terms/{t["slug"]}/'; n=escape(t['term']); d=escape(t['definition'],quote=True); p=escape(t['pronunciation']); ld=json.dumps({'@context':'https://schema.org','@type':'DefinedTerm','name':t['term'],'description':t['definition'],'url':u,'inDefinedTermSet':BASE+'/','inLanguage':'en'},ensure_ascii=False)
 return f'<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{n} | EpochLex</title><meta name="description" content="{d}"><link rel="canonical" href="{u}"><script type="application/ld+json">{ld}</script><link rel="stylesheet" href="../../assets/css/styles.css"><link rel="stylesheet" href="../../assets/css/term-pages.css"><link rel="stylesheet" href="../../assets/css/brand-theme.css"></head><body><main id="term-page" class="term-page shell" data-term-slug="{t["slug"]}"><div id="term-fallback" class="term-fallback"><nav class="term-breadcrumb"><a href="../../">Browse</a><span>/</span><span>{n}</span></nav><p class="eyebrow">EpochLex entry</p><h1>{n}</h1><p class="fallback-pronunciation">{p}</p><p class="fallback-definition">{escape(t["definition"])}</p></div></main><script src="../../assets/js/app.js"></script><script src="../../assets/js/term-page.js"></script></body></html>\n'
tp=R/'data/terms.json'; terms=json.loads(tp.read_text()); existing={x['slug'] for x in terms}
for b in B:
 if b['slug'] in existing: raise SystemExit('already published: '+b['slug'])
 rec={k:v for k,v in b.items() if k not in ('related','sources')}; rec.update({'added':D,'lastReviewed':D,'sources':[]}); terms.append(rec)
terms.sort(key=lambda x:x['term'].lower()); tp.write_text(json.dumps(terms,ensure_ascii=False,separators=(',',':'))+'\n')
pp=R/'data/provenance.json'; prov=json.loads(pp.read_text())
for b in B: prov[b['slug']]={'researchStatus':'pending','origin':None,'firstKnownUse':None,'history':[],'relatedTerms':b['related'],'sources':b['sources']}
pp.write_text(json.dumps(prov,ensure_ascii=False,indent=2)+'\n')
for b in B:
 p=R/'terms'/b['slug']; p.mkdir(parents=True,exist_ok=True); (p/'index.html').write_text(page(b))
cp=R/'docs/CORPUS-CANDIDATES.md'; text=cp.read_text(); labels={'Local Inference':'Local Inference','Agent Telemetry':'Agent Telemetry','Evaluation Trace':'Evaluation Trace','MCP Progress Notification':'MCP Progress Notification','Cross-Encoder':'Cross-Encoder','Dense Retrieval':'Dense Retrieval','AI Bill of Materials':'AI Bill of Materials (AIBOM)','Model Risk Management':'Model Risk Management','AI Accountability':'AI Accountability','AI Compliance':'AI Compliance'}
for b in B: text=re.sub(r'^- '+re.escape(labels[b['term']])+r'\s*$','',text,flags=re.M)
text=re.sub(r'\n{3,}','\n\n',text); st=text.index('## Repository roadmap candidates'); en=text.index('## Related documentation'); count=sum(1 for line in text[st:en].splitlines() if line.startswith('- ')); text=re.sub(r'\*\*Current unpublished inventory: \d+ candidates\.\*\*',f'**Current unpublished inventory: {count} candidates.**',text,count=1); cp.write_text(text)
ap=R/'docs/CORPUS-AUDIT-2026-09.md'; a=ap.read_text(); sec='\n## Research Further promotion pass 12 — Batch P (published September 8, 2026)\n\nThis batch is the twelfth evidence-based promotion from **Research Further**. Promotion records an audit decision for these entries; it does not create a permanent lifecycle state or automatic promotion rule.\n\n'
for b in B:
 src='; '.join(f"[{s['publisher']}: {s['title']}]({s['url']})" for s in b['sources']); sec+=f"### {b['term']}\n\n**Why promote and publish:** {b['definition']}\n\n**Usage evidence:** {src}\n\n**Provenance state:** `pending` — meaning/usage evidence is recorded; origin, first-known-use, and fuller history research remain open.\n\n"
a=a.replace('## Research Further',sec+'## Research Further',1); a=re.sub(r'This audit has now published \d+ candidates across Batches A–O and added 172 new research candidates\.', 'This audit has now published 153 candidates across Batches A–P and added 172 new research candidates.', a); ap.write_text(re.sub(r'\n{3,}','\n\n',a))
rp=R/'docs/ROADMAP.md'; r=rp.read_text().replace('- 265 published dictionary entries;','- 275 published dictionary entries;').replace('- 122 researched provenance records and 143 pending provenance records in the current published corpus;','- 122 researched provenance records and 153 pending provenance records in the current published corpus;'); rp.write_text(r)
sp=R/'sitemap.xml'; sm=sp.read_text(); blocks=''.join(f'  <url>\n    <loc>{BASE}/terms/{b["slug"]}/</loc>\n    <lastmod>{D}</lastmod>\n  </url>\n' for b in B); sp.write_text(sm.replace('</urlset>',blocks+'</urlset>'))
terms=json.loads(tp.read_text()); prov=json.loads(pp.read_text()); slugs={x['slug'] for x in terms}
assert len(terms)==275, len(terms); assert slugs==set(prov); assert sum(x.get('researchStatus')=='pending' for x in prov.values())==153
assert count==597, count
for b in B: assert (R/'terms'/b['slug']/'index.html').exists()
for slug,p in prov.items():
 for rel in p.get('relatedTerms',[]): assert rel in slugs,(slug,rel)
print('Validated Batch P: 275 published, 153 pending, 597 candidates.')