#!/usr/bin/env python3
import json,re
from pathlib import Path
from html import escape
R=Path(__file__).resolve().parents[1]; D='2026-09-08'; BASE='https://epochlex.justathoughtblog.org'
B=[
{'term':'Byte-Pair Encoding (BPE)','slug':'byte-pair-encoding','pronunciation':'BYTE pair en-KOH-ding','definition':'A subword tokenization algorithm that builds a vocabulary by repeatedly merging frequently occurring adjacent symbols or token pairs, allowing common sequences to become single tokens while less common text remains split into smaller units.','example':'The tokenizer used byte-pair encoding so common word pieces became single tokens while unusual words were split into smaller subword units.','categories':['AI Systems & Technical Concepts'],'aliases':['Byte Pair Encoding','BPE'],'status':'Established tokenization algorithm','partOfSpeech':'noun','related':['tokenization'],'sources':[{'id':'hf-bpe-2026','type':'primary','publisher':'Hugging Face','title':'Tokenization algorithms — Byte pair encoding (BPE)','published':'2026','url':'https://huggingface.co/docs/transformers/main/tokenizer_summary','supports':['definition','usage','technical-definition']},{'id':'hf-tokenizers-bpe-2026','type':'primary','publisher':'Hugging Face','title':'Tokenizers Models — BPE','published':'2026','url':'https://huggingface.co/docs/tokenizers/main/api/models','supports':['technical-definition']}]},
{'term':'Autoregressive Model','slug':'autoregressive-model','pronunciation':'aw-toh-ree-GRESS-iv MOD-ul','definition':'A model that generates or predicts a sequence one step at a time, with each new prediction conditioned on earlier elements of the sequence, including the model’s own previous outputs during generation.','example':'The language model is autoregressive, predicting each next token from the tokens that came before it.','categories':['AI Systems & Technical Concepts'],'aliases':['Auto-regressive model'],'status':'Established model architecture term','partOfSpeech':'noun','related':['transformer','inference'],'sources':[{'id':'google-autoregressive-glossary-2026','type':'primary','publisher':'Google for Developers','title':'Machine Learning Glossary — auto-regressive model','published':'2026','url':'https://developers.google.com/machine-learning/glossary','supports':['definition','usage','technical-definition']},{'id':'hf-causal-lm-2026','type':'primary','publisher':'Hugging Face','title':'Causal language modeling','published':'2026','url':'https://huggingface.co/docs/transformers/tasks/language_modeling','supports':['usage','technical-definition']}]},
{'term':'Encoder','slug':'encoder','pronunciation':'en-KOH-der','definition':'The component of an encoder-decoder or related neural architecture that transforms input data into hidden representations that capture information the model can use for downstream prediction or generation.','example':'The encoder converted the source sentence into hidden states that the decoder used when producing the translation.','categories':['AI Systems & Technical Concepts'],'aliases':['Model encoder'],'status':'Established neural-network architecture term','partOfSpeech':'noun','related':['decoder','transformer','embedding'],'sources':[{'id':'hf-encoder-decoder-2026','type':'primary','publisher':'Hugging Face','title':'Encoder Decoder Models','published':'2026','url':'https://huggingface.co/docs/transformers/model_doc/encoder-decoder','supports':['definition','usage','technical-definition']},{'id':'vaswani-transformer-2017','type':'research','publisher':'arXiv','title':'Attention Is All You Need','published':'2017-06-12','url':'https://arxiv.org/abs/1706.03762','supports':['technical-definition','history']}]},
{'term':'Decoder','slug':'decoder','pronunciation':'dee-KOH-der','definition':'The component of an encoder-decoder or generative neural architecture that produces output representations or tokens, often using prior generated tokens and, when present, information produced by an encoder.','example':'The decoder generated the translated sentence token by token while attending to the encoder’s hidden states.','categories':['AI Systems & Technical Concepts'],'aliases':['Model decoder'],'status':'Established neural-network architecture term','partOfSpeech':'noun','related':['encoder','transformer','cross-attention'],'sources':[{'id':'hf-encoder-decoder-2026','type':'primary','publisher':'Hugging Face','title':'Encoder Decoder Models','published':'2026','url':'https://huggingface.co/docs/transformers/model_doc/encoder-decoder','supports':['definition','usage','technical-definition']},{'id':'vaswani-transformer-2017','type':'research','publisher':'arXiv','title':'Attention Is All You Need','published':'2017-06-12','url':'https://arxiv.org/abs/1706.03762','supports':['technical-definition','history']}]},
{'term':'Cross-Attention','slug':'cross-attention','pronunciation':'KROSS uh-TEN-shun','definition':'An attention mechanism in which one sequence or representation supplies the queries while a different sequence or representation supplies the keys and values, allowing information from one source to guide processing of another.','example':'The decoder used cross-attention to focus on relevant encoder states while generating each translated token.','categories':['AI Systems & Technical Concepts'],'aliases':['Cross attention'],'status':'Established attention mechanism','partOfSpeech':'noun','related':['encoder','decoder','transformer'],'sources':[{'id':'hf-cross-attention-2026','type':'primary','publisher':'Hugging Face','title':'Encoder Decoder Models','published':'2026','url':'https://huggingface.co/docs/transformers/model_doc/encoder-decoder','supports':['definition','usage','technical-definition']},{'id':'vaswani-transformer-2017','type':'research','publisher':'arXiv','title':'Attention Is All You Need','published':'2017-06-12','url':'https://arxiv.org/abs/1706.03762','supports':['technical-definition','history']}]},
{'term':'Softmax','slug':'softmax','pronunciation':'SOFT-maks','definition':'A function that converts a set of numeric scores into nonnegative values that sum to one, commonly used to turn model logits into a probability distribution over possible classes or tokens.','example':'The model applied softmax to the output logits to obtain probabilities for each possible next token.','categories':['AI Systems & Technical Concepts'],'aliases':['Softmax function'],'status':'Established machine-learning function','partOfSpeech':'noun','related':['logit'],'sources':[{'id':'pytorch-softmax-2026','type':'primary','publisher':'PyTorch','title':'Softmax','published':'2026','url':'https://docs.pytorch.org/docs/stable/generated/torch.nn.modules.activation.Softmax.html','supports':['definition','technical-definition']},{'id':'google-softmax-glossary-2026','type':'primary','publisher':'Google for Developers','title':'Machine Learning Glossary — softmax','published':'2026','url':'https://developers.google.com/machine-learning/glossary','supports':['definition','usage']}]},
{'term':'Logit','slug':'logit','pronunciation':'LOH-jit','definition':'A raw, unnormalized prediction score produced by a model before a normalization step such as softmax converts a set of scores into probabilities.','example':'The decoder produced one logit for every vocabulary token before softmax converted those scores into next-token probabilities.','categories':['AI Systems & Technical Concepts'],'aliases':['Model logit','Logits'],'status':'Established machine-learning term','partOfSpeech':'noun','related':['softmax','decoder'],'sources':[{'id':'hf-logits-encoder-decoder-2026','type':'primary','publisher':'Hugging Face','title':'Encoder Decoder Models','published':'2026','url':'https://huggingface.co/docs/transformers/model_doc/encoder-decoder','supports':['definition','usage','technical-definition']}]},
{'term':'Perplexity','slug':'perplexity','pronunciation':'per-PLEK-suh-tee','definition':'A metric for evaluating autoregressive language models based on the exponentiated average negative log-likelihood of a sequence; lower perplexity indicates that the model assigns higher probability to the observed text under the same tokenization and evaluation setup.','example':'The team compared perplexity on the same held-out corpus to see which language model predicted the text more confidently.','categories':['AI Systems & Technical Concepts','AI Ways of Working'],'aliases':['PPL'],'status':'Established language-model evaluation metric','partOfSpeech':'noun','related':['autoregressive-model','eval'],'sources':[{'id':'hf-perplexity-2026','type':'primary','publisher':'Hugging Face','title':'Perplexity of fixed-length models','published':'2026','url':'https://huggingface.co/docs/transformers/v4.57.1/en/perplexity','supports':['definition','usage','technical-definition','evaluation']},{'id':'hf-causal-perplexity-2026','type':'primary','publisher':'Hugging Face','title':'Causal language modeling','published':'2026','url':'https://huggingface.co/docs/transformers/tasks/language_modeling','supports':['usage','evaluation']}]},
{'term':'Multimodal Model','slug':'multimodal-model','pronunciation':'mul-tee-MOH-dul MOD-ul','definition':'An AI model designed to process, relate, or generate information across more than one data modality, such as text, images, audio, or video.','example':'The multimodal model analyzed a photograph and a written question together before producing a text answer.','categories':['AI Systems & Technical Concepts'],'aliases':['Multimodal AI model'],'status':'Established AI model category','partOfSpeech':'noun','related':['multimodal-benchmark','text-to-video'],'sources':[{'id':'hf-multimodal-generation-2026','type':'primary','publisher':'Hugging Face','title':'Multimodal Generation','published':'2026','url':'https://huggingface.co/docs/transformers/main/tasks/any_to_any','supports':['definition','usage','technical-definition']}]},
{'term':'FlashAttention','slug':'flashattention','pronunciation':'FLASH uh-TEN-shun','definition':'An IO-aware exact attention algorithm that reorganizes attention computation into blocks to reduce memory reads and writes between GPU memory levels, improving speed and memory efficiency without approximating the attention result.','example':'The inference stack enabled FlashAttention to reduce attention memory traffic and improve throughput on long sequences.','categories':['AI Systems & Technical Concepts'],'aliases':['Flash Attention','FlashAttention-1'],'status':'Established optimized attention algorithm','partOfSpeech':'noun','related':['transformer','kv-cache'],'sources':[{'id':'dao-flashattention-2022','type':'research','publisher':'arXiv','title':'FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness','published':'2022-05-27','url':'https://arxiv.org/abs/2205.14135','supports':['definition','technical-definition','history']},{'id':'hf-attention-backends-2026','type':'primary','publisher':'Hugging Face','title':'Attention backends','published':'2026','url':'https://huggingface.co/docs/transformers/en/attention_interface','supports':['usage','technical-definition']}]}
]
def page(t):
 u=f'{BASE}/terms/{t["slug"]}/'; n=escape(t['term']); d=escape(t['definition'],quote=True); p=escape(t['pronunciation']); ld=json.dumps({'@context':'https://schema.org','@type':'DefinedTerm','name':t['term'],'description':t['definition'],'url':u,'inDefinedTermSet':BASE+'/','inLanguage':'en'},ensure_ascii=False)
 return f'<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{n} | EpochLex</title><meta name="description" content="{d}"><link rel="canonical" href="{u}"><script type="application/ld+json">{ld}</script><link rel="stylesheet" href="../../assets/css/styles.css"><link rel="stylesheet" href="../../assets/css/term-pages.css"><link rel="stylesheet" href="../../assets/css/brand-theme.css"></head><body><main id="term-page" class="term-page shell" data-term-slug="{t["slug"]}"><div id="term-fallback" class="term-fallback"><nav class="term-breadcrumb"><a href="../../">Browse</a><span>/</span><span>{n}</span></nav><p class="eyebrow">EpochLex entry</p><h1>{n}</h1><p class="fallback-pronunciation">{p}</p><p class="fallback-definition">{escape(t["definition"])}</p></div></main><script src="../../assets/js/app.js"></script><script src="../../assets/js/term-page.js"></script></body></html>\n'
tp=R/'data/terms.json'; terms=json.loads(tp.read_text()); existing={x['slug'] for x in terms}
for b in B:
 if b['slug'] in existing: raise SystemExit('already published: '+b['slug'])
 rec={k:v for k,v in b.items() if k not in ('related','sources')}; rec.update({'added':D,'lastReviewed':D,'sources':[]}); terms.append(rec)
# Resolve two known candidate overlaps only if the canonical entries already carry the alias.
cleanup=[]
for slug,label in [('groundedness','Faithfulness'),('inference-time-scaling','Test-Time Scaling')]:
 t=next((x for x in terms if x['slug']==slug),None)
 if t and label in t.get('aliases',[]): cleanup.append(label)
terms.sort(key=lambda x:x['term'].lower()); tp.write_text(json.dumps(terms,ensure_ascii=False,separators=(',',':'))+'\n')
pp=R/'data/provenance.json'; prov=json.loads(pp.read_text())
for b in B: prov[b['slug']]={'researchStatus':'pending','origin':None,'firstKnownUse':None,'history':[],'relatedTerms':b['related'],'sources':b['sources']}
pp.write_text(json.dumps(prov,ensure_ascii=False,indent=2)+'\n')
for b in B:
 p=R/'terms'/b['slug']; p.mkdir(parents=True,exist_ok=True); (p/'index.html').write_text(page(b))
cp=R/'docs/CORPUS-CANDIDATES.md'; text=cp.read_text()
for label in [b['term'] for b in B]+cleanup: text=re.sub(r'^- '+re.escape(label)+r'\s*$','',text,flags=re.M)
text=re.sub(r'\n{3,}','\n\n',text); st=text.index('## Repository roadmap candidates'); en=text.index('## Related documentation'); count=sum(1 for line in text[st:en].splitlines() if line.startswith('- ')); text=re.sub(r'\*\*Current unpublished inventory: \d+ candidates\.\*\*',f'**Current unpublished inventory: {count} candidates.**',text,count=1); cp.write_text(text)
ap=R/'docs/CORPUS-AUDIT-2026-09.md'; a=ap.read_text(); sec='\n## Research Further promotion pass 21 — Batch Y (published September 8, 2026)\n\nThis batch is the twenty-first evidence-based promotion from **Research Further**. Promotion records an audit decision for these entries; it does not create a permanent lifecycle state or automatic promotion rule. This pass deliberately prioritizes foundational model-architecture vocabulary that remained underrepresented after earlier frontier and agent-focused expansion.\n\n'
for b in B:
 src='; '.join(f"[{s['publisher']}: {s['title']}]({s['url']})" for s in b['sources']); sec+=f"### {b['term']}\n\n**Why promote and publish:** {b['definition']}\n\n**Usage evidence:** {src}\n\n**Provenance state:** `pending` — meaning/usage evidence is recorded; origin, first-known-use, and fuller history research remain open.\n\n"
for label in cleanup:
 canonical='Groundedness' if label=='Faithfulness' else 'Inference-Time Scaling'
 sec+=f'### Alias disposition: {label}\n\n**Disposition:** Remove **{label}** from the unpublished candidate inventory because the existing published **{canonical}** entry already carries it as an alias. This is a consistency cleanup, not a new relationship type or lifecycle rule.\n\n'
a=a.replace('## Research Further',sec+'## Research Further',1); a=re.sub(r'This audit has now published \d+ candidates across Batches A–X and added 172 new research candidates\.', 'This audit has now published 243 candidates across Batches A–Y and added 172 new research candidates.', a); ap.write_text(re.sub(r'\n{3,}','\n\n',a))
rp=R/'docs/ROADMAP.md'; r=rp.read_text().replace('- 355 published dictionary entries;','- 365 published dictionary entries;').replace('- 122 researched provenance records and 233 pending provenance records in the current published corpus;','- 122 researched provenance records and 243 pending provenance records in the current published corpus;'); rp.write_text(r)
sp=R/'sitemap.xml'; sm=sp.read_text(); blocks=''.join(f'  <url>\n    <loc>{BASE}/terms/{b["slug"]}/</loc>\n    <lastmod>{D}</lastmod>\n  </url>\n' for b in B); sm=sm.replace('</urlset>',blocks+'</urlset>'); sp.write_text(sm)
# Validation
terms=json.loads(tp.read_text()); prov=json.loads(pp.read_text()); slugs={x['slug'] for x in terms}
assert len(terms)==365,len(terms); assert set(prov)==slugs,(len(prov),len(slugs)); assert sum(1 for x in prov.values() if x.get('researchStatus')=='pending')==243
for slug,p in prov.items():
 for rel in p.get('relatedTerms',[]): assert rel in slugs,(slug,rel)
for b in B: assert (R/'terms'/b['slug']/'index.html').exists()
ct=cp.read_text(); st=ct.index('## Repository roadmap candidates'); en=ct.index('## Related documentation'); actual=sum(1 for line in ct[st:en].splitlines() if line.startswith('- ')); assert actual==count
assert count==511-10-len(cleanup),(count,cleanup)
for label in cleanup: assert not re.search(r'^- '+re.escape(label)+r'\s*$',ct,flags=re.M)
print(json.dumps({'published':len(terms),'pending':243,'candidates':count,'alias_cleanup':cleanup,'batch':[b['term'] for b in B]},indent=2))
