#!/usr/bin/env python3
import json
from pathlib import Path
R=Path(__file__).resolve().parents[1]
RECORDS={
'ai-assurance':{'researchStatus':'researched','origin':'AI assurance is an umbrella practice concerned with building justified confidence that an AI system will perform as intended and that relevant risks, trustworthiness characteristics, and safeguards have been examined with credible evidence. The concept draws on older assurance practices in safety, security, software, and systems engineering rather than a single AI-era coinage.','firstKnownUse':None,'history':[{'date':'2022-03-15','event':'NIST researchers published “The Path to Consensus on Artificial Intelligence Assurance,” proposing a formalization of AI assurance across data quality, performance, trustworthiness, security, explainability, and related dimensions.'}],'sources':[{'id':'nist-ai-assurance-2022','type':'primary','publisher':'National Institute of Standards and Technology','title':'The Path to Consensus on Artificial Intelligence Assurance','published':'2022-03-15','url':'https://www.nist.gov/publications/path-consensus-artificial-intelligence-assurance','supports':['definition','history','usage']},{'id':'nist-assurance-glossary','type':'reference','publisher':'National Institute of Standards and Technology','title':'assurance - Glossary','published':None,'url':'https://csrc.nist.gov/glossary/term/assurance','supports':['definition','technical-definition']}]},
'high-risk-ai':{'researchStatus':'researched','origin':'High-risk AI is an established risk-classification label whose current legal meaning is strongly shaped by the EU AI Act. Under that framework, certain AI systems are classified as high-risk because of their role in regulated products or because specified uses can significantly affect health, safety, or fundamental rights. The broader phrase predates the Act, so EpochLex does not assign it to a single coinage.','firstKnownUse':None,'history':[{'date':'2024-08-01','event':'The EU AI Act entered into force, establishing a risk-based regulatory framework that includes a formal high-risk category.'},{'date':'2026-05-19','event':'The European Commission published draft guidelines to clarify classification of high-risk AI systems under Article 6 of the AI Act.'}],'sources':[{'id':'ec-high-risk-guidelines-2026','type':'primary','publisher':'European Commission','title':'Draft Commission guidelines on the classification of high-risk AI systems','published':'2026-05-19','url':'https://digital-strategy.ec.europa.eu/en/library/draft-commission-guidelines-classification-high-risk-ai-systems','supports':['definition','history','legal-scope']},{'id':'ec-ai-act-current','type':'primary','publisher':'European Commission','title':'AI Act','published':None,'url':'https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai','supports':['definition','history','legal-scope']}]},
'ai-safety-case':{'researchStatus':'researched','origin':'AI safety cases adapt the established safety-case practice from safety-critical engineering to AI systems. In frontier AI, a safety case is a structured argument, supported by evidence, that an AI system is acceptably safe within a specified training, deployment, application, or risk context. EpochLex does not treat the concept as having a single AI-era inventor.','firstKnownUse':None,'history':[{'date':'2024-08-23','event':'The UK AI Security Institute described safety cases as structured arguments for frontier AI safety and announced work on adapting them to advanced-model contexts.'},{'date':'2024-11-12','event':'Researchers submitted a frontier-AI safety-case template for an offensive-cyber inability argument.'}],'sources':[{'id':'aisi-safety-cases-2024','type':'primary','publisher':'UK AI Security Institute','title':'Safety cases at AISI','published':'2024-08-23','url':'https://www.aisi.gov.uk/blog/safety-cases-at-aisi','supports':['definition','history','usage']},{'id':'aisi-cyber-safety-case-2024','type':'primary','publisher':'UK AI Security Institute','title':'Safety case template for frontier AI: A cyber inability argument','published':'2024-12-12','url':'https://www.aisi.gov.uk/research/safety-case-template-for-frontier-ai-a-cyber-inability-argument-2','supports':['definition','history','technical-definition']}]},
'frontier-ai':{'researchStatus':'researched','origin':'Frontier AI is a policy and safety term for highly capable general-purpose AI models or systems near the leading edge of currently available capabilities. The phrase developed through research, industry, and government usage rather than one established coinage. A major policy milestone was the 2024 Seoul frontier-AI safety commitments, which explicitly defined the term for participating developers.','firstKnownUse':None,'history':[{'date':'2024-05-21','event':'The AI Seoul Summit frontier-AI safety commitments defined frontier AI as highly capable general-purpose AI models or systems that can perform a wide variety of tasks and match or exceed capabilities present in the most advanced models.'}],'sources':[{'id':'uk-frontier-ai-seoul-2024','type':'primary','publisher':'UK Government','title':'Frontier AI Safety Commitments, AI Seoul Summit 2024','published':'2024-05-21','url':'https://www.gov.uk/government/publications/frontier-ai-safety-commitments-ai-seoul-summit-2024/frontier-ai-safety-commitments-ai-seoul-summit-2024','supports':['definition','history','usage']},{'id':'aisi-frontier-trends-2025','type':'primary','publisher':'UK AI Security Institute','title':'AISI Frontier AI Trends Report (2025)','published':'2025','url':'https://www.aisi.gov.uk/research/aisi-frontier-ai-trends-report-2025','supports':['usage','history']}]},
'general-purpose-ai':{'researchStatus':'researched','origin':'General-purpose AI is a broad concept for AI models or systems capable of supporting many distinct tasks or downstream uses rather than being limited to one narrow purpose. The term predates the EU AI Act, but the Act and subsequent Commission guidance gave “general-purpose AI model” a formal regulatory definition and made the broader GPAI label especially prominent in policy and industry usage.','firstKnownUse':None,'history':[{'date':'2024-08-01','event':'The EU AI Act entered into force with formal provisions for general-purpose AI models.'},{'date':'2025-08-02','event':'EU obligations for providers of general-purpose AI models entered into application.'}],'sources':[{'id':'ec-gpai-qa','type':'primary','publisher':'European Commission','title':'General-Purpose AI Models in the AI Act – Questions & Answers','published':None,'url':'https://digital-strategy.ec.europa.eu/en/faqs/general-purpose-ai-models-ai-act-questions-answers','supports':['definition','legal-scope','usage']},{'id':'ec-gpai-guidelines','type':'primary','publisher':'European Commission','title':'Guidelines for providers of general-purpose AI models','published':'2025','url':'https://digital-strategy.ec.europa.eu/en/policies/guidelines-gpai-providers','supports':['history','usage','legal-scope']}]},
'ai-act':{'researchStatus':'researched','origin':'The AI Act is the European Union’s horizontal legal framework for artificial intelligence, built around a risk-based system of prohibited practices, obligations for high-risk AI systems, transparency duties, and rules for general-purpose AI models. Its development began with the European Commission’s 2021 legislative proposal and culminated in the regulation entering into force in 2024.','firstKnownUse':None,'history':[{'date':'2021-04-21','event':'The European Commission proposed a regulatory framework for artificial intelligence that became the basis of the AI Act.'},{'date':'2024-08-01','event':'The EU AI Act entered into force.'},{'date':'2025-02-02','event':'The first AI Act rules, including prohibited practices and AI literacy obligations, began to apply.'},{'date':'2025-08-02','event':'Governance rules and obligations for general-purpose AI models began to apply.'},{'date':'2026-08-02','event':'The AI Act became broadly applicable and Commission enforcement powers for GPAI obligations began to apply, with specified high-risk rules following later transition dates.'}],'sources':[{'id':'ec-ai-act-current','type':'primary','publisher':'European Commission','title':'AI Act','published':None,'url':'https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai','supports':['definition','history','legal-scope']},{'id':'ec-ai-act-navigation','type':'primary','publisher':'European Commission','title':'Navigating the AI Act','published':'2026','url':'https://digital-strategy.ec.europa.eu/en/faqs/navigating-ai-act','supports':['history','legal-scope','usage']}]},
'human-oversight':{'researchStatus':'researched','origin':'Human oversight is an established governance and safety concept referring to arrangements that keep appropriately empowered people able to supervise, interpret, intervene in, or stop an AI system when necessary. The concept predates current generative AI and appears in multiple governance frameworks; the EU AI Act makes human oversight an explicit requirement for high-risk AI systems.','firstKnownUse':None,'history':[{'date':'2024-08-01','event':'The EU AI Act entered into force with human oversight as an explicit requirement for high-risk AI systems.'}],'sources':[{'id':'ec-ai-act-human-oversight','type':'primary','publisher':'European Commission','title':'Navigating the AI Act','published':'2026','url':'https://digital-strategy.ec.europa.eu/en/faqs/navigating-ai-act','supports':['definition','history','legal-scope']},{'id':'nist-ai-rmf-core','type':'primary','publisher':'National Institute of Standards and Technology','title':'AI RMF Core','published':None,'url':'https://airc.nist.gov/airmf-resources/airmf/5-sec-core/','supports':['usage','governance']}]},
'ai-accountability':{'researchStatus':'researched','origin':'AI accountability is the governance principle that organizations and individuals responsible for AI systems should have defined responsibilities, traceable decisions, mechanisms for review and redress, and answerability for outcomes and risk-management actions. The phrase has no single established coinage and draws on older accountability traditions in law, governance, privacy, security, and organizational management.','firstKnownUse':None,'history':[{'date':'2023-01-26','event':'NIST released AI RMF 1.0, treating accountability and transparency as core characteristics of trustworthy AI and calling for clear accountability structures in AI risk management.'}],'sources':[{'id':'nist-ai-rmf-2023','type':'primary','publisher':'National Institute of Standards and Technology','title':'Artificial Intelligence Risk Management Framework (AI RMF 1.0)','published':'2023-01-26','url':'https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-ai-rmf-10','supports':['definition','history','usage']},{'id':'nist-ai-rmf-core','type':'primary','publisher':'National Institute of Standards and Technology','title':'AI RMF Core','published':None,'url':'https://airc.nist.gov/airmf-resources/airmf/5-sec-core/','supports':['definition','governance','usage']}]},
'trustworthy-ai':{'researchStatus':'researched','origin':'Trustworthy AI is a broad normative concept for AI that merits justified confidence because relevant qualities such as validity, reliability, safety, security, resilience, accountability, transparency, explainability, privacy, and fairness are addressed in context. The concept developed across standards, policy, and research rather than from a single coinage.','firstKnownUse':None,'history':[{'date':'2019-05-22','event':'OECD member countries adopted the OECD AI Principles, establishing an influential international framework for trustworthy AI.'},{'date':'2023-01-26','event':'NIST released AI RMF 1.0, organizing trustworthy-AI characteristics into an operational risk-management framework.'}],'sources':[{'id':'oecd-trustworthy-ai','type':'primary','publisher':'OECD.AI','title':'Catalogue of Tools & Metrics for Trustworthy AI - About','published':None,'url':'https://oecd.ai/en/catalogue/faq','supports':['definition','usage','governance']},{'id':'nist-ai-rmf-2023','type':'primary','publisher':'National Institute of Standards and Technology','title':'Artificial Intelligence Risk Management Framework (AI RMF 1.0)','published':'2023-01-26','url':'https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-ai-rmf-10','supports':['definition','history','usage']}]},
'local-inference':{'researchStatus':'researched','origin':'Local inference is the practice of running a trained model on a user-controlled local machine or local endpoint rather than sending each inference request to a third-party remote service. The practice grew from earlier local and edge machine-learning deployment patterns and does not have a single established coinage.','firstKnownUse':None,'history':[],'sources':[{'id':'hf-local-models','type':'primary','publisher':'Hugging Face','title':'Use AI Models Locally','published':None,'url':'https://huggingface.co/docs/hub/local-apps','supports':['definition','usage','technical-definition']},{'id':'hf-inference-client','type':'primary','publisher':'Hugging Face','title':'Inference','published':None,'url':'https://huggingface.co/docs/huggingface_hub/package_reference/inference_client','supports':['definition','usage','technical-definition']}]},
'ai-companion':{'researchStatus':'researched','origin':'AI companion is a broad product and research label for conversational AI systems used primarily for companionship-like interaction, emotional support, social connection, or an ongoing relationship rather than only task completion. The category developed across social-chatbot products and research and does not have a single established coinage.','firstKnownUse':None,'history':[{'date':'2026-08-04','event':'Nature Human Behaviour published a large study of AI-companion use and psychological well-being, reflecting the category’s maturation as a distinct research topic.'}],'sources':[{'id':'stanford-ai-index-companions-2026','type':'secondary','publisher':'Stanford Institute for Human-Centered Artificial Intelligence','title':'AI Index Report 2026 — AI Companions','published':'2026','url':'https://hai.stanford.edu/assets/files/ai_index_report_2026.pdf','supports':['definition','usage','history']},{'id':'nature-ai-companions-2026','type':'secondary','publisher':'Nature Human Behaviour','title':'Interaction with AI companions and psychological well-being','published':'2026-08-04','url':'https://www.nature.com/articles/s41562-026-02516-2','supports':['definition','usage','history']}]}
}
pp=R/'data/provenance.json'; prov=json.loads(pp.read_text())
for slug,record in RECORDS.items():
    assert slug in prov, slug
    assert prov[slug].get('researchStatus')=='pending',(slug,prov[slug].get('researchStatus'))
    record['relatedTerms']=prov[slug].get('relatedTerms',[])
    prov[slug]=record
pp.write_text(json.dumps(prov,indent=2,ensure_ascii=False)+'\n')
terms=json.loads((R/'data/terms.json').read_text()); published={t['slug'] for t in terms}
assert len(terms)==365 and set(prov)==published
for s,p in prov.items():
    for rel in p.get('relatedTerms',[]): assert rel in published,(s,rel)
researched=sum(p.get('researchStatus')=='researched' for p in prov.values()); pending=sum(p.get('researchStatus')=='pending' for p in prov.values())
assert researched==183 and pending==182,(researched,pending)
for s in RECORDS:
    assert prov[s]['sources'] and all(src.get('supports') for src in prov[s]['sources'])
rp=R/'docs/ROADMAP.md'; road=rp.read_text().replace('172 researched provenance records and 193 pending provenance records','183 researched provenance records and 182 pending provenance records'); rp.write_text(road)
qp=R/'docs/PROVENANCE-REVIEW-QUEUE-2026-09.md'; q=qp.read_text()
q=q.replace('including **172 researched** provenance records and **193 pending** records after provenance Batch 05.','including **183 researched** provenance records and **182 pending** records after provenance Batch 06.')
q=q.replace('Provenance Batches 01–05 completed 50 of the 61 Wave 1 records, leaving **11 Wave 1 reviews** to reach that milestone.','Provenance Batches 01–06 completed all 61 Wave 1 records. EpochLex has now crossed the first consolidation milestone with **183 researched** records and **182 pending** records.')
marker='## Wave 1 — Majority milestone (61)'
section='''## Provenance Batch 06 — completed September 8, 2026\n\nThis milestone batch completed the final 11 Wave 1 records, concentrating on governance, safety, trust, local inference, and AI companionship. All eleven records completed the initial human-reviewed provenance pass and now use `researchStatus: "researched"`.\n\n1. **AI Assurance**\n2. **High-Risk AI**\n3. **AI Safety Case**\n4. **Frontier AI**\n5. **General-Purpose AI**\n6. **AI Act**\n7. **Human Oversight**\n8. **AI Accountability**\n9. **Trustworthy AI**\n10. **Local Inference**\n11. **AI Companion**\n\n**Wave 1 milestone reached:** 61 of 61 Wave 1 records are researched, bringing the published corpus to **183 researched / 182 pending** without adding new entries.\n\n'''
assert marker in q; qp.write_text(q.replace(marker,section+marker,1))
print(json.dumps({'published':365,'researched':researched,'pending':pending,'batch':list(RECORDS)},indent=2))
