#!/usr/bin/env python3
import json,re
from pathlib import Path
from html import escape
R=Path(__file__).resolve().parents[1]; D='2026-09-08'; BASE='https://epochlex.justathoughtblog.org'
B=[
{'term':'Inference Server','slug':'inference-server','pronunciation':'IN-fer-ens SUR-ver','definition':'Server software that loads one or more trained AI models and exposes an interface, often an API, for receiving requests and running model inference.','example':'The team started an inference server so internal applications could send prompts to the locally hosted model.','categories':['AI Systems & Technical Concepts'],'aliases':['Model inference server'],'status':'Established deployment term','partOfSpeech':'noun','related':['inference','model-serving','local-ai','structured-output'],'sources':[{'id':'hf-transformers-serve-2026','type':'reference','publisher':'Hugging Face','title':'Serve CLI','published':'2026','url':'https://huggingface.co/docs/transformers/serve-cli/serving','supports':['definition','usage','technical-definition']}]},
{'term':'Model Serving','slug':'model-serving','pronunciation':'MOD-ul SUR-ving','definition':'The deployment and operation of a trained AI model so applications or users can send inference requests and receive outputs, typically through managed endpoints or inference servers.','example':'The production team separated model training from model serving so the deployed endpoint could scale independently.','categories':['AI Systems & Technical Concepts','AI Ways of Working'],'aliases':['AI model serving'],'status':'Established deployment term','partOfSpeech':'noun','related':['inference','inference-server','model-registry','ai-governance'],'sources':[{'id':'hf-jobs-serving-2026','type':'reference','publisher':'Hugging Face','title':'Serve Models on Jobs','published':'2026','url':'https://huggingface.co/docs/hub/jobs-serving','supports':['definition','usage']}]},
{'term':'GGUF','slug':'gguf','pronunciation':'G-G-U-F','definition':'A single-file model format used with GGML-compatible inference engines that stores model tensors together with standardized metadata and supports multiple quantized data types.','example':'The local inference setup downloaded a GGUF version of the model that fit comfortably in available memory.','categories':['AI Systems & Technical Concepts'],'aliases':['GGUF format'],'status':'Established model-format term','partOfSpeech':'noun','related':['local-ai','open-weight-model','qlora','on-device-ai'],'sources':[{'id':'hf-gguf-2026','type':'reference','publisher':'Hugging Face','title':'GGUF','published':'2026','url':'https://huggingface.co/docs/transformers/main/quantization/gguf','supports':['definition','usage','technical-definition']}]},
{'term':'4-Bit Quantization','slug':'4-bit-quantization','pronunciation':'four-bit kwon-tuh-ZAY-shun','definition':'A model-compression approach that represents model weights or other numerical values using 4-bit precision, substantially reducing memory requirements while potentially changing accuracy or performance.','example':'The team used 4-bit quantization so the model could run within the workstation’s available GPU memory.','categories':['AI Systems & Technical Concepts'],'aliases':['4-bit model quantization','Four-bit quantization'],'status':'Established technical term','partOfSpeech':'noun','related':['qlora','local-ai','open-weight-model','inference'],'sources':[{'id':'hf-bitsandbytes-4bit-2026','type':'reference','publisher':'Hugging Face','title':'Bitsandbytes','published':'2026','url':'https://huggingface.co/docs/transformers/main/quantization/bitsandbytes','supports':['definition','usage','technical-definition']}]},
{'term':'Safetensors','slug':'safetensors','pronunciation':'SAFE-ten-sers','definition':'A tensor serialization format designed to store model weights and other tensors safely and efficiently without relying on executable pickle-based serialization.','example':'The model repository provided Safetensors weights so the runtime could load the checkpoint without using a pickle file.','categories':['AI Systems & Technical Concepts'],'aliases':['Safetensors format','.safetensors'],'status':'Established model-format term','partOfSpeech':'noun','related':['model-weights','open-weight-model','fine-tuning','local-ai'],'sources':[{'id':'hf-safetensors-2026','type':'primary','publisher':'Hugging Face','title':'Safetensors','published':'2026','url':'https://huggingface.co/docs/safetensors/index','supports':['definition','usage','technical-definition']}]},
{'term':'Reranker','slug':'reranker','pronunciation':'ree-RANK-er','definition':'A model or component that takes an existing set of retrieved candidates and reorders them according to their estimated relevance to a query or task.','example':'The search pipeline used a reranker after retrieval to move the most relevant documents to the top of the context.','categories':['AI Systems & Technical Concepts'],'aliases':['Re-ranker','Rerank model'],'status':'Established retrieval term','partOfSpeech':'noun','related':['reranking','rag','hybrid-search','vector-search'],'sources':[{'id':'cohere-rerank-2026','type':'primary','publisher':'Cohere','title':'Cohere’s Rerank Model','published':'2026','url':'https://docs.cohere.com/docs/rerank','supports':['definition','usage']}]},
{'term':'Safety Evaluation','slug':'safety-evaluation','pronunciation':'SAYF-tee ih-val-yoo-AY-shun','definition':'The systematic testing of an AI model or system for safety-relevant behaviors, risks, safeguards, and failure modes under defined conditions or scenarios.','example':'The release process included safety evaluation for harmful compliance, refusal behavior, and agent actions before deployment.','categories':['AI Risks, Safety & Governance','AI Ways of Working'],'aliases':['AI safety evaluation','Safety eval'],'status':'Established evaluation term','partOfSpeech':'noun','related':['eval','red-teaming','ai-safety-case','ai-assurance'],'sources':[{'id':'nist-ai-metrology-safety-eval-2026','type':'primary','publisher':'NIST','title':'AI Metrology Center','published':'2026','url':'https://airc.nist.gov/metrology/','supports':['definition','usage','risk']}]},
{'term':'Pass@k','slug':'pass-at-k','pronunciation':'pass at kay','definition':'An evaluation metric estimating whether at least one successful solution appears among k independently sampled model outputs for the same task, commonly used in code-generation evaluation.','example':'The coding benchmark reported pass@10 because the model was allowed ten sampled attempts at each problem.','categories':['AI Systems & Technical Concepts'],'aliases':['Pass at k','pass@k metric'],'status':'Established evaluation metric','partOfSpeech':'noun','related':['eval','benchmark','sampling'],'sources':[{'id':'chen-codex-passk-2021','type':'primary','publisher':'OpenAI researchers','title':'Evaluating Large Language Models Trained on Code','published':'2021-07-07','url':'https://arxiv.org/abs/2107.03374','supports':['definition','usage','history']}]},
{'term':'Group Relative Policy Optimization','slug':'group-relative-policy-optimization','pronunciation':'groop REL-uh-tiv POL-uh-see op-tuh-muh-ZAY-shun','definition':'A reinforcement-learning post-training method in which a model generates groups of candidate completions, receives rewards for them, and updates its policy using advantages computed relative to other completions in the group.','example':'The reasoning model used Group Relative Policy Optimization to learn from reward differences among several generated answers to each prompt.','categories':['AI Systems & Technical Concepts'],'aliases':['GRPO'],'status':'Established post-training term','partOfSpeech':'noun','related':['direct-preference-optimization','ai-alignment','fine-tuning','reasoning-effort'],'sources':[{'id':'hf-grpo-trainer-2026','type':'reference','publisher':'Hugging Face','title':'GRPO Trainer','published':'2026','url':'https://huggingface.co/docs/trl/grpo_trainer','supports':['definition','usage','technical-definition']}]},
{'term':'Model Registry','slug':'model-registry','pronunciation':'MOD-ul REJ-uh-stree','definition':'A managed catalog for recording model versions and associated metadata, evaluation information, lifecycle status, approvals, or deployment references so models can be governed and promoted through operational workflows.','example':'The approved checkpoint was registered in the model registry before the deployment pipeline released it to production.','categories':['AI Systems & Technical Concepts','AI Risks, Safety & Governance'],'aliases':['AI model registry'],'status':'Established MLOps term','partOfSpeech':'noun','related':['ai-governance','model-card','system-card','model-serving'],'sources':[{'id':'aws-model-registry-2026','type':'primary','publisher':'AWS','title':'Model Registration Deployment with Model Registry','published':'2026','url':'https://docs.aws.amazon.com/sagemaker/latest/dg/model-registry.html','supports':['definition','usage','governance']}]}
]
def page(t):
 u=f'{BASE}/terms/{t["slug"]}/'; n=escape(t['term']); d=escape(t['definition'],quote=True); p=escape(t['pronunciation']); ld=json.dumps({'@context':'https://schema.org','@type':'DefinedTerm','name':t['term'],'description':t['definition'],'url':u,'inDefinedTermSet':BASE+'/','inLanguage':'en'},ensure_ascii=False)
 return f'<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{n} | EpochLex</title><meta name="description" content="{d}"><link rel="canonical" href="{u}"><script type="application/ld+json">{ld}</script><link rel="stylesheet" href="../../assets/css/styles.css"><link rel="stylesheet" href="../../assets/css/term-pages.css"><link rel="stylesheet" href="../../assets/css/brand-theme.css"></head><body><main id="term-page" class="term-page shell" data-term-slug="{t["slug"]}"><div id="term-fallback" class="term-fallback"><nav class="term-breadcrumb"><a href="../../">Browse</a><span>/</span><span>{n}</span></nav><p class="eyebrow">EpochLex entry</p><h1>{n}</h1><p class="fallback-pronunciation">{p}</p><p class="fallback-definition">{escape(t["definition"])}</p></div></main><script src="../../assets/js/app.js"></script><script src="../../assets/js/term-page.js"></script></body></html>\n'
tp=R/'data/terms.json'; terms=json.loads(tp.read_text()); existing={x['slug'] for x in terms}
for b in B:
 if b['slug'] in existing: raise SystemExit('already published: '+b['slug'])
 rec={k:v for k,v in b.items() if k not in ('related','sources')}; rec.update({'added':D,'lastReviewed':D,'sources':[]}); terms.append(rec)
terms.sort(key=lambda x:x['term'].lower()); tp.write_text(json.dumps(terms,ensure_ascii=False,separators=(',',':'))+'\n')
pp=R/'data/provenance.json'; prov=json.loads(pp.read_text())
for b in B: prov[b['slug']]={'researchStatus':'pending','origin':None,'firstKnownUse':None,'history':[],'relatedTerms':b['related'],'sources':b['sources']}
pp.write_text(json.dumps(prov,ensure_ascii=False,indent=2)+'\n')
for b in B:
 p=R/'terms'/b['slug']; p.mkdir(parents=True,exist_ok=True); (p/'index.html').write_text(page(b))
cp=R/'docs/CORPUS-CANDIDATES.md'; text=cp.read_text(); labels={b['term']:b['term'] for b in B}; labels['Group Relative Policy Optimization']='Group Relative Policy Optimization (GRPO)'
for b in B: text=re.sub(r'^- '+re.escape(labels[b['term']])+r'\s*$','',text,flags=re.M)
text=re.sub(r'\n{3,}','\n\n',text); st=text.index('## Repository roadmap candidates'); en=text.index('## Related documentation'); count=sum(1 for line in text[st:en].splitlines() if line.startswith('- ')); text=re.sub(r'\*\*Current unpublished inventory: \d+ candidates\.\*\*',f'**Current unpublished inventory: {count} candidates.**',text,count=1); cp.write_text(text)
ap=R/'docs/CORPUS-AUDIT-2026-09.md'; a=ap.read_text(); sec='\n## Research Further promotion pass 5 — Batch I (published September 8, 2026)\n\nThis batch is the fifth evidence-based promotion from **Research Further**. Promotion records an audit decision for these entries; it does not create a permanent lifecycle state or automatic promotion rule.\n\n'
for b in B:
 src='; '.join(f"[{s['publisher']}: {s['title']}]({s['url']})" for s in b['sources']); sec+=f"### {b['term']}\n\n**Why promote and publish:** {b['definition']}\n\n**Usage evidence:** {src}\n\n**Provenance state:** `pending` — meaning/usage evidence is recorded; origin, first-known-use, and fuller history research remain open.\n\n"
a=a.replace('## Research Further',sec+'## Research Further',1); a=a.replace('This audit has now published 73 candidates across Batches A–H and added 172 new research candidates.','This audit has now published 83 candidates across Batches A–I and added 172 new research candidates.'); ap.write_text(re.sub(r'\n{3,}','\n\n',a))
rp=R/'docs/ROADMAP.md'; r=rp.read_text().replace('- 195 published dictionary entries;','- 205 published dictionary entries;').replace('- 122 researched provenance records and 73 pending provenance records in the current published corpus;','- 122 researched provenance records and 83 pending provenance records in the current published corpus;'); rp.write_text(r)
sp=R/'sitemap.xml'; sm=sp.read_text(); blocks=''.join(f'  <url>\n    <loc>{BASE}/terms/{b["slug"]}/</loc>\n    <lastmod>{D}</lastmod>\n  </url>\n' for b in B); sp.write_text(sm.replace('</urlset>',blocks+'</urlset>'))
terms=json.loads(tp.read_text()); prov=json.loads(pp.read_text()); slugs={x['slug'] for x in terms}
assert len(terms)==205, len(terms); assert slugs==set(prov); assert sum(x.get('researchStatus')=='pending' for x in prov.values())==83
for rec in prov.values():
 for s in rec.get('relatedTerms',[]): assert s in slugs, s
for b in B: assert (R/'terms'/b['slug']/'index.html').exists()
assert count==667, count
print('Validated Batch I: 205 published, 83 pending, 667 candidates, related-term parity.')
