#!/usr/bin/env python3
import json,re
from pathlib import Path
from html import escape
R=Path(__file__).resolve().parents[1]; D='2026-09-08'; BASE='https://epochlex.justathoughtblog.org'
B=[
{'term':'Agent-to-Agent (A2A)','slug':'agent-to-agent-a2a','pronunciation':'AY-jent too AY-jent, A-two-A','definition':'An open interoperability protocol that lets independent AI agents discover one another, exchange information, delegate work, and collaborate across different frameworks, vendors, and services.','example':'The travel-planning agent used A2A to delegate a booking task to a separate agent operated by another service.','categories':['AI Systems & Technical Concepts','AI Ways of Working'],'aliases':['Agent2Agent','A2A','Agent-to-Agent Protocol'],'status':'Established agent interoperability standard','partOfSpeech':'noun','related':['ai-agent','multi-agent-orchestration','mcp'],'sources':[{'id':'a2a-v1-docs-2026','type':'primary','publisher':'A2A Protocol','title':'Agent2Agent (A2A) Protocol','published':'2026','url':'https://a2a-protocol.org/v1.0.0/','supports':['definition','usage','technical-definition']},{'id':'linux-foundation-a2a-2026','type':'primary','publisher':'Linux Foundation','title':'A2A Protocol Surpasses 150 Organizations, Lands in Major Cloud Platforms, and Sees Enterprise Production Use in First Year','published':'2026-04-09','url':'https://www.linuxfoundation.org/press/a2a-protocol-surpasses-150-organizations-lands-in-major-cloud-platforms-and-sees-enterprise-production-use-in-first-year','supports':['usage','status']}]},
{'term':'Supervisor Agent','slug':'supervisor-agent','pronunciation':'SOO-per-vy-zur AY-jent','definition':'An agent that coordinates other agents or tools by deciding how work should be delegated, sequenced, or routed and by combining their results toward a larger task.','example':'The supervisor agent routed tax questions to one specialist agent and payroll questions to another before returning a combined response.','categories':['AI Systems & Technical Concepts','AI Ways of Working'],'aliases':['Agent supervisor','Supervisory agent'],'status':'Established multi-agent orchestration pattern','partOfSpeech':'noun','related':['multi-agent-orchestration','ai-agent','agent-runtime'],'sources':[{'id':'microsoft-databricks-supervisor-2026','type':'primary','publisher':'Microsoft Learn','title':'Use Supervisor Agent to create a coordinated multi-agent system','published':'2026-08','url':'https://learn.microsoft.com/en-us/azure/databricks/generative-ai/agent-bricks/multi-agent-supervisor','supports':['definition','usage','technical-definition']}]},
{'term':'Agent Memory','slug':'agent-memory','pronunciation':'AY-jent MEM-uh-ree','definition':'Stored or retrievable information from prior interactions, sessions, or external context that an AI agent can use to maintain continuity and influence later behavior or responses.','example':'Agent memory allowed the assistant to retrieve relevant details from earlier conversations instead of starting each session without context.','categories':['AI Systems & Technical Concepts'],'aliases':['AI agent memory'],'status':'Established agent architecture term','partOfSpeech':'noun','related':['ai-agent','agent-state','vector-database'],'sources':[{'id':'microsoft-agent-memory-2026','type':'primary','publisher':'Microsoft Learn','title':'Chat History Memory Provider','published':'2026-09-01','url':'https://learn.microsoft.com/en-us/agent-framework/concepts/agents/conversations/chat-history-memory-provider','supports':['definition','usage','technical-definition']},{'id':'microsoft-agent-conversations-2026','type':'primary','publisher':'Microsoft Learn','title':'Conversations & Memory overview','published':'2026-08-25','url':'https://learn.microsoft.com/en-us/agent-framework/agents/conversations/','supports':['usage','technical-definition']}]},
{'term':'Outcome Reward Model','slug':'outcome-reward-model','pronunciation':'OUT-kum ree-WORD MOD-ul','definition':'A reward model that scores a complete response or trajectory based on its final outcome rather than assigning separate rewards to intermediate reasoning steps.','example':'The training pipeline used an outcome reward model to score whether each completed mathematical solution was correct.','categories':['AI Systems & Technical Concepts'],'aliases':['ORM'],'status':'Established post-training term','partOfSpeech':'noun','related':['process-reward-model','reinforcement-learning-with-verifiable-rewards','group-relative-policy-optimization'],'sources':[{'id':'pmlr-outcome-reward-model-2025','type':'primary','publisher':'PMLR','title':'Free Process Rewards without Process Labels','published':'2025','url':'https://proceedings.mlr.press/v267/yuan25c.html','supports':['definition','usage','technical-definition']}]},
{'term':'Metadata Filtering','slug':'metadata-filtering','pronunciation':'MET-uh-day-tuh FIL-ter-ing','definition':'A retrieval technique that restricts search results using structured metadata conditions, such as category, date, tenant, source, or document type, before or alongside relevance ranking.','example':'Metadata filtering limited the vector search to documents from the legal department before semantic similarity was applied.','categories':['AI Systems & Technical Concepts'],'aliases':['Metadata filter','Vector metadata filtering'],'status':'Established retrieval technique','partOfSpeech':'noun','related':['retrieval-pipeline','vector-search','vector-database'],'sources':[{'id':'pinecone-metadata-filtering-2026','type':'primary','publisher':'Pinecone','title':'Filter by metadata','published':'2026','url':'https://docs.pinecone.io/guides/search/filter-by-metadata','supports':['definition','usage','technical-definition']}]},
{'term':'Query Rewriting','slug':'query-rewriting','pronunciation':'KWEER-ee ree-RY-ting','definition':'The practice of reformulating a user or search query into a version intended to improve retrieval quality, specificity, coverage, or compatibility with the search system.','example':'The RAG pipeline used query rewriting to turn a vague user question into a more specific search query before retrieval.','categories':['AI Systems & Technical Concepts','AI Ways of Working'],'aliases':['Query reformulation'],'status':'Established retrieval technique','partOfSpeech':'noun','related':['retrieval-pipeline','query-routing','rag'],'sources':[{'id':'elastic-rag-query-rewriting-2026','type':'primary','publisher':'Elastic','title':'RAG','published':'2026','url':'https://www.elastic.co/docs/solutions/search/rag','supports':['definition','usage','technical-definition']}]},
{'term':'Automated Evaluation','slug':'automated-evaluation','pronunciation':'AW-tuh-may-ted ih-val-yoo-AY-shun','definition':'Evaluation in which software, rules, metrics, or AI-based graders automatically score or judge model outputs or system behavior without requiring a human reviewer for every case.','example':'The team used automated evaluation to score thousands of model responses before sending a smaller sample to expert reviewers.','categories':['AI Ways of Working','AI Systems & Technical Concepts'],'aliases':['Automated eval','Automatic evaluation'],'status':'Established evaluation method','partOfSpeech':'noun','related':['eval','evals-framework','llm-as-a-judge'],'sources':[{'id':'openai-gdpval-automated-grader-2025','type':'primary','publisher':'OpenAI','title':'Measuring the performance of our models on real-world tasks','published':'2025','url':'https://openai.com/index/gdpval/','supports':['definition','usage','evaluation']},{'id':'openai-evals-business-2025','type':'primary','publisher':'OpenAI','title':'How evals drive the next chapter in AI for businesses','published':'2025-11-19','url':'https://openai.com/index/evals-drive-next-chapter-of-ai/','supports':['usage','evaluation']}]},
{'term':'Rubric','slug':'rubric','pronunciation':'ROO-brik','definition':'A set of explicit criteria used to judge or score model outputs, often defining what a successful response should include, avoid, or accomplish and sometimes assigning weights or points to each criterion.','example':'The evaluation rubric awarded points for factual accuracy, completeness, and appropriate uncertainty while penalizing unsupported claims.','categories':['AI Ways of Working','AI Systems & Technical Concepts'],'aliases':['Evaluation rubric','Scoring rubric'],'status':'Established evaluation term','partOfSpeech':'noun','related':['eval','automated-evaluation','human-evaluation'],'sources':[{'id':'openai-healthbench-rubric-2025','type':'primary','publisher':'OpenAI','title':'Introducing HealthBench','published':'2025','url':'https://openai.com/index/healthbench/','supports':['definition','usage','evaluation']},{'id':'openai-evals-rubric-2025','type':'primary','publisher':'OpenAI','title':'How evals drive the next chapter in AI for businesses','published':'2025-11-19','url':'https://openai.com/index/evals-drive-next-chapter-of-ai/','supports':['usage','evaluation']}]},
{'term':'Algorithmic Audit','slug':'algorithmic-audit','pronunciation':'al-guh-RITH-mik AW-dit','definition':'An independent or structured examination of an algorithmic or AI system, or the processes around it, to assess behavior, compliance, risks, impacts, accountability, or whether the system operates as claimed.','example':'The agency commissioned an algorithmic audit to examine the system’s outputs, governance controls, and effects after deployment.','categories':['AI Risks, Safety & Governance'],'aliases':['Algorithm audit','Algorithmic auditing'],'status':'Established accountability practice','partOfSpeech':'noun','related':['ai-audit','algorithmic-accountability','ai-governance'],'sources':[{'id':'oecd-algorithmic-audits-2025','type':'primary','publisher':'OECD','title':'Enablers, guardrails and engagement for unlocking trustworthy AI','published':'2025','url':'https://www.oecd.org/en/publications/governing-with-artificial-intelligence_795de142-en/full-report/enablers-guardrails-and-engagement-for-unlocking-trustworthy-ai_2f817983.html','supports':['definition','usage','governance']}]},
{'term':'AI Regulation','slug':'ai-regulation','pronunciation':'A-I reg-yuh-LAY-shun','definition':'Binding legal or regulatory rules that govern the development, deployment, use, oversight, or effects of artificial intelligence systems within a jurisdiction or sector.','example':'The company reviewed new AI regulation to determine which transparency and risk-management obligations applied to its products.','categories':['AI Risks, Safety & Governance'],'aliases':['Artificial intelligence regulation'],'status':'Established governance term','partOfSpeech':'noun','related':['ai-policy','ai-act','ai-governance'],'sources':[{'id':'oecd-ai-regulation-2025','type':'primary','publisher':'OECD','title':'Enablers, guardrails and engagement for unlocking trustworthy AI','published':'2025','url':'https://www.oecd.org/en/publications/governing-with-artificial-intelligence_795de142-en/full-report/enablers-guardrails-and-engagement-for-unlocking-trustworthy-ai_2f817983.html','supports':['definition','usage','governance']},{'id':'oecd-regulatory-outlook-ai-2025','type':'primary','publisher':'OECD','title':'Regulating for the future','published':'2025','url':'https://www.oecd.org/en/publications/oecd-regulatory-policy-outlook-2025_56b60e39-en/full-report/regulating-for-the-future_e948d334.html','supports':['usage','governance']}]}
]
def page(t):
 u=f'{BASE}/terms/{t["slug"]}/'; n=escape(t['term']); d=escape(t['definition'],quote=True); p=escape(t['pronunciation']); ld=json.dumps({'@context':'https://schema.org','@type':'DefinedTerm','name':t['term'],'description':t['definition'],'url':u,'inDefinedTermSet':BASE+'/','inLanguage':'en'},ensure_ascii=False)
 return f'<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{n} | EpochLex</title><meta name="description" content="{d}"><link rel="canonical" href="{u}"><script type="application/ld+json">{ld}</script><link rel="stylesheet" href="../../assets/css/styles.css"><link rel="stylesheet" href="../../assets/css/term-pages.css"><link rel="stylesheet" href="../../assets/css/brand-theme.css"></head><body><main id="term-page" class="term-page shell" data-term-slug="{t["slug"]}"><div id="term-fallback" class="term-fallback"><nav class="term-breadcrumb"><a href="../../">Browse</a><span>/</span><span>{n}</span></nav><p class="eyebrow">EpochLex entry</p><h1>{n}</h1><p class="fallback-pronunciation">{p}</p><p class="fallback-definition">{escape(t["definition"])}</p></div></main><script src="../../assets/js/app.js"></script><script src="../../assets/js/term-page.js"></script></body></html>\n'
tp=R/'data/terms.json'; terms=json.loads(tp.read_text()); existing={x['slug'] for x in terms}
for b in B:
 if b['slug'] in existing: raise SystemExit('already published: '+b['slug'])
 rec={k:v for k,v in b.items() if k not in ('related','sources')}; rec.update({'added':D,'lastReviewed':D,'sources':[]}); terms.append(rec)
for t in terms:
 if t['slug']=='ai-audit':
  aliases=t.setdefault('aliases',[])
  if 'AI Auditing' not in aliases: aliases.append('AI Auditing')
terms.sort(key=lambda x:x['term'].lower()); tp.write_text(json.dumps(terms,ensure_ascii=False,separators=(',',':'))+'\n')
pp=R/'data/provenance.json'; prov=json.loads(pp.read_text())
for b in B: prov[b['slug']]={'researchStatus':'pending','origin':None,'firstKnownUse':None,'history':[],'relatedTerms':b['related'],'sources':b['sources']}
pp.write_text(json.dumps(prov,ensure_ascii=False,indent=2)+'\n')
for b in B:
 p=R/'terms'/b['slug']; p.mkdir(parents=True,exist_ok=True); (p/'index.html').write_text(page(b))
cp=R/'docs/CORPUS-CANDIDATES.md'; text=cp.read_text()
for label in [b['term'] for b in B]+['AI Auditing']:
 text=re.sub(r'^- '+re.escape(label)+r'\s*$','',text,flags=re.M)
text=re.sub(r'\n{3,}','\n\n',text); st=text.index('## Repository roadmap candidates'); en=text.index('## Related documentation'); count=sum(1 for line in text[st:en].splitlines() if line.startswith('- ')); text=re.sub(r'\*\*Current unpublished inventory: \d+ candidates\.\*\*',f'**Current unpublished inventory: {count} candidates.**',text,count=1); cp.write_text(text)
ap=R/'docs/CORPUS-AUDIT-2026-09.md'; a=ap.read_text(); sec='\n## Research Further promotion pass 16 — Batch T (published September 8, 2026)\n\nThis batch is the sixteenth evidence-based promotion from **Research Further**. Promotion records an audit decision for these entries; it does not create a permanent lifecycle state or automatic promotion rule.\n\n'
for b in B:
 src='; '.join(f"[{s['publisher']}: {s['title']}]({s['url']})" for s in b['sources']); sec+=f"### {b['term']}\n\n**Why promote and publish:** {b['definition']}\n\n**Usage evidence:** {src}\n\n**Provenance state:** `pending` — meaning/usage evidence is recorded; origin, first-known-use, and fuller history research remain open.\n\n"
sec+='### Alias disposition: AI Auditing\n\n**Disposition:** Represent as an alias of the published **AI Audit** entry rather than as a separate page. The gerund form does not provide distinct reader value beyond the existing audit concept.\n\n'
a=a.replace('## Research Further',sec+'## Research Further',1); a=re.sub(r'This audit has now published \d+ candidates across Batches A–S and added 172 new research candidates\.', 'This audit has now published 193 candidates across Batches A–T and added 172 new research candidates.', a); ap.write_text(re.sub(r'\n{3,}','\n\n',a))
rp=R/'docs/ROADMAP.md'; r=rp.read_text().replace('- 305 published dictionary entries;','- 315 published dictionary entries;').replace('- 122 researched provenance records and 183 pending provenance records in the current published corpus;','- 122 researched provenance records and 193 pending provenance records in the current published corpus;'); rp.write_text(r)
sp=R/'sitemap.xml'; sm=sp.read_text(); blocks=''.join(f'  <url>\n    <loc>{BASE}/terms/{b["slug"]}/</loc>\n    <lastmod>{D}</lastmod>\n  </url>\n' for b in B); sp.write_text(sm.replace('</urlset>',blocks+'</urlset>'))
terms=json.loads(tp.read_text()); prov=json.loads(pp.read_text()); slugs={x['slug'] for x in terms}
assert len(terms)==315, len(terms); assert slugs==set(prov); assert sum(x.get('researchStatus')=='pending' for x in prov.values())==193
assert count==555, count
assert any(t['slug']=='ai-audit' and 'AI Auditing' in t.get('aliases',[]) for t in terms)
for b in B: assert (R/'terms'/b['slug']/'index.html').exists()
for slug,p in prov.items():
 for rel in p.get('relatedTerms',[]): assert rel in slugs,(slug,rel)
print('Validated Batch T: 315 published, 193 pending, 555 candidates; AI Auditing represented as alias.')
