#!/usr/bin/env python3
import json
from pathlib import Path
R=Path(__file__).resolve().parents[1]
RECORDS={
'model-serving':{'researchStatus':'researched','origin':'Model serving is a deployment practice rather than a term with a single established inventor. It refers to making a trained model available to applications through a runtime, server, endpoint, or similar serving layer that loads the model and handles inference requests. Modern serving systems add concerns such as scaling, routing, batching, health checks, versioning, and hardware-aware execution.','firstKnownUse':None,'history':[],'sources':[{'id':'kserve-framework-overview','type':'primary','publisher':'KServe','title':'Model Serving Frameworks Overview','published':None,'url':'https://kserve.github.io/website/docs/next/model-serving/predictive-inference/frameworks/overview','supports':['definition','usage','technical-definition']},{'id':'kserve-servingruntime','type':'primary','publisher':'KServe','title':'Serving Runtime','published':None,'url':'https://kserve.github.io/website/docs/concepts/resources/servingruntime','supports':['definition','usage','technical-definition']}]},
'top-p':{'researchStatus':'researched','origin':'Top-p sampling is the common implementation label for nucleus sampling, a decoding method introduced by Ari Holtzman, Jan Buys, Li Du, Maxwell Forbes, and Yejin Choi in 2019. Nucleus sampling restricts sampling to the smallest set of tokens whose cumulative probability mass reaches a threshold p, then samples from that dynamically sized set. The current evidence establishes the 2019 method introduction but does not prove that the exact phrase “top-p” was coined in that paper.','firstKnownUse':None,'history':[{'date':'2019-04-22','event':'Holtzman and colleagues submitted “The Curious Case of Neural Text Degeneration,” introducing nucleus sampling as a dynamic probability-mass truncation method for neural text generation.'}],'sources':[{'id':'holtzman-nucleus-2019','type':'primary','publisher':'arXiv','title':'The Curious Case of Neural Text Degeneration','published':'2019-04-22','url':'https://arxiv.org/abs/1904.09751','supports':['definition','history','technical-definition','usage']}]},
'bm25':{'researchStatus':'researched','origin':'BM25 emerged from the Okapi probabilistic information-retrieval work led by Stephen Robertson and colleagues. A 1994 TREC-3 paper from the Okapi team documented the weighting family in active retrieval experiments, and later reviews describe BM25 as a major result of the probabilistic relevance framework. EpochLex treats the 1994 TREC work as an early documented milestone rather than claiming it was the first mathematical appearance of every component of the formula.','firstKnownUse':None,'history':[{'date':'1994','event':'The Okapi team reported refined probabilistic term-weighting functions at TREC-3, part of the line of work that became known as BM25.'},{'date':'2009-09-17','event':'Robertson and Zaragoza published a major review of the probabilistic relevance framework and BM25.'}],'sources':[{'id':'okapi-trec3-1994','type':'primary','publisher':'National Institute of Standards and Technology','title':'Okapi at TREC-3','published':'1994','url':'https://pages.nist.gov/trec-browser/trec3/routing/proceedings/','supports':['history','usage']},{'id':'robertson-zaragoza-bm25-2009','type':'secondary','publisher':'Foundations and Trends in Information Retrieval','title':'The Probabilistic Relevance Framework: BM25 and Beyond','published':'2009-09-17','url':'https://doi.org/10.1561/1500000019','supports':['definition','history','technical-definition']}]},
'hnsw':{'researchStatus':'researched','origin':'Hierarchical Navigable Small World (HNSW) graphs were introduced by Yu. A. Malkov and D. A. Yashunin in 2016 as a graph-based method for approximate nearest-neighbor search. The method adds a hierarchy of proximity-graph layers so search can begin at coarse levels and progressively descend toward closer neighbors.','firstKnownUse':{'date':'2016-03-30','precision':'day','note':'Malkov and Yashunin submitted the HNSW paper to arXiv on March 30, 2016.'},'history':[{'date':'2016-03-30','event':'Malkov and Yashunin submitted “Efficient and robust approximate nearest neighbor search using Hierarchical Navigable Small World graphs,” introducing HNSW.'}],'sources':[{'id':'malkov-yashunin-hnsw-2016','type':'primary','publisher':'arXiv','title':'Efficient and robust approximate nearest neighbor search using Hierarchical Navigable Small World graphs','published':'2016-03-30','url':'https://arxiv.org/abs/1603.09320','supports':['origin','firstKnownUse','definition','history','technical-definition']}]},
'dense-retrieval':{'researchStatus':'researched','origin':'Dense retrieval refers to retrieval based on dense learned vector representations rather than sparse term-weight vectors. The idea developed across representation-learning and neural information-retrieval research, so EpochLex does not assign the general term to one inventor. A major modern milestone was Dense Passage Retrieval (DPR) in 2020, which showed that learned dense question and passage representations could outperform a strong BM25 baseline for open-domain question answering.','firstKnownUse':None,'history':[{'date':'2020-04-10','event':'Karpukhin and colleagues submitted the Dense Passage Retrieval paper, demonstrating strong open-domain passage retrieval using learned dense representations and a dual-encoder architecture.'}],'sources':[{'id':'dpr-2020','type':'primary','publisher':'arXiv','title':'Dense Passage Retrieval for Open-Domain Question Answering','published':'2020-04-10','url':'https://arxiv.org/abs/2004.04906','supports':['definition','history','usage','technical-definition']}]},
'sparse-retrieval':{'researchStatus':'researched','origin':'Sparse retrieval is an information-retrieval family in which queries and documents are represented with sparse features, traditionally lexical terms or weighted term dimensions. It predates modern neural retrieval and includes methods such as TF-IDF and BM25. Modern systems may also use learned sparse representations, but the shared property is that most dimensions remain zero and matching is performed over sparse signals. The current research pass does not establish a single origin for the umbrella term.','firstKnownUse':None,'history':[],'sources':[{'id':'dpr-sparse-baseline-2020','type':'primary','publisher':'arXiv','title':'Dense Passage Retrieval for Open-Domain Question Answering','published':'2020-04-10','url':'https://arxiv.org/abs/2004.04906','supports':['definition','usage','contrast']},{'id':'robertson-zaragoza-bm25-2009','type':'secondary','publisher':'Foundations and Trends in Information Retrieval','title':'The Probabilistic Relevance Framework: BM25 and Beyond','published':'2009-09-17','url':'https://doi.org/10.1561/1500000019','supports':['history','usage','technical-definition']}]},
'cross-encoder':{'researchStatus':'researched','origin':'Cross-encoder is a model-architecture label used for systems that process a pair of inputs jointly and produce a score or classification for that pair. In retrieval, cross-encoders commonly score a query and candidate document together, usually with higher relevance quality but greater computational cost than independently encoded embeddings. The current research pass does not establish a single coinage for the term.','firstKnownUse':None,'history':[],'sources':[{'id':'sentence-transformers-cross-encoder','type':'primary','publisher':'Sentence Transformers','title':'Cross-Encoders','published':None,'url':'https://www.sbert.net/examples/cross_encoder/applications/README.html','supports':['definition','usage','technical-definition','contrast']},{'id':'sentence-transformers-cross-usage','type':'primary','publisher':'Sentence Transformers','title':'Cross Encoder Usage','published':None,'url':'https://www.sbert.net/docs/cross_encoder/usage/usage.html','supports':['definition','usage']}]},
'bi-encoder':{'researchStatus':'researched','origin':'Bi-encoder is a model-architecture label for systems that encode two inputs independently into vector representations that can be compared efficiently. The pattern is widely used in semantic search and first-stage retrieval because document embeddings can be precomputed and reused. The current research pass does not establish a single inventor or first use of the term.','firstKnownUse':None,'history':[],'sources':[{'id':'sentence-transformers-bi-encoder','type':'primary','publisher':'Sentence Transformers','title':'Quickstart','published':None,'url':'https://sbert.net/docs/quickstart.html','supports':['definition','usage','technical-definition','contrast']},{'id':'dpr-2020','type':'primary','publisher':'arXiv','title':'Dense Passage Retrieval for Open-Domain Question Answering','published':'2020-04-10','url':'https://arxiv.org/abs/2004.04906','supports':['history','usage','technical-definition']}]},
'reranker':{'researchStatus':'researched','origin':'Reranking is a long-established search and recommendation pattern rather than a modern generative-AI coinage. A reranker takes an initial candidate set and applies a second scoring stage to reorder those candidates, often using a more expensive model than the first-stage retriever. In modern semantic search, cross-encoders are a common reranking architecture.','firstKnownUse':None,'history':[],'sources':[{'id':'sentence-transformers-cross-usage','type':'primary','publisher':'Sentence Transformers','title':'Cross Encoder Usage','published':None,'url':'https://www.sbert.net/docs/cross_encoder/usage/usage.html','supports':['definition','usage','technical-definition']},{'id':'sentence-transformers-retrieve-rerank','type':'primary','publisher':'Sentence Transformers','title':'Cross-Encoder vs. Bi-Encoder','published':None,'url':'https://www.sbert.net/examples/cross_encoder/applications/README.html','supports':['definition','usage','contrast']}]},
'retrieval-pipeline':{'researchStatus':'researched','origin':'Retrieval pipeline is a descriptive systems term rather than a concept with a single established coinage. It refers to an ordered sequence of retrieval and ranking stages used to turn a query into a candidate or ranked result set. Modern pipelines may combine lexical search, vector retrieval, filtering, fusion, and reranking.','firstKnownUse':None,'history':[],'sources':[{'id':'elastic-retrievers-overview','type':'primary','publisher':'Elastic','title':'Retrievers','published':None,'url':'https://www.elastic.co/docs/solutions/search/retrievers-overview','supports':['definition','usage','technical-definition']},{'id':'sentence-transformers-cross-usage','type':'primary','publisher':'Sentence Transformers','title':'Cross Encoder Usage','published':None,'url':'https://www.sbert.net/docs/cross_encoder/usage/usage.html','supports':['usage','technical-definition']}]}
}
pp=R/'data/provenance.json'; prov=json.loads(pp.read_text())
for slug,record in RECORDS.items():
    assert slug in prov, slug
    assert prov[slug].get('researchStatus')=='pending',(slug,prov[slug].get('researchStatus'))
    record['relatedTerms']=prov[slug].get('relatedTerms',[])
    prov[slug]=record
pp.write_text(json.dumps(prov,indent=2,ensure_ascii=False)+'\n')
terms=json.loads((R/'data/terms.json').read_text()); published={t['slug'] for t in terms}
assert len(terms)==365 and set(prov)==published
for s,p in prov.items():
    for rel in p.get('relatedTerms',[]): assert rel in published,(s,rel)
researched=sum(p.get('researchStatus')=='researched' for p in prov.values()); pending=sum(p.get('researchStatus')=='pending' for p in prov.values())
assert researched==162 and pending==203,(researched,pending)
for s in RECORDS:
    assert prov[s]['sources'] and all(src.get('supports') for src in prov[s]['sources'])
rp=R/'docs/ROADMAP.md'; road=rp.read_text().replace('152 researched provenance records and 213 pending provenance records','162 researched provenance records and 203 pending provenance records'); rp.write_text(road)
qp=R/'docs/PROVENANCE-REVIEW-QUEUE-2026-09.md'; q=qp.read_text()
q=q.replace('including **152 researched** provenance records and **213 pending** records after provenance Batch 03.','including **162 researched** provenance records and **203 pending** records after provenance Batch 04.')
q=q.replace('Provenance Batches 01–03 completed 30 of the 61 Wave 1 records, leaving **31 Wave 1 reviews** to reach that milestone.','Provenance Batches 01–04 completed 40 of the 61 Wave 1 records, leaving **21 Wave 1 reviews** to reach that milestone.')
marker='## Wave 1 — Majority milestone (61)'
section='''## Provenance Batch 04 — completed September 8, 2026\n\nThis batch concentrated on model serving and retrieval architecture. All ten records completed the initial human-reviewed provenance pass and now use `researchStatus: "researched"`.\n\n1. **Model Serving**\n2. **Top-p**\n3. **BM25**\n4. **HNSW**\n5. **Dense Retrieval**\n6. **Sparse Retrieval**\n7. **Cross-Encoder**\n8. **Bi-Encoder**\n9. **Reranker**\n10. **Retrieval Pipeline**\n\n'''
assert marker in q; qp.write_text(q.replace(marker,section+marker,1))
print(json.dumps({'published':365,'researched':researched,'pending':pending,'batch':list(RECORDS)},indent=2))
