#!/usr/bin/env python3
import json,re
from pathlib import Path
from html import escape
R=Path(__file__).resolve().parents[1]; D='2026-09-08'; BASE='https://epochlex.justathoughtblog.org'
B=[
{'term':'Query Expansion','slug':'query-expansion','pronunciation':'KWEER-ee ek-SPAN-shun','definition':'A retrieval technique that broadens or reformulates a search request into additional query terms or query variants so the system can retrieve a wider set of potentially relevant results.','example':'The RAG pipeline used query expansion to search several variations of the user’s wording before ranking the combined results.','categories':['AI Systems & Technical Concepts'],'aliases':['Search query expansion'],'status':'Established retrieval technique','partOfSpeech':'noun','related':['query-rewriting','multi-query-retrieval','retrieval-pipeline'],'sources':[{'id':'microsoft-query-expansion-2026','type':'primary','publisher':'Microsoft Learn','title':'Improve RAG chain quality','published':'2026','url':'https://learn.microsoft.com/en-us/azure/databricks/agents/tutorials/ai-cookbook/quality-rag-chain','supports':['definition','usage','technical-definition']}]},
{'term':'Multi-Hop Retrieval','slug':'multi-hop-retrieval','pronunciation':'MUL-tee HOP ree-TREE-vul','definition':'A retrieval approach that gathers evidence across multiple dependent retrieval steps when answering a question requires information that is distributed across different sources or intermediate facts.','example':'The research workflow used multi-hop retrieval to find a company acquisition first and then retrieve the acquired company’s earlier product history.','categories':['AI Systems & Technical Concepts'],'aliases':['Multi-hop search'],'status':'Established retrieval pattern','partOfSpeech':'noun','related':['retrieval-pipeline','multi-query-retrieval','query-expansion'],'sources':[{'id':'microsoft-rag-decomposition-2026','type':'primary','publisher':'Microsoft Learn','title':'Develop a RAG Solution on Azure - Information-Retrieval Phase','published':'2026','url':'https://learn.microsoft.com/azure/architecture/ai-ml/guide/rag/rag-information-retrieval','supports':['definition','usage','technical-definition']},{'id':'microsoft-agentic-retrieval-2026','type':'primary','publisher':'Microsoft Learn','title':'Quickstart: Agentic Retrieval','published':'2026','url':'https://learn.microsoft.com/en-us/azure/search/search-get-started-agentic-retrieval?pivots=rest','supports':['usage','technical-definition']}]},
{'term':'Membership Inference','slug':'membership-inference','pronunciation':'MEM-ber-ship IN-fer-ens','definition':'A privacy attack that attempts to determine whether a particular data sample was included in the training set of a machine-learning model.','example':'The privacy review tested whether repeated model queries could reveal whether a specific medical record had been part of the training data.','categories':['AI Risks, Safety & Governance','AI Systems & Technical Concepts'],'aliases':['Membership inference attack'],'status':'Established privacy attack','partOfSpeech':'noun','related':['model-inversion','ai-security','training-data'],'sources':[{'id':'nist-membership-inference-2026','type':'primary','publisher':'NIST CSRC','title':'membership-inference attack - Glossary','published':'2026','url':'https://csrc.nist.gov/glossary/term/membership_inference_attack','supports':['definition','technical-definition','security']}]},
{'term':'Agent Session','slug':'agent-session','pronunciation':'AY-jent SESH-un','definition':'A conversation-scoped state container used by an AI agent to preserve information such as message history, memory references, service conversation identifiers, or other state across multiple runs.','example':'The application restored the agent session so the assistant could continue the same conversation after the process restarted.','categories':['AI Systems & Technical Concepts'],'aliases':['AI agent session'],'status':'Established agent-framework term','partOfSpeech':'noun','related':['agent-state','agent-memory','agent-runtime'],'sources':[{'id':'microsoft-agent-session-2026','type':'primary','publisher':'Microsoft Learn','title':'Conversations & Memory overview in Agent Framework','published':'2026-08-25','url':'https://learn.microsoft.com/en-us/agent-framework/agents/conversations/','supports':['definition','usage','technical-definition']},{'id':'microsoft-agent-session-api-2026','type':'primary','publisher':'Microsoft Learn','title':'AgentSession Class','published':'2026','url':'https://learn.microsoft.com/en-us/dotnet/api/microsoft.agents.ai.agentsession?view=agent-framework-dotnet-latest','supports':['technical-definition']}]},
{'term':'Persistent Memory','slug':'persistent-memory','pronunciation':'per-SIS-tent MEM-uh-ree','definition':'Agent memory stored durably so information can be recalled across separate sessions, process restarts, or later interactions rather than existing only in the current context window.','example':'Persistent memory let the travel assistant remember the user’s seating preference in a new session days later.','categories':['AI Systems & Technical Concepts'],'aliases':['Persistent agent memory'],'status':'Established agent-memory pattern','partOfSpeech':'noun','related':['agent-memory','agent-session','semantic-memory'],'sources':[{'id':'microsoft-persistent-memory-neo4j-2026','type':'primary','publisher':'Microsoft Learn','title':'Neo4j','published':'2026','url':'https://learn.microsoft.com/en-us/agent-framework/integrations/neo4j-memory','supports':['definition','usage','technical-definition']},{'id':'microsoft-persistent-memory-foundry-2026','type':'primary','publisher':'Microsoft Learn','title':'Quickstart: Give a hosted agent persistent memory','published':'2026-08-05','url':'https://learn.microsoft.com/en-us/azure/foundry/agents/quickstarts/quickstart-memory-hosted-agent','supports':['usage','technical-definition']}]},
{'term':'Semantic Memory','slug':'semantic-memory','pronunciation':'suh-MAN-tik MEM-uh-ree','definition':'Long-term agent memory that stores facts, concepts, preferences, or other knowledge in a form that can be retrieved later by semantic relevance rather than only by exact conversational position.','example':'The assistant used semantic memory to recall that the user prefers vegetarian restaurants even though the preference was mentioned in a different session.','categories':['AI Systems & Technical Concepts'],'aliases':['Semantic agent memory'],'status':'Established agent-memory term','partOfSpeech':'noun','related':['agent-memory','persistent-memory','vector-database'],'sources':[{'id':'microsoft-semantic-memory-cosmos-2026','type':'primary','publisher':'Microsoft Learn','title':'Azure Cosmos DB','published':'2026-08-25','url':'https://learn.microsoft.com/en-us/agent-framework/integrations/by-component/context-providers/azure-cosmos','supports':['definition','usage','technical-definition']},{'id':'microsoft-semantic-memory-foundry-2026','type':'primary','publisher':'Microsoft Learn','title':'Quickstart: Give a hosted agent persistent memory','published':'2026-08-05','url':'https://learn.microsoft.com/en-us/azure/foundry/agents/quickstarts/quickstart-memory-hosted-agent','supports':['usage','technical-definition']}]},
{'term':'Capability Benchmark','slug':'capability-benchmark','pronunciation':'kay-puh-BIL-uh-tee BENCH-mark','definition':'A benchmark used to measure a model’s performance on general or domain-specific capabilities so changes in useful ability can be compared across models, training methods, or safety interventions.','example':'The alignment study used capability benchmarks to verify that the safety intervention did not materially reduce general model performance.','categories':['AI Systems & Technical Concepts','AI Ways of Working'],'aliases':['Capabilities benchmark'],'status':'Established evaluation term','partOfSpeech':'noun','related':['capability-evaluation','safety-benchmark','eval'],'sources':[{'id':'anthropic-capability-benchmark-2026','type':'research','publisher':'Anthropic','title':'Automated Researchers Can Mitigate Well-Characterized Alignment Failures','published':'2026','url':'https://alignment.anthropic.com/2026/automated-alignment-researchers/','supports':['definition','usage','evaluation']},{'id':'anthropic-a3-capability-benchmark-2026','type':'research','publisher':'Anthropic','title':'A3: An Automated Alignment Agent for Safety Finetuning','published':'2026','url':'https://alignment.anthropic.com/2026/automated-alignment-agent/','supports':['usage','evaluation']}]},
{'term':'Multimodal Benchmark','slug':'multimodal-benchmark','pronunciation':'mul-tee-MOH-dul BENCH-mark','definition':'A benchmark that evaluates a model or AI system on tasks requiring understanding, reasoning, generation, or interaction across more than one modality, such as text and images.','example':'The model’s multimodal benchmark combined images with technical questions to test whether visual evidence improved troubleshooting accuracy.','categories':['AI Systems & Technical Concepts'],'aliases':['Multimodal evaluation benchmark'],'status':'Established evaluation term','partOfSpeech':'noun','related':['multimodal-model','capability-benchmark','eval'],'sources':[{'id':'openai-multimodal-benchmark-2026','type':'primary','publisher':'OpenAI','title':'GPT-5.5 System Card','published':'2026-04-23','url':'https://deploymentsafety.openai.com/gpt-5-5','supports':['definition','usage','evaluation']},{'id':'openai-multimodal-eval-2025','type':'primary','publisher':'OpenAI','title':'GPT-5 System Card','published':'2025','url':'https://deploymentsafety.openai.com/gpt-5','supports':['usage','evaluation']}]},
{'term':'AI Red Team','slug':'ai-red-team','pronunciation':'A-I RED teem','definition':'A group of internal or external testers who adversarially probe an AI model or system to uncover harmful capabilities, misuse pathways, security weaknesses, or failures in safeguards.','example':'The AI red team tested the agent for jailbreaks, prompt injection, unsafe tool use, and other failure modes before release.','categories':['AI Risks, Safety & Governance','AI Ways of Working'],'aliases':['AI red-team','AI red teamers'],'status':'Established AI safety practice role','partOfSpeech':'noun','related':['red-teaming','ai-security-testing','safety-evaluation'],'sources':[{'id':'openai-red-team-2024','type':'primary','publisher':'OpenAI','title':'Response to NIST Executive Order on AI','published':'2024','url':'https://openai.com/global-affairs/response-to-nist-executive-order-on-ai/','supports':['definition','usage','governance']},{'id':'openai-gpt55-red-team-2026','type':'primary','publisher':'OpenAI','title':'GPT-5.5 System Card','published':'2026-04-23','url':'https://openai.com/index/gpt-5-5-system-card/','supports':['usage','evaluation']}]},
{'term':'Backdoor Attack','slug':'backdoor-attack','pronunciation':'BACK-door uh-TAK','definition':'An adversarial machine-learning attack that implants or exploits a hidden trigger so a model behaves normally on ordinary inputs but produces attacker-chosen behavior when the trigger is present.','example':'The poisoned training examples created a backdoor attack that caused the classifier to mislabel images containing a particular visual trigger.','categories':['AI Risks, Safety & Governance','AI Systems & Technical Concepts'],'aliases':['Model Backdoor','Model backdoor attack','Trojan attack','Trapdoor attack'],'status':'Established adversarial-ML security term','partOfSpeech':'noun','related':['data-poisoning','ai-security','model-inversion'],'sources':[{'id':'nist-backdoor-attack-2024','type':'primary','publisher':'NIST','title':'Adversarial Machine Learning: A Taxonomy and Terminology of Attacks and Mitigations','published':'2024','url':'https://www.nist.gov/publications/adversarial-machine-learning-taxonomy-and-terminology-attacks-and-mitigations','supports':['definition','usage','technical-definition','security']},{'id':'nist-trojai-backdoor','type':'primary','publisher':'NIST','title':'What Is TrojAI','published':'2024','url':'https://pages.nist.gov/trojai/docs/about.html','supports':['usage','technical-definition']}]}
]
def page(t):
 u=f'{BASE}/terms/{t["slug"]}/'; n=escape(t['term']); d=escape(t['definition'],quote=True); p=escape(t['pronunciation']); ld=json.dumps({'@context':'https://schema.org','@type':'DefinedTerm','name':t['term'],'description':t['definition'],'url':u,'inDefinedTermSet':BASE+'/','inLanguage':'en'},ensure_ascii=False)
 return f'<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{n} | EpochLex</title><meta name="description" content="{d}"><link rel="canonical" href="{u}"><script type="application/ld+json">{ld}</script><link rel="stylesheet" href="../../assets/css/styles.css"><link rel="stylesheet" href="../../assets/css/term-pages.css"><link rel="stylesheet" href="../../assets/css/brand-theme.css"></head><body><main id="term-page" class="term-page shell" data-term-slug="{t["slug"]}"><div id="term-fallback" class="term-fallback"><nav class="term-breadcrumb"><a href="../../">Browse</a><span>/</span><span>{n}</span></nav><p class="eyebrow">EpochLex entry</p><h1>{n}</h1><p class="fallback-pronunciation">{p}</p><p class="fallback-definition">{escape(t["definition"])}</p></div></main><script src="../../assets/js/app.js"></script><script src="../../assets/js/term-page.js"></script></body></html>\n'
tp=R/'data/terms.json'; terms=json.loads(tp.read_text()); existing={x['slug'] for x in terms}
for b in B:
 if b['slug'] in existing: raise SystemExit('already published: '+b['slug'])
 rec={k:v for k,v in b.items() if k not in ('related','sources')}; rec.update({'added':D,'lastReviewed':D,'sources':[]}); terms.append(rec)
terms.sort(key=lambda x:x['term'].lower()); tp.write_text(json.dumps(terms,ensure_ascii=False,separators=(',',':'))+'\n')
pp=R/'data/provenance.json'; prov=json.loads(pp.read_text())
for b in B: prov[b['slug']]={'researchStatus':'pending','origin':None,'firstKnownUse':None,'history':[],'relatedTerms':b['related'],'sources':b['sources']}
pp.write_text(json.dumps(prov,ensure_ascii=False,indent=2)+'\n')
for b in B:
 p=R/'terms'/b['slug']; p.mkdir(parents=True,exist_ok=True); (p/'index.html').write_text(page(b))
cp=R/'docs/CORPUS-CANDIDATES.md'; text=cp.read_text()
for label in [b['term'] for b in B]+['Model Backdoor']:
 text=re.sub(r'^- '+re.escape(label)+r'\s*$','',text,flags=re.M)
text=re.sub(r'\n{3,}','\n\n',text); st=text.index('## Repository roadmap candidates'); en=text.index('## Related documentation'); count=sum(1 for line in text[st:en].splitlines() if line.startswith('- ')); text=re.sub(r'\*\*Current unpublished inventory: \d+ candidates\.\*\*',f'**Current unpublished inventory: {count} candidates.**',text,count=1); cp.write_text(text)
ap=R/'docs/CORPUS-AUDIT-2026-09.md'; a=ap.read_text(); sec='\n## Research Further promotion pass 19 — Batch W (published September 8, 2026)\n\nThis batch is the nineteenth evidence-based promotion from **Research Further**. Promotion records an audit decision for these entries; it does not create a permanent lifecycle state or automatic promotion rule.\n\n'
for b in B:
 src='; '.join(f"[{s['publisher']}: {s['title']}]({s['url']})" for s in b['sources']); sec+=f"### {b['term']}\n\n**Why promote and publish:** {b['definition']}\n\n**Usage evidence:** {src}\n\n**Provenance state:** `pending` — meaning/usage evidence is recorded; origin, first-known-use, and fuller history research remain open.\n\n"
sec+='### Alias disposition: Model Backdoor\n\n**Disposition:** Represent as an alias of the published **Backdoor Attack** entry rather than as a separate page. Current adversarial-ML terminology treats the model backdoor as the implanted backdoor behavior or mechanism within the broader backdoor-attack concept, and a separate entry would not add enough distinct reader value here.\n\n'
a=a.replace('## Research Further',sec+'## Research Further',1); a=re.sub(r'This audit has now published \d+ candidates across Batches A–V and added 172 new research candidates\.', 'This audit has now published 223 candidates across Batches A–W and added 172 new research candidates.', a); ap.write_text(re.sub(r'\n{3,}','\n\n',a))
rp=R/'docs/ROADMAP.md'; r=rp.read_text().replace('- 335 published dictionary entries;','- 345 published dictionary entries;').replace('- 122 researched provenance records and 213 pending provenance records in the current published corpus;','- 122 researched provenance records and 223 pending provenance records in the current published corpus;'); rp.write_text(r)
sp=R/'sitemap.xml'; sm=sp.read_text(); blocks=''.join(f'  <url>\n    <loc>{BASE}/terms/{b["slug"]}/</loc>\n    <lastmod>{D}</lastmod>\n  </url>\n' for b in B); sp.write_text(sm.replace('</urlset>',blocks+'</urlset>'))
terms=json.loads(tp.read_text()); prov=json.loads(pp.read_text()); slugs={x['slug'] for x in terms}
assert len(terms)==345, len(terms); assert slugs==set(prov); assert sum(x.get('researchStatus')=='pending' for x in prov.values())==223
assert count==522, count
for b in B: assert (R/'terms'/b['slug']/'index.html').exists()
for slug,p in prov.items():
 for rel in p.get('relatedTerms',[]): assert rel in slugs,(slug,rel)
assert 'Model Backdoor' in next(x for x in terms if x['slug']=='backdoor-attack').get('aliases',[])
print('Validated Batch W: 345 published, 223 pending, 522 candidates.')
