#!/usr/bin/env python3
import json
from pathlib import Path
R=Path(__file__).resolve().parents[1]
RECORDS={
'byte-pair-encoding':{'researchStatus':'researched','origin':'Byte Pair Encoding (BPE) was introduced by Philip Gage in 1994 as a general-purpose data-compression algorithm that repeatedly replaces frequent adjacent byte pairs. In NLP, Sennrich, Haddow, and Birch adapted BPE to subword segmentation in 2016, a milestone that helped make BPE-style tokenization widely used in neural language systems.','firstKnownUse':{'date':'1994-02-01','precision':'day','note':'Philip Gage’s 1994 article “A New Algorithm for Data Compression” explicitly names and describes Byte Pair Encoding (BPE).'},'history':[{'date':'1994-02-01','event':'Philip Gage published “A New Algorithm for Data Compression,” describing Byte Pair Encoding (BPE).'}, {'date':'2016','event':'Sennrich, Haddow, and Birch applied BPE to subword segmentation for neural machine translation.'}],'sources':[{'id':'gage-bpe-1994','type':'primary','publisher':'C Users Journal','title':'A New Algorithm for Data Compression','published':'1994-02-01','url':'https://jacobfilipp.com/DrDobbs/articles/CUJ/1994/9402/gage/gage.htm','supports':['origin','firstKnownUse','definition','history']},{'id':'sennrich-bpe-2016','type':'primary','publisher':'Association for Computational Linguistics','title':'Neural Machine Translation of Rare Words with Subword Units','published':'2016','url':'https://aclanthology.org/P16-1162/','supports':['history','usage','technical-definition']}]},
'autoregressive-model':{'researchStatus':'researched','origin':'Autoregressive modeling originated in statistics and time-series analysis long before modern generative AI. In current generative-model usage, an autoregressive model predicts each next element from earlier elements or prior predictions. EpochLex does not assign the general concept to a modern AI coinage.','firstKnownUse':None,'history':[],'sources':[{'id':'google-autoregressive-glossary','type':'reference','publisher':'Google for Developers','title':'Machine Learning Glossary — auto-regressive model','published':None,'url':'https://developers.google.com/machine-learning/glossary/generative','supports':['definition','usage']},{'id':'ibm-autoregressive','type':'reference','publisher':'IBM','title':'What is an autoregressive model?','published':None,'url':'https://www.ibm.com/think/topics/autoregressive-model','supports':['definition','history','usage']}]},
'encoder':{'researchStatus':'researched','origin':'Encoders are a long-standing component pattern in representation learning and sequence models rather than a Transformer-era coinage. In encoder-decoder systems, the encoder transforms input into an internal representation used by downstream components. The 2017 Transformer retained the encoder-decoder pattern while replacing recurrence and convolution with attention.','firstKnownUse':None,'history':[{'date':'2017-06-12','event':'Vaswani and colleagues introduced the Transformer, using stacked attention-based encoder and decoder components.'}],'sources':[{'id':'attention-is-all-you-need','type':'primary','publisher':'Google Research / NeurIPS','title':'Attention Is All You Need','published':'2017-06-12','url':'https://research.google/pubs/attention-is-all-you-need/','supports':['definition','history','usage']}]},
'decoder':{'researchStatus':'researched','origin':'Decoders are a long-standing component pattern in sequence and representation models rather than a Transformer-era coinage. In encoder-decoder systems, the decoder produces outputs using an encoded representation plus any previously generated state or tokens. The 2017 Transformer implemented this role using masked self-attention and encoder-decoder attention.','firstKnownUse':None,'history':[{'date':'2017-06-12','event':'Vaswani and colleagues introduced the Transformer architecture with stacked attention-based decoder layers.'}],'sources':[{'id':'attention-is-all-you-need','type':'primary','publisher':'Google Research / NeurIPS','title':'Attention Is All You Need','published':'2017-06-12','url':'https://research.google/pubs/attention-is-all-you-need/','supports':['definition','history','usage']}]},
'cross-attention':{'researchStatus':'researched','origin':'Cross-attention is the modern label for attention in which queries from one sequence or representation attend to keys and values from another. The 2017 Transformer paper described this mechanism in the decoder as encoder-decoder attention rather than using “cross-attention” as its primary label, so EpochLex does not treat the paper as evidence that the current term itself originated there.','firstKnownUse':None,'history':[{'date':'2017-06-12','event':'The Transformer paper described decoder attention over encoder outputs, the mechanism now commonly described as cross-attention.'}],'sources':[{'id':'attention-is-all-you-need','type':'primary','publisher':'Google Research / NeurIPS','title':'Attention Is All You Need','published':'2017-06-12','url':'https://research.google/pubs/attention-is-all-you-need/','supports':['definition','history','technical-definition']}]},
'softmax':{'researchStatus':'researched','origin':'Softmax is a mathematical normalization function that predates modern AI. In machine learning, it transforms a vector of scores or logits into normalized probabilities whose values sum to one, commonly for multi-class prediction or token selection. The current research pass does not assign the function to a single AI-era origin.','firstKnownUse':None,'history':[],'sources':[{'id':'google-softmax-glossary','type':'reference','publisher':'Google for Developers','title':'Machine Learning Glossary — softmax','published':None,'url':'https://developers.google.com/machine-learning/glossary/fundamentals','supports':['definition','technical-definition','usage']}]},
'logit':{'researchStatus':'researched','origin':'The logit is a statistical concept that predates modern machine learning. In current ML systems, “logits” commonly refers to raw, unnormalized model scores that are often passed through a function such as softmax to obtain probabilities. EpochLex leaves the deeper historical origin unresolved in this pass rather than assigning a precise first use without stronger claim-specific evidence.','firstKnownUse':None,'history':[],'sources':[{'id':'google-logits-glossary','type':'reference','publisher':'Google for Developers','title':'Machine Learning Glossary — logits','published':None,'url':'https://developers.google.com/machine-learning/glossary','supports':['definition','usage','technical-definition']}]},
'perplexity':{'researchStatus':'researched','origin':'Perplexity is an information-theoretic and language-model evaluation concept rather than a recent generative-AI coinage. In language modeling it summarizes how uncertain a model is about observed sequences, with lower perplexity generally indicating that the model assigns higher probability to the evaluated data. The current research pass does not establish a defensible first use of the term in language modeling.','firstKnownUse':None,'history':[],'sources':[{'id':'google-perplexity-glossary','type':'reference','publisher':'Google for Developers','title':'Machine Learning Glossary — perplexity','published':None,'url':'https://developers.google.com/machine-learning/glossary','supports':['definition','usage','technical-definition']}]},
'multimodal-model':{'researchStatus':'researched','origin':'Multimodal modeling developed from work combining multiple forms of data such as text, images, audio, and video rather than from a single established coinage. In current AI usage, a multimodal model accepts, produces, or jointly represents more than one modality. The current evidence does not support assigning the term to one inventor.','firstKnownUse':None,'history':[],'sources':[{'id':'google-multimodal-glossary','type':'reference','publisher':'Google for Developers','title':'Machine Learning Glossary — multimodal model','published':None,'url':'https://developers.google.com/machine-learning/glossary','supports':['definition','usage']}]},
'flashattention':{'researchStatus':'researched','origin':'FlashAttention was introduced by Tri Dao, Daniel Y. Fu, Stefano Ermon, Atri Rudra, and Christopher Ré in 2022 as an IO-aware exact attention algorithm designed to reduce memory traffic between GPU memory levels while preserving exact attention results.','firstKnownUse':{'date':'2022-05-27','precision':'day','note':'The authors submitted the paper “FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness” on May 27, 2022.'},'history':[{'date':'2022-05-27','event':'The FlashAttention paper was submitted, introducing an IO-aware exact attention algorithm using tiling to reduce memory reads and writes.'},{'date':'2022','event':'FlashAttention appeared in NeurIPS 2022 and quickly became a widely adopted optimization for Transformer attention.'}],'sources':[{'id':'flashattention-2022','type':'primary','publisher':'arXiv / NeurIPS','title':'FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness','published':'2022-05-27','url':'https://arxiv.org/abs/2205.14135','supports':['origin','firstKnownUse','definition','history','technical-definition']},{'id':'flashattention-repo','type':'primary','publisher':'Dao-AILab','title':'FlashAttention official implementation','published':None,'url':'https://github.com/Dao-AILab/flash-attention','supports':['usage','history']}]}
}
pp=R/'data/provenance.json'; prov=json.loads(pp.read_text())
for slug,record in RECORDS.items():
    assert slug in prov, slug
    assert prov[slug].get('researchStatus')=='pending',(slug,prov[slug].get('researchStatus'))
    record['relatedTerms']=prov[slug].get('relatedTerms',[])
    prov[slug]=record
pp.write_text(json.dumps(prov,indent=2,ensure_ascii=False)+'\n')
terms=json.loads((R/'data/terms.json').read_text()); published={t['slug'] for t in terms}
assert len(terms)==365 and set(prov)==published
for s,p in prov.items():
    for rel in p.get('relatedTerms',[]): assert rel in published,(s,rel)
researched=sum(p.get('researchStatus')=='researched' for p in prov.values()); pending=sum(p.get('researchStatus')=='pending' for p in prov.values())
assert researched==152 and pending==213,(researched,pending)
for s in RECORDS:
    assert prov[s]['sources'] and all(src.get('supports') for src in prov[s]['sources'])
rp=R/'docs/ROADMAP.md'; road=rp.read_text().replace('142 researched provenance records and 223 pending provenance records','152 researched provenance records and 213 pending provenance records'); rp.write_text(road)
qp=R/'docs/PROVENANCE-REVIEW-QUEUE-2026-09.md'; q=qp.read_text()
q=q.replace('including **142 researched** provenance records and **223 pending** records after provenance Batch 02.','including **152 researched** provenance records and **213 pending** records after provenance Batch 03.')
q=q.replace('Provenance Batches 01–02 completed 20 of the 61 Wave 1 records, leaving **41 Wave 1 reviews** to reach that milestone.','Provenance Batches 01–03 completed 30 of the 61 Wave 1 records, leaving **31 Wave 1 reviews** to reach that milestone.')
marker='## Wave 1 — Majority milestone (61)'
section='''## Provenance Batch 03 — completed September 8, 2026\n\nThis batch concentrated on model architecture, probability-output, evaluation, multimodal, and attention concepts. All ten records completed the initial human-reviewed provenance pass and now use `researchStatus: "researched"`.\n\n1. **Byte-Pair Encoding (BPE)**\n2. **Autoregressive Model**\n3. **Encoder**\n4. **Decoder**\n5. **Cross-Attention**\n6. **Softmax**\n7. **Logit**\n8. **Perplexity**\n9. **Multimodal Model**\n10. **FlashAttention**\n\n'''
assert marker in q; qp.write_text(q.replace(marker,section+marker,1))
print(json.dumps({'published':365,'researched':researched,'pending':pending,'batch':list(RECORDS)},indent=2))
