#!/usr/bin/env python3
import json,re
from pathlib import Path
from html import escape
R=Path(__file__).resolve().parents[1]; D='2026-09-08'; BASE='https://epochlex.justathoughtblog.org'
B=[
{'term':'Inference Backend','slug':'inference-backend','pronunciation':'IN-fer-ens BACK-end','definition':'The software implementation within an inference-serving system that actually executes a model, often by wrapping a framework or runtime such as PyTorch, TensorRT, ONNX Runtime, or a custom execution layer.','example':'The serving platform routed the model to an ONNX Runtime inference backend for execution.','categories':['AI Systems & Technical Concepts'],'aliases':['Model inference backend'],'status':'Established deployment term','partOfSpeech':'noun','related':['inference-server','inference-runtime','model-serving'],'sources':[{'id':'nvidia-triton-backend-2026','type':'primary','publisher':'NVIDIA','title':'Triton Inference Server Backend','published':'2026','url':'https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/backend/README.html','supports':['definition','usage','technical-definition']}]},
{'term':'Model Offloading','slug':'model-offloading','pronunciation':'MOD-ul OFF-loh-ding','definition':'A memory-management technique that moves some model parameters, buffers, or other state from a faster device such as a GPU to slower memory such as CPU RAM or disk so models larger than the fastest device memory can still run.','example':'Model offloading let the workstation run a larger model by keeping only part of it on the GPU at a time.','categories':['AI Systems & Technical Concepts'],'aliases':['AI model offloading'],'status':'Established inference optimization term','partOfSpeech':'noun','related':['gpu-offloading','local-inference','inference-runtime'],'sources':[{'id':'hf-big-model-offload-2026','type':'reference','publisher':'Hugging Face','title':'Loading models — Big Model Inference','published':'2026','url':'https://huggingface.co/docs/transformers/models','supports':['definition','usage','technical-definition']}]},
{'term':'CPU Offloading','slug':'cpu-offloading','pronunciation':'C-P-U OFF-loh-ding','definition':'A model-execution technique that keeps some or all model parameters in CPU memory and transfers them to an accelerator such as a GPU only when needed for computation.','example':'CPU offloading reduced GPU memory pressure by moving inactive model weights back to system RAM between layer executions.','categories':['AI Systems & Technical Concepts'],'aliases':['CPU model offloading'],'status':'Established inference optimization term','partOfSpeech':'noun','related':['model-offloading','gpu-offloading','local-inference'],'sources':[{'id':'hf-accelerate-cpu-offload-2026','type':'reference','publisher':'Hugging Face','title':'Working with large models — cpu_offload','published':'2026','url':'https://huggingface.co/docs/accelerate/package_reference/big_modeling','supports':['definition','usage','technical-definition']}]},
{'term':'Prompt Observability','slug':'prompt-observability','pronunciation':'PROMPT ob-zur-vuh-BIL-uh-tee','definition':'The practice of capturing and analyzing prompt-related traces, versions, inputs, outputs, metadata, and evaluation signals so teams can understand how prompts behave in development and production.','example':'Prompt observability helped the team compare production traces before and after a prompt-template change.','categories':['AI Ways of Working','AI Systems & Technical Concepts'],'aliases':['Prompt tracing'],'status':'Established emerging observability term','partOfSpeech':'noun','related':['llm-observability','model-telemetry','evaluation-trace'],'sources':[{'id':'langfuse-observability-2026','type':'reference','publisher':'Langfuse','title':'Example Project — Tracing and Prompt Management','published':'2026','url':'https://langfuse.com/docs/demo','supports':['definition','usage','observability']}]},
{'term':'Retrieval Pipeline','slug':'retrieval-pipeline','pronunciation':'ree-TREE-vul PIPE-line','definition':'The ordered retrieval and ranking logic that turns a query into a set of top results, potentially combining multiple retrievers, filters, fusion steps, and rerankers.','example':'The retrieval pipeline used sparse and dense retrieval before reranking the combined candidates.','categories':['AI Systems & Technical Concepts','AI Ways of Working'],'aliases':['Search retrieval pipeline'],'status':'Established retrieval term','partOfSpeech':'noun','related':['rag','retriever','reranker'],'sources':[{'id':'elastic-retrieval-pipeline-2026','type':'primary','publisher':'Elastic','title':'Retrievers overview','published':'2026','url':'https://www.elastic.co/docs/solutions/search/retrievers-overview','supports':['definition','usage','technical-definition']}]},
{'term':'Retriever','slug':'retriever','pronunciation':'ree-TREE-ver','definition':'A search component that accepts a query and returns a ranked or otherwise selected set of candidate documents, passages, records, or other items for downstream use.','example':'The RAG application used a retriever to select candidate passages before the language model generated its answer.','categories':['AI Systems & Technical Concepts'],'aliases':['Retrieval component'],'status':'Established retrieval term','partOfSpeech':'noun','related':['rag','dense-retrieval','sparse-retrieval'],'sources':[{'id':'elastic-retriever-2026','type':'primary','publisher':'Elastic','title':'Retrievers','published':'2026','url':'https://www.elastic.co/docs/reference/elasticsearch/rest-apis/retrievers','supports':['definition','usage','technical-definition']}]},
{'term':'AI Security','slug':'ai-security','pronunciation':'A-I sih-KYOOR-uh-tee','definition':'The cybersecurity practices, controls, and technologies used to protect AI models, data, applications, and supporting systems from threats, vulnerabilities, unauthorized access, manipulation, and disruption.','example':'The security review treated prompt injection, model theft, access control, and monitoring as part of the organization’s AI security program.','categories':['AI Risks, Safety & Governance'],'aliases':['Artificial intelligence security'],'status':'Established security term','partOfSpeech':'noun','related':['agent-security','ai-risk-management','prompt-injection'],'sources':[{'id':'microsoft-ai-security-2026','type':'primary','publisher':'Microsoft Security','title':'What is AI Security?','published':'2026','url':'https://www.microsoft.com/en-us/security/business/security-101/what-is-ai-security','supports':['definition','usage','security']}]},
{'term':'Model Inventory','slug':'model-inventory','pronunciation':'MOD-ul IN-ven-tor-ee','definition':'A maintained record of models under development, in use, or retired, together with enough information about ownership, purpose, status, validation, limitations, and risk to support model governance and risk management.','example':'The risk team used the model inventory to identify which production models were awaiting validation review.','categories':['AI Risks, Safety & Governance','AI Ways of Working'],'aliases':['AI model inventory'],'status':'Established model-governance term','partOfSpeech':'noun','related':['ai-inventory','model-risk-management','model-registry'],'sources':[{'id':'fed-model-inventory-2026','type':'primary','publisher':'Federal Reserve','title':'Supervisory Guidance on Model Risk Management — Model Inventory','published':'2026-04-17','url':'https://www.federalreserve.gov/frrs/guidance/supervisory-guidance-on-model-risk-management.htm','supports':['definition','usage','governance']}]},
{'term':'Algorithmic Accountability','slug':'algorithmic-accountability','pronunciation':'al-guh-RITH-mik uh-kown-tuh-BIL-uh-tee','definition':'The principle and practice of making organizations responsible for the effects of automated or algorithmic systems through governance, documentation, transparency, oversight, assessment, and mechanisms for addressing harmful outcomes.','example':'The procurement policy required algorithmic accountability measures for systems that materially affected eligibility decisions.','categories':['AI Risks, Safety & Governance'],'aliases':['Algorithm accountability'],'status':'Established governance concept','partOfSpeech':'noun','related':['ai-accountability','ai-governance','human-oversight'],'sources':[{'id':'ftc-algorithmic-accountability-2022','type':'primary','publisher':'Federal Trade Commission','title':'Combatting Online Harms Through Innovation','published':'2022','url':'https://www.ftc.gov/system/files/ftc_gov/pdf/Combatting%20Online%20Harms%20Through%20Innovation%3B%20Federal%20Trade%20Commission%20Report%20to%20Congress.pdf','supports':['definition','usage','governance']},{'id':'nist-algorithmic-accountability-2026','type':'primary','publisher':'NIST AI Resource Center','title':'AI RMF Playbook — Govern','published':'2026','url':'https://airc.nist.gov/airmf-resources/playbook/govern/','supports':['usage','governance']}]},
{'term':'AI Policy','slug':'ai-policy','pronunciation':'A-I POL-uh-see','definition':'A policy, policy framework, or coordinated set of public or organizational rules and priorities that directs how artificial intelligence is developed, adopted, governed, regulated, or used.','example':'The government updated its AI policy to clarify priorities for trustworthy deployment, skills, research, and oversight.','categories':['AI Risks, Safety & Governance','AI Ways of Working'],'aliases':['Artificial intelligence policy'],'status':'Established governance term','partOfSpeech':'noun','related':['ai-governance','ai-compliance','responsible-ai'],'sources':[{'id':'oecd-ai-policy-2026','type':'primary','publisher':'OECD.AI','title':'The OECD AI Policy Toolkit: Better AI policies for better lives','published':'2026-06-03','url':'https://oecd.ai/en/wonk/the-oecd-ai-policy-toolkit-better-ai-policies-for-better-lives','supports':['definition','usage','governance']},{'id':'oecd-policy-navigator-2026','type':'primary','publisher':'OECD.AI','title':'AI Policy Navigator','published':'2026','url':'https://oecd.ai/en/dashboards/overview','supports':['usage','governance']}]}
]
def page(t):
 u=f'{BASE}/terms/{t["slug"]}/'; n=escape(t['term']); d=escape(t['definition'],quote=True); p=escape(t['pronunciation']); ld=json.dumps({'@context':'https://schema.org','@type':'DefinedTerm','name':t['term'],'description':t['definition'],'url':u,'inDefinedTermSet':BASE+'/','inLanguage':'en'},ensure_ascii=False)
 return f'<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{n} | EpochLex</title><meta name="description" content="{d}"><link rel="canonical" href="{u}"><script type="application/ld+json">{ld}</script><link rel="stylesheet" href="../../assets/css/styles.css"><link rel="stylesheet" href="../../assets/css/term-pages.css"><link rel="stylesheet" href="../../assets/css/brand-theme.css"></head><body><main id="term-page" class="term-page shell" data-term-slug="{t["slug"]}"><div id="term-fallback" class="term-fallback"><nav class="term-breadcrumb"><a href="../../">Browse</a><span>/</span><span>{n}</span></nav><p class="eyebrow">EpochLex entry</p><h1>{n}</h1><p class="fallback-pronunciation">{p}</p><p class="fallback-definition">{escape(t["definition"])}</p></div></main><script src="../../assets/js/app.js"></script><script src="../../assets/js/term-page.js"></script></body></html>\n'
tp=R/'data/terms.json'; terms=json.loads(tp.read_text()); existing={x['slug'] for x in terms}
for b in B:
 if b['slug'] in existing: raise SystemExit('already published: '+b['slug'])
 rec={k:v for k,v in b.items() if k not in ('related','sources')}; rec.update({'added':D,'lastReviewed':D,'sources':[]}); terms.append(rec)
terms.sort(key=lambda x:x['term'].lower()); tp.write_text(json.dumps(terms,ensure_ascii=False,separators=(',',':'))+'\n')
pp=R/'data/provenance.json'; prov=json.loads(pp.read_text())
for b in B: prov[b['slug']]={'researchStatus':'pending','origin':None,'firstKnownUse':None,'history':[],'relatedTerms':b['related'],'sources':b['sources']}
pp.write_text(json.dumps(prov,ensure_ascii=False,indent=2)+'\n')
for b in B:
 p=R/'terms'/b['slug']; p.mkdir(parents=True,exist_ok=True); (p/'index.html').write_text(page(b))
cp=R/'docs/CORPUS-CANDIDATES.md'; text=cp.read_text()
for b in B: text=re.sub(r'^- '+re.escape(b['term'])+r'\s*$','',text,flags=re.M)
text=re.sub(r'\n{3,}','\n\n',text); st=text.index('## Repository roadmap candidates'); en=text.index('## Related documentation'); count=sum(1 for line in text[st:en].splitlines() if line.startswith('- ')); text=re.sub(r'\*\*Current unpublished inventory: \d+ candidates\.\*\*',f'**Current unpublished inventory: {count} candidates.**',text,count=1); cp.write_text(text)
ap=R/'docs/CORPUS-AUDIT-2026-09.md'; a=ap.read_text(); sec='\n## Research Further promotion pass 14 — Batch R (published September 8, 2026)\n\nThis batch is the fourteenth evidence-based promotion from **Research Further**. Promotion records an audit decision for these entries; it does not create a permanent lifecycle state or automatic promotion rule.\n\n'
for b in B:
 src='; '.join(f"[{s['publisher']}: {s['title']}]({s['url']})" for s in b['sources']); sec+=f"### {b['term']}\n\n**Why promote and publish:** {b['definition']}\n\n**Usage evidence:** {src}\n\n**Provenance state:** `pending` — meaning/usage evidence is recorded; origin, first-known-use, and fuller history research remain open.\n\n"
a=a.replace('## Research Further',sec+'## Research Further',1); a=re.sub(r'This audit has now published \d+ candidates across Batches A–Q and added 172 new research candidates\.', 'This audit has now published 173 candidates across Batches A–R and added 172 new research candidates.', a); ap.write_text(re.sub(r'\n{3,}','\n\n',a))
rp=R/'docs/ROADMAP.md'; r=rp.read_text().replace('- 285 published dictionary entries;','- 295 published dictionary entries;').replace('- 122 researched provenance records and 163 pending provenance records in the current published corpus;','- 122 researched provenance records and 173 pending provenance records in the current published corpus;'); rp.write_text(r)
sp=R/'sitemap.xml'; sm=sp.read_text(); blocks=''.join(f'  <url>\n    <loc>{BASE}/terms/{b["slug"]}/</loc>\n    <lastmod>{D}</lastmod>\n  </url>\n' for b in B); sp.write_text(sm.replace('</urlset>',blocks+'</urlset>'))
terms=json.loads(tp.read_text()); prov=json.loads(pp.read_text()); slugs={x['slug'] for x in terms}
assert len(terms)==295, len(terms); assert slugs==set(prov); assert sum(x.get('researchStatus')=='pending' for x in prov.values())==173
assert count==577, count
for b in B: assert (R/'terms'/b['slug']/'index.html').exists()
for slug,p in prov.items():
 for rel in p.get('relatedTerms',[]): assert rel in slugs,(slug,rel)
print('Validated Batch R: 295 published, 173 pending, 577 candidates.')
