#!/usr/bin/env python3
import json,re
from pathlib import Path
from html import escape
R=Path(__file__).resolve().parents[1]; D='2026-09-08'; BASE='https://epochlex.justathoughtblog.org'
B=[
{'term':'Content Credentials','slug':'content-credentials','pronunciation':'KON-tent kruh-DEN-shuls','definition':'Cryptographically verifiable provenance information attached to or associated with digital content to record claims about its origin, edits, and processing history using the C2PA standard.','example':'The image included Content Credentials so viewers could inspect information about how it was created and edited.','categories':['AI Risks, Safety & Governance','AI Systems & Technical Concepts'],'aliases':['C2PA Content Credentials'],'status':'Established provenance standard term','partOfSpeech':'noun','related':['synthetic-content','responsible-ai','ai-governance'],'sources':[{'id':'c2pa-2-4-2026','type':'primary','publisher':'C2PA','title':'Content Credentials: C2PA Technical Specification 2.4','published':'2026-04','url':'https://spec.c2pa.org/specifications/specifications/2.4/specs/C2PA_Specification.html','supports':['definition','usage']}]},
{'term':'Context Caching','slug':'context-caching','pronunciation':'KON-tekst KASH-ing','definition':'A technique for reusing computation associated with previously processed context so repeated or shared prompt prefixes do not have to be fully recomputed for every generation.','example':'The application used context caching for a long shared system prompt that appeared in many requests.','categories':['AI Systems & Technical Concepts'],'aliases':['Prompt caching','Prefix caching'],'status':'Established inference optimization term','partOfSpeech':'noun','related':['context-window','kv-cache','inference','token'],'sources':[{'id':'hf-context-caching-2026','type':'reference','publisher':'Hugging Face','title':'Cache strategies','published':'2026','url':'https://huggingface.co/docs/transformers/main/kv_cache','supports':['definition','usage']}]},
{'term':'MCP Authorization','slug':'mcp-authorization','pronunciation':'M-C-P aw-thur-uh-ZAY-shun','definition':'The authorization mechanisms used with Model Context Protocol connections to control whether an MCP client may access protected MCP servers or capabilities on behalf of a resource owner.','example':'The remote server required MCP Authorization before the client could call its protected tools.','categories':['AI Systems & Technical Concepts','AI Risks, Safety & Governance'],'aliases':['Model Context Protocol authorization'],'status':'Established protocol security term','partOfSpeech':'noun','related':['mcp','tool-calling','ai-agent'],'sources':[{'id':'mcp-auth-2026','type':'primary','publisher':'Model Context Protocol','title':'The 2026-07-28 Specification','published':'2026-07-28','url':'https://blog.modelcontextprotocol.io/posts/2026-07-28/','supports':['definition','usage']}]},
{'term':'MCP Tool','slug':'mcp-tool','pronunciation':'M-C-P tool','definition':'A callable capability exposed by a Model Context Protocol server, described with a name and input schema and invoked by an MCP client through the protocol’s tool-calling methods.','example':'The MCP server exposed a search function as an MCP Tool that the client could discover and call.','categories':['AI Systems & Technical Concepts'],'aliases':['Model Context Protocol tool'],'status':'Established protocol term','partOfSpeech':'noun','related':['mcp','tool-calling','ai-agent'],'sources':[{'id':'mcp-tools-2026','type':'primary','publisher':'Model Context Protocol','title':'The 2026-07-28 Specification','published':'2026-07-28','url':'https://blog.modelcontextprotocol.io/posts/2026-07-28/','supports':['definition','usage']}]},
{'term':'Grader','slug':'grader','pronunciation':'GRAY-dur','definition':'A rule, metric, program, or model used in an AI evaluation to score, label, compare, or otherwise judge a model or system output against defined criteria.','example':'The eval used a grader to assign a score to each response based on the reference answer and rubric.','categories':['AI Systems & Technical Concepts','AI Ways of Working'],'aliases':['Eval grader'],'status':'Established evaluation term','partOfSpeech':'noun','related':['eval','benchmark','ground-truth'],'sources':[{'id':'openai-graders-2026','type':'primary','publisher':'OpenAI','title':'Graders','published':'2026','url':'https://platform.openai.com/docs/api-reference/graders','supports':['definition','usage']}]},
{'term':'Long-Context Evaluation','slug':'long-context-evaluation','pronunciation':'long KON-tekst ih-val-yoo-AY-shun','definition':'Evaluation designed to measure how well a model uses, retrieves from, reasons over, or summarizes information across very long input contexts rather than merely accepting a large context window.','example':'The long-context evaluation tested multi-hop reasoning across a document set far longer than a typical prompt.','categories':['AI Systems & Technical Concepts'],'aliases':['Long-context eval'],'status':'Established emerging evaluation term','partOfSpeech':'noun','related':['eval','context-window','benchmark'],'sources':[{'id':'helm-long-context-2026','type':'reference','publisher':'Stanford CRFM','title':'HELM Long Context','published':'2026','url':'https://crfm.stanford.edu/helm/long-context/latest/','supports':['definition','usage']}]},
{'term':'Structured Output','slug':'structured-output','pronunciation':'STRUK-churd OWT-put','definition':'Model-generated output constrained to follow a specified machine-readable structure or schema so downstream software can reliably parse and use it.','example':'The application requested structured output matching a JSON schema instead of free-form text.','categories':['AI Systems & Technical Concepts','AI Ways of Working'],'aliases':['Structured Outputs'],'status':'Established application-development term','partOfSpeech':'noun','related':['tool-calling','prompt-engineering','large-language-model'],'sources':[{'id':'openai-structured-outputs-2024','type':'primary','publisher':'OpenAI','title':'Introducing Structured Outputs in the API','published':'2024-08-06','url':'https://openai.com/index/introducing-structured-outputs-in-the-api/','supports':['definition','usage']}]},
{'term':'Speculative Decoding','slug':'speculative-decoding','pronunciation':'SPEK-yuh-luh-tiv dee-KOH-ding','definition':'An inference technique that speeds generation by having a faster helper produce candidate tokens that a larger model verifies in fewer expensive forward passes.','example':'The serving stack used speculative decoding to reduce generation latency without changing the final model.','categories':['AI Systems & Technical Concepts'],'aliases':['Speculative generation'],'status':'Established inference optimization term','partOfSpeech':'noun','related':['inference','sampling','large-language-model'],'sources':[{'id':'hf-speculative-decoding-2026','type':'reference','publisher':'Hugging Face','title':'Assisted decoding','published':'2026','url':'https://huggingface.co/docs/transformers/main/assisted_decoding','supports':['definition','usage']}]},
{'term':'KV Cache','slug':'kv-cache','pronunciation':'K-V kash','definition':'A key-value cache that stores attention-layer key and value states for previously processed tokens so an autoregressive model can reuse them during later generation steps instead of recomputing them.','example':'The inference server kept a KV cache to avoid recalculating attention states for the entire conversation on every new token.','categories':['AI Systems & Technical Concepts'],'aliases':['Key-value cache'],'status':'Established transformer inference term','partOfSpeech':'noun','related':['inference','context-caching','large-language-model','token'],'sources':[{'id':'hf-kv-cache-2026','type':'reference','publisher':'Hugging Face','title':'Caching','published':'2026','url':'https://huggingface.co/docs/transformers/cache_explanation','supports':['definition','usage']}]},
{'term':'General-Purpose AI','slug':'general-purpose-ai','pronunciation':'JEN-er-ul PUR-pus A-I','definition':'In the EU AI Act context, AI with significant generality that can competently perform a wide range of distinct tasks and be integrated into varied downstream systems or applications; the Act separately defines general-purpose AI models and systems.','example':'The compliance team assessed whether the model fell within the AI Act rules for general-purpose AI.','categories':['AI Risks, Safety & Governance','AI Systems & Technical Concepts'],'aliases':['GPAI','General-Purpose AI Model','General-purpose artificial intelligence'],'status':'Established regulatory term','partOfSpeech':'noun','related':['artificial-intelligence','ai-governance','frontier-ai','high-risk-ai'],'sources':[{'id':'eu-gpai-guidance-2025','type':'primary','publisher':'European Commission AI Act Service Desk','title':'Guidelines on the scope of the obligations for general-purpose AI models','published':'2025','url':'https://ai-act-service-desk.ec.europa.eu/sites/default/files/2025-07/guidelines_on_the_scope_of_the_obligations_for_generalpurpose_ai_models_established_by_regulation_1cx2atxgq79us4n3x8jfgyy1qlm_118340-3.pdf','supports':['definition','usage','scope']}]}
]
def page(t):
 u=f'{BASE}/terms/{t["slug"]}/'; n=escape(t['term']); d=escape(t['definition'],quote=True); p=escape(t['pronunciation']); ld=json.dumps({'@context':'https://schema.org','@type':'DefinedTerm','name':t['term'],'description':t['definition'],'url':u,'inDefinedTermSet':BASE+'/','inLanguage':'en'},ensure_ascii=False)
 return f'''<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light dark"><title>{n} | EpochLex</title><meta name="description" content="{d}"><link rel="canonical" href="{u}"><meta property="og:site_name" content="EpochLex"><meta property="og:title" content="{n} | EpochLex"><meta property="og:description" content="{d}"><meta property="og:type" content="article"><meta property="og:url" content="{u}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="{n} | EpochLex"><meta name="twitter:description" content="{d}"><script type="application/ld+json">{ld}</script><link rel="stylesheet" href="../../assets/css/styles.css"><link rel="stylesheet" href="../../assets/css/term-pages.css"><link rel="stylesheet" href="../../assets/css/brand-theme.css"></head><body><main id="term-page" class="term-page shell" data-term-slug="{t['slug']}"><div id="term-fallback" class="term-fallback"><nav class="term-breadcrumb" aria-label="Breadcrumb"><a href="../../">Browse</a><span aria-hidden="true">/</span><span>{n}</span></nav><p class="eyebrow">EpochLex entry</p><h1>{n}</h1><p class="fallback-pronunciation">{p}</p><p class="fallback-definition">{escape(t['definition'])}</p></div></main><script src="../../assets/js/app.js"></script><script src="../../assets/js/term-page.js"></script></body></html>\n'''
tp=R/'data/terms.json'; terms=json.loads(tp.read_text()); existing={x['slug'] for x in terms}
for b in B:
 if b['slug'] in existing: raise SystemExit('already published: '+b['slug'])
 rec={k:v for k,v in b.items() if k not in ('related','sources')}; rec.update({'added':D,'lastReviewed':D,'sources':[]}); terms.append(rec)
terms.sort(key=lambda x:x['term'].lower()); tp.write_text(json.dumps(terms,ensure_ascii=False,separators=(',',':'))+'\n')
pp=R/'data/provenance.json'; prov=json.loads(pp.read_text())
for b in B: prov[b['slug']]={'researchStatus':'pending','origin':None,'firstKnownUse':None,'history':[],'relatedTerms':b['related'],'sources':b['sources']}
pp.write_text(json.dumps(prov,ensure_ascii=False,indent=2)+'\n')
for b in B:
 p=R/'terms'/b['slug']; p.mkdir(parents=True,exist_ok=True); (p/'index.html').write_text(page(b))
cp=R/'docs/CORPUS-CANDIDATES.md'; text=cp.read_text()
for b in B:
 text=re.sub(r'^- '+re.escape(b['term'])+r'\s*$','',text,flags=re.M)
 text=re.sub(r'^- \['+re.escape(b['term'])+r'\]\([^\n]+\)\s*$','',text,flags=re.M)
text=re.sub(r'\n{3,}','\n\n',text); st=text.index('## Repository roadmap candidates'); en=text.index('## Related documentation'); count=sum(1 for line in text[st:en].splitlines() if line.startswith('- ')); text=re.sub(r'\*\*Current unpublished inventory: \d+ candidates\.\*\*',f'**Current unpublished inventory: {count} candidates.**',text,count=1); cp.write_text(text)
ap=R/'docs/CORPUS-AUDIT-2026-09.md'; a=ap.read_text(); sec='\n## Research Further promotion pass 3 — Batch G (published September 8, 2026)\n\nThis batch is the third evidence-based promotion from **Research Further**. Promotion records an audit decision for these entries; it does not create a permanent lifecycle state or automatic promotion rule.\n\n'
for b in B:
 src='; '.join(f"[{s['publisher']}: {s['title']}]({s['url']})" for s in b['sources']); sec+=f"### {b['term']}\n\n**Why promote and publish:** {b['definition']}\n\n**Usage evidence:** {src}\n\n**Provenance state:** `pending` — meaning/usage evidence is recorded; origin, first-known-use, and fuller history research remain open.\n\n"
a=a.replace('## Research Further',sec+'## Research Further',1); a=a.replace('This audit has now published 53 candidates across Batches A–F and added 172 new research candidates.','This audit has now published 63 candidates across Batches A–G and added 172 new research candidates.'); ap.write_text(re.sub(r'\n{3,}','\n\n',a))
rp=R/'docs/ROADMAP.md'; r=rp.read_text().replace('- 175 published dictionary entries;','- 185 published dictionary entries;').replace('- 122 researched provenance records and 53 pending provenance records in the current published corpus;','- 122 researched provenance records and 63 pending provenance records in the current published corpus;'); rp.write_text(r)
sp=R/'sitemap.xml'; sm=sp.read_text(); blocks=''.join(f'  <url>\n    <loc>{BASE}/terms/{b["slug"]}/</loc>\n    <lastmod>{D}</lastmod>\n  </url>\n' for b in B); sp.write_text(sm.replace('</urlset>',blocks+'</urlset>'))
terms=json.loads(tp.read_text()); prov=json.loads(pp.read_text()); slugs={x['slug'] for x in terms}
assert len(terms)==185, len(terms); assert slugs==set(prov); assert sum(x.get('researchStatus')=='pending' for x in prov.values())==63
for rec in prov.values():
 for s in rec.get('relatedTerms',[]): assert s in slugs, s
for b in B: assert (R/'terms'/b['slug']/'index.html').exists()
assert count==687, count
print('Validated Batch G: 185 published, 63 pending, 687 candidates, related-term parity.')
