#!/usr/bin/env python3
import json,re
from pathlib import Path
from html import escape
R=Path(__file__).resolve().parents[1]; D='2026-09-08'; BASE='https://epochlex.justathoughtblog.org'
B=[
{'term':'Agent Handoff','slug':'agent-handoff','pronunciation':'AY-jent HAND-off','definition':'A transfer of control from one AI agent to another so the receiving agent continues the workflow with the relevant conversation or task state.','example':'The triage agent used a handoff to transfer the customer to a billing specialist agent.','categories':['AI Systems & Technical Concepts','AI Ways of Working'],'aliases':['Agent-to-agent handoff'],'status':'Established agent orchestration term','partOfSpeech':'noun','related':['ai-agent','agent-to-agent-a2a','multi-agent-orchestration'],'sources':[{'id':'openai-agent-handoff-2026','type':'primary','publisher':'OpenAI','title':'A practical guide to building agents','published':'2026','url':'https://openai.com/business/guides-and-resources/a-practical-guide-to-building-ai-agents/','supports':['definition','usage','technical-definition']}]},
{'term':'Agent Harness','slug':'agent-harness','pronunciation':'AY-jent HAR-niss','definition':'The surrounding software and workflow infrastructure that manages an AI agent’s loop, tools, context, execution environment, state, and control flow so the agent can carry out tasks reliably over time.','example':'The coding agent’s harness managed its tools, sandbox, working state, and repeated execution loop.','categories':['AI Systems & Technical Concepts'],'aliases':['AI agent harness'],'status':'Established emerging agent infrastructure term','partOfSpeech':'noun','related':['agent-runtime','agent-loop','ai-agent'],'sources':[{'id':'openai-agent-harness-2026','type':'primary','publisher':'OpenAI','title':'The next evolution of the Agents SDK','published':'2026-04-15','url':'https://openai.com/index/the-next-evolution-of-the-agents-sdk/','supports':['definition','usage','technical-definition']},{'id':'anthropic-agent-harness-2026','type':'primary','publisher':'Anthropic','title':'Harness design for long-running application development','published':'2026','url':'https://www.anthropic.com/engineering/harness-design-long-running-apps','supports':['usage','technical-definition']}]},
{'term':'Agent Planning','slug':'agent-planning','pronunciation':'AY-jent PLAN-ing','definition':'The process by which an AI agent identifies or organizes intermediate steps, subtasks, or actions needed to complete a larger goal before or during execution.','example':'Agent planning broke the research request into source discovery, comparison, synthesis, and final reporting steps.','categories':['AI Systems & Technical Concepts','AI Ways of Working'],'aliases':['AI agent planning','Planning design pattern'],'status':'Established agent design pattern','partOfSpeech':'noun','related':['ai-agent','agent-state','agent-memory'],'sources':[{'id':'microsoft-agent-planning-2025','type':'primary','publisher':'Microsoft Learn','title':'What Is the AI Agent Planning Design Pattern?','published':'2025-03-24','url':'https://learn.microsoft.com/en-us/shows/ai-agents-for-beginners/what-is-the-ai-agent-planning-design-pattern','supports':['definition','usage','technical-definition']}]},
{'term':'Verifiable Reward','slug':'verifiable-reward','pronunciation':'VAIR-uh-fy-uh-bul ree-WORD','definition':'A reward signal whose correctness or success can be checked automatically or objectively against a rule, reference answer, test, or other verifier rather than relying only on a learned preference model.','example':'A unit-test result served as a verifiable reward for code generated during reinforcement-learning post-training.','categories':['AI Systems & Technical Concepts'],'aliases':['Verifiable rewards','Checker-based reward'],'status':'Established emerging post-training term','partOfSpeech':'noun','related':['reinforcement-learning-with-verifiable-rewards','outcome-reward-model','process-reward-model'],'sources':[{'id':'hf-verifiable-reward-2026','type':'reference','publisher':'Hugging Face','title':'Verifiable Rewards (Rule/Checker-Based Rewards)','published':'2026','url':'https://huggingface.co/datasets/rl-llm-wiki/knowledge-base/blob/main/topics/reward-modeling/verifiable-rewards.md','supports':['definition','usage','technical-definition']},{'id':'microsoft-rlvr-2026','type':'research','publisher':'Microsoft Research','title':'Reinforcement Learning with Verifiable Rewards Implicitly Incentivizes Correct Reasoning in Base LLMs','published':'2026','url':'https://www.microsoft.com/en-us/research/publication/reinforcement-learning-with-verifiable-rewards-implicitly-incentivizes-correct-reasoning-in-base-llms/','supports':['usage','technical-definition']}]},
{'term':'Semantic Chunking','slug':'semantic-chunking','pronunciation':'suh-MAN-tik CHUNK-ing','definition':'A document-splitting approach that creates chunks around semantically coherent content or meaning boundaries instead of relying only on fixed character, token, or length limits.','example':'Semantic chunking kept each policy section together so the retriever could return coherent passages instead of arbitrary text slices.','categories':['AI Systems & Technical Concepts'],'aliases':['Semantic text chunking'],'status':'Established retrieval preparation technique','partOfSpeech':'noun','related':['rag','retrieval-pipeline','contextual-retrieval'],'sources':[{'id':'microsoft-semantic-chunking-2026','type':'primary','publisher':'Microsoft Learn','title':'Retrieval-Augmented Generation with Azure Document Intelligence in Foundry Tools','published':'2026-08-15','url':'https://learn.microsoft.com/en-us/azure/ai-services/document-intelligence/concept/retrieval-augmented-generation?view=doc-intel-4.0.0','supports':['definition','usage','technical-definition']}]},
{'term':'Regression Evaluation','slug':'regression-evaluation','pronunciation':'ree-GRESH-un ih-val-yoo-AY-shun','definition':'An evaluation used to detect whether a model, prompt, retrieval system, or AI application performs worse on previously supported behaviors after a change.','example':'The team ran regression evaluations after changing the retrieval pipeline to make sure previously correct answers still passed.','categories':['AI Ways of Working','AI Systems & Technical Concepts'],'aliases':['Regression eval','AI regression testing'],'status':'Established evaluation practice','partOfSpeech':'noun','related':['automated-evaluation','eval','golden-dataset'],'sources':[{'id':'openai-regression-evals-2026','type':'primary','publisher':'OpenAI','title':'Morgan Stanley uses AI evals to shape the future of financial services','published':'2026','url':'https://openai.com/index/morgan-stanley/','supports':['definition','usage','evaluation']}]},
{'term':'Excessive Agency','slug':'excessive-agency','pronunciation':'ek-SESS-iv AY-jen-see','definition':'A security vulnerability in which an AI or LLM-based system has more functionality, permissions, or autonomy than necessary, allowing unexpected or manipulated outputs to cause damaging actions.','example':'The email agent had excessive agency because it could delete messages without a separate approval step.','categories':['AI Risks, Safety & Governance'],'aliases':['Excessive agent autonomy'],'status':'Established AI security risk','partOfSpeech':'noun','related':['agent-security','least-privilege-agent','tool-approval'],'sources':[{'id':'owasp-excessive-agency-2025','type':'primary','publisher':'OWASP GenAI Security Project','title':'LLM06:2025 Excessive Agency','published':'2025','url':'https://genai.owasp.org/llmrisk/llm062025-excessive-agency/','supports':['definition','usage','security']}]},
{'term':'Prompt Injection Defense','slug':'prompt-injection-defense','pronunciation':'PROMPT in-JEK-shun dee-FENS','definition':'A defense-in-depth set of controls intended to reduce the likelihood or impact of direct or indirect prompt injection, such as input handling, instruction/data separation, least privilege, output validation, monitoring, and approval gates.','example':'The agent used prompt injection defenses that sanitized external content, restricted tool permissions, and required approval for destructive actions.','categories':['AI Risks, Safety & Governance','AI Ways of Working'],'aliases':['Prompt injection defenses','Prompt injection mitigation'],'status':'Established AI security practice','partOfSpeech':'noun','related':['prompt-injection','ai-security','agent-security'],'sources':[{'id':'owasp-prompt-injection-defense-2026','type':'primary','publisher':'OWASP Cheat Sheet Series','title':'LLM Prompt Injection Prevention Cheat Sheet','published':'2026','url':'https://cheatsheetseries.owasp.org/cheatsheets/LLM_Prompt_Injection_Prevention_Cheat_Sheet.html','supports':['definition','usage','security']},{'id':'owasp-prompt-injection-2025','type':'primary','publisher':'OWASP GenAI Security Project','title':'LLM01:2025 Prompt Injection','published':'2025','url':'https://genai.owasp.org/llmrisk/llm01-prompt-injection/','supports':['usage','security']}]},
{'term':'AI Oversight','slug':'ai-oversight','pronunciation':'A-I OH-ver-syte','definition':'The organizational and human governance activities used to supervise, review, challenge, monitor, or intervene in the development, deployment, and operation of AI systems.','example':'The organization assigned an independent risk committee to provide AI oversight for high-impact deployments.','categories':['AI Risks, Safety & Governance'],'aliases':['Artificial intelligence oversight'],'status':'Established governance concept','partOfSpeech':'noun','related':['human-oversight','ai-governance','ai-accountability'],'sources':[{'id':'nist-ai-oversight-2026','type':'primary','publisher':'NIST AI Resource Center','title':'AI RMF Playbook — Map and Govern','published':'2026','url':'https://airc.nist.gov/airmf-resources/playbook/map/','supports':['definition','usage','governance']},{'id':'nist-ai-oversight-govern-2026','type':'primary','publisher':'NIST AI Resource Center','title':'AI RMF Playbook — Govern','published':'2026','url':'https://airc.nist.gov/airmf-resources/playbook/govern/','supports':['usage','governance']}]},
{'term':'Model Audit','slug':'model-audit','pronunciation':'MOD-ul AW-dit','definition':'A structured examination of a model and its surrounding development, validation, monitoring, documentation, controls, or performance to assess whether it meets defined governance, risk, or compliance expectations.','example':'The bank commissioned a model audit to review validation evidence, monitoring controls, documentation, and unresolved model-risk findings.','categories':['AI Risks, Safety & Governance'],'aliases':['AI model audit'],'status':'Established model-governance practice','partOfSpeech':'noun','related':['ai-audit','model-risk-management','model-inventory'],'sources':[{'id':'nist-model-audit-2026','type':'primary','publisher':'NIST AI Resource Center','title':'AI RMF Playbook — Govern','published':'2026','url':'https://airc.nist.gov/airmf-resources/playbook/govern/','supports':['definition','usage','governance']}]}
]
def page(t):
 u=f'{BASE}/terms/{t["slug"]}/'; n=escape(t['term']); d=escape(t['definition'],quote=True); p=escape(t['pronunciation']); ld=json.dumps({'@context':'https://schema.org','@type':'DefinedTerm','name':t['term'],'description':t['definition'],'url':u,'inDefinedTermSet':BASE+'/','inLanguage':'en'},ensure_ascii=False)
 return f'<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{n} | EpochLex</title><meta name="description" content="{d}"><link rel="canonical" href="{u}"><script type="application/ld+json">{ld}</script><link rel="stylesheet" href="../../assets/css/styles.css"><link rel="stylesheet" href="../../assets/css/term-pages.css"><link rel="stylesheet" href="../../assets/css/brand-theme.css"></head><body><main id="term-page" class="term-page shell" data-term-slug="{t["slug"]}"><div id="term-fallback" class="term-fallback"><nav class="term-breadcrumb"><a href="../../">Browse</a><span>/</span><span>{n}</span></nav><p class="eyebrow">EpochLex entry</p><h1>{n}</h1><p class="fallback-pronunciation">{p}</p><p class="fallback-definition">{escape(t["definition"])}</p></div></main><script src="../../assets/js/app.js"></script><script src="../../assets/js/term-page.js"></script></body></html>\n'
tp=R/'data/terms.json'; terms=json.loads(tp.read_text()); existing={x['slug'] for x in terms}
for b in B:
 if b['slug'] in existing: raise SystemExit('already published: '+b['slug'])
 rec={k:v for k,v in b.items() if k not in ('related','sources')}; rec.update({'added':D,'lastReviewed':D,'sources':[]}); terms.append(rec)
terms.sort(key=lambda x:x['term'].lower()); tp.write_text(json.dumps(terms,ensure_ascii=False,separators=(',',':'))+'\n')
pp=R/'data/provenance.json'; prov=json.loads(pp.read_text())
for b in B: prov[b['slug']]={'researchStatus':'pending','origin':None,'firstKnownUse':None,'history':[],'relatedTerms':b['related'],'sources':b['sources']}
pp.write_text(json.dumps(prov,ensure_ascii=False,indent=2)+'\n')
for b in B:
 p=R/'terms'/b['slug']; p.mkdir(parents=True,exist_ok=True); (p/'index.html').write_text(page(b))
cp=R/'docs/CORPUS-CANDIDATES.md'; text=cp.read_text()
for b in B: text=re.sub(r'^- '+re.escape(b['term'])+r'\s*$','',text,flags=re.M)
text=re.sub(r'\n{3,}','\n\n',text); st=text.index('## Repository roadmap candidates'); en=text.index('## Related documentation'); count=sum(1 for line in text[st:en].splitlines() if line.startswith('- ')); text=re.sub(r'\*\*Current unpublished inventory: \d+ candidates\.\*\*',f'**Current unpublished inventory: {count} candidates.**',text,count=1); cp.write_text(text)
ap=R/'docs/CORPUS-AUDIT-2026-09.md'; a=ap.read_text(); sec='\n## Research Further promotion pass 17 — Batch U (published September 8, 2026)\n\nThis batch is the seventeenth evidence-based promotion from **Research Further**. Promotion records an audit decision for these entries; it does not create a permanent lifecycle state or automatic promotion rule.\n\n'
for b in B:
 src='; '.join(f"[{s['publisher']}: {s['title']}]({s['url']})" for s in b['sources']); sec+=f"### {b['term']}\n\n**Why promote and publish:** {b['definition']}\n\n**Usage evidence:** {src}\n\n**Provenance state:** `pending` — meaning/usage evidence is recorded; origin, first-known-use, and fuller history research remain open.\n\n"
a=a.replace('## Research Further',sec+'## Research Further',1); a=re.sub(r'This audit has now published \d+ candidates across Batches A–T and added 172 new research candidates\.', 'This audit has now published 203 candidates across Batches A–U and added 172 new research candidates.', a); ap.write_text(re.sub(r'\n{3,}','\n\n',a))
rp=R/'docs/ROADMAP.md'; r=rp.read_text().replace('- 315 published dictionary entries;','- 325 published dictionary entries;').replace('- 122 researched provenance records and 193 pending provenance records in the current published corpus;','- 122 researched provenance records and 203 pending provenance records in the current published corpus;'); rp.write_text(r)
sp=R/'sitemap.xml'; sm=sp.read_text(); blocks=''.join(f'  <url>\n    <loc>{BASE}/terms/{b["slug"]}/</loc>\n    <lastmod>{D}</lastmod>\n  </url>\n' for b in B); sp.write_text(sm.replace('</urlset>',blocks+'</urlset>'))
terms=json.loads(tp.read_text()); prov=json.loads(pp.read_text()); slugs={x['slug'] for x in terms}
assert len(terms)==325, len(terms); assert slugs==set(prov); assert sum(x.get('researchStatus')=='pending' for x in prov.values())==203
assert count==545, count
for b in B: assert (R/'terms'/b['slug']/'index.html').exists()
for slug,p in prov.items():
 for rel in p.get('relatedTerms',[]): assert rel in slugs,(slug,rel)
print('Validated Batch U: 325 published, 203 pending, 545 candidates.')
