#!/usr/bin/env python3
import json,re
from pathlib import Path
from html import escape
R=Path(__file__).resolve().parents[1]; D='2026-09-08'; BASE='https://epochlex.justathoughtblog.org'
B=[
{'term':'MCP Extension','slug':'mcp-extension','pronunciation':'em-see-PEE ek-STEN-shun','definition':'An opt-in capability that extends Model Context Protocol beyond the core specification, is negotiated through extension metadata, and can evolve and version independently of the protocol core.','example':'The client advertised support for the MCP Tasks extension before the server returned a long-running task handle.','categories':['AI Systems & Technical Concepts'],'aliases':['Model Context Protocol extension'],'status':'Established protocol term','partOfSpeech':'noun','related':['mcp','mcp-apps','mcp-tasks'],'sources':[{'id':'mcp-2026-extensions','type':'primary','publisher':'Model Context Protocol','title':'The 2026-07-28 Specification','published':'2026-07-28','url':'https://blog.modelcontextprotocol.io/posts/2026-07-28/','supports':['definition','usage','technical-definition']}]},
{'term':'MCP UI Resource','slug':'mcp-ui-resource','pronunciation':'em-see-PEE yoo-eye REE-sors','definition':'A server-provided user-interface resource in the MCP Apps extension, referenced by tool metadata and rendered by a host as a sandboxed interactive interface.','example':'The analytics tool returned an MCP UI Resource so the host could render an interactive dashboard directly in the conversation.','categories':['AI Systems & Technical Concepts'],'aliases':['UI Resource','MCP Apps UI resource'],'status':'Established MCP Apps primitive','partOfSpeech':'noun','related':['mcp-apps','mcp-tool','mcp-resource'],'sources':[{'id':'mcp-apps-ui-resource-2026','type':'primary','publisher':'Model Context Protocol','title':'MCP Apps - Bringing UI Capabilities To MCP Clients','published':'2026-01-26','url':'https://blog.modelcontextprotocol.io/posts/2026-01-26-mcp-apps/','supports':['definition','usage','technical-definition']}]},
{'term':'MCP Structured Content','slug':'mcp-structured-content','pronunciation':'em-see-PEE STRUK-cherd KON-tent','definition':'Machine-readable JSON returned by an MCP tool in its structuredContent field, optionally validated against the tool’s output schema alongside other result content.','example':'The weather tool returned MCP Structured Content matching its output schema so the client could consume temperature and humidity as typed data.','categories':['AI Systems & Technical Concepts'],'aliases':['Structured Content in MCP','MCP structuredContent'],'status':'Established protocol data term','partOfSpeech':'noun','related':['mcp-tool','structured-output','mcp'],'sources':[{'id':'mcp-tools-structured-content','type':'primary','publisher':'Model Context Protocol','title':'Tools','published':'2025-11-25','url':'https://modelcontextprotocol.io/specification/2025-11-25/server/tools','supports':['definition','usage','technical-definition']},{'id':'mcp-2026-structured-content','type':'primary','publisher':'Model Context Protocol','title':'The 2026-07-28 Specification Release Candidate','published':'2026-05-21','url':'https://blog.modelcontextprotocol.io/posts/2026-07-28-release-candidate/','supports':['usage','technical-definition']}]},
{'term':'Agent Trace','slug':'agent-trace','pronunciation':'AY-jent trays','definition':'A trace of an AI agent execution that records an ordered span hierarchy across model calls, tool invocations, retrieval, workflow steps, latency, errors, and other telemetry used to inspect the agent’s behavior.','example':'The engineer opened the agent trace to see that a slow database tool call caused most of the response delay.','categories':['AI Systems & Technical Concepts','AI Ways of Working'],'aliases':['AI agent trace'],'status':'Established emerging observability term','partOfSpeech':'noun','related':['agent-observability','ai-agent','llm-observability'],'sources':[{'id':'ms-foundry-agent-tracing-2026','type':'primary','publisher':'Microsoft Foundry','title':'Set Up Tracing for AI Agents in Microsoft Foundry','published':'2026-09-07','url':'https://learn.microsoft.com/en-us/azure/foundry/observability/how-to/trace-agent-setup','supports':['definition','usage','technical-definition']}]},
{'term':'LLM Observability','slug':'llm-observability','pronunciation':'el-el-em ob-zur-vuh-BIL-ih-tee','definition':'The practice of collecting and analyzing telemetry about language-model and generative-AI application behavior—such as traces, model calls, tool calls, tokens, latency, events, and errors—to understand and troubleshoot system operation.','example':'The team used LLM observability to identify repeated tool retries and an unexpected increase in token usage.','categories':['AI Systems & Technical Concepts','AI Ways of Working'],'aliases':['Large language model observability','GenAI observability'],'status':'Established emerging observability term','partOfSpeech':'noun','related':['agent-observability','agent-trace','large-language-model'],'sources':[{'id':'otel-genai-observability-2026','type':'primary','publisher':'OpenTelemetry','title':'Inside the LLM Call: GenAI Observability with OpenTelemetry','published':'2026-05-14','url':'https://opentelemetry.io/blog/2026/genai-observability/','supports':['definition','usage','technical-definition']}]},
{'term':'Evaluation Harness','slug':'evaluation-harness','pronunciation':'ih-val-yoo-AY-shun HAR-nis','definition':'A software framework that runs standardized evaluation tasks, benchmarks, prompts, metrics, and model backends in a repeatable way so model results can be compared and reproduced.','example':'The research team used an evaluation harness to run the same benchmark suite against several local and hosted models.','categories':['AI Systems & Technical Concepts','AI Ways of Working'],'aliases':['Eval harness','Evaluation framework'],'status':'Established evaluation-infrastructure term','partOfSpeech':'noun','related':['eval','benchmark','evaluation-dataset'],'sources':[{'id':'eleutherai-lm-eval-harness','type':'primary','publisher':'EleutherAI','title':'Language Model Evaluation Harness','published':'2026','url':'https://github.com/EleutherAI/lm-evaluation-harness','supports':['definition','usage','technical-definition']}]},
{'term':'Evaluation Dataset','slug':'evaluation-dataset','pronunciation':'ih-val-yoo-AY-shun DAY-tuh-set','definition':'A collection of reusable evaluation inputs, test cases, conversations, traces, contexts, reference answers, or other records prepared for running and comparing AI-system evaluations.','example':'The team versioned an evaluation dataset containing customer-support scenarios and expected outcomes before each release.','categories':['AI Systems & Technical Concepts','AI Ways of Working'],'aliases':['Eval dataset','Evaluation data set'],'status':'Established evaluation term','partOfSpeech':'noun','related':['eval','benchmark','ground-truth'],'sources':[{'id':'ms-foundry-evaluation-datasets-2026','type':'primary','publisher':'Microsoft Foundry','title':'Evaluation datasets in Microsoft Foundry','published':'2026-08-28','url':'https://learn.microsoft.com/en-us/azure/foundry/observability/how-to/evaluation-datasets','supports':['definition','usage','technical-definition']}]},
{'term':'8-Bit Quantization','slug':'8-bit-quantization','pronunciation':'ayt-bit kwon-tuh-ZAY-shun','definition':'Quantization that represents selected model weights or activations with 8-bit numeric precision, commonly to reduce memory use and make inference more efficient than higher-precision representations.','example':'The team used 8-bit quantization so the model could fit in available GPU memory with a smaller memory footprint.','categories':['AI Systems & Technical Concepts'],'aliases':['Int8 quantization','8 bit quantization'],'status':'Established model-compression term','partOfSpeech':'noun','related':['quantization','4-bit-quantization','local-ai'],'sources':[{'id':'hf-bitsandbytes-8bit','type':'primary','publisher':'Hugging Face','title':'Bitsandbytes','published':'2026','url':'https://huggingface.co/docs/transformers/quantization/bitsandbytes','supports':['definition','usage','technical-definition']}]},
{'term':'Quantized Model','slug':'quantized-model','pronunciation':'KWON-tyzed MOD-ul','definition':'A model whose weights, activations, or other numerical representations have been converted to lower precision through quantization to reduce memory or computational cost, often for more efficient inference or deployment.','example':'The laptop ran a quantized model that used substantially less memory than the original higher-precision checkpoint.','categories':['AI Systems & Technical Concepts'],'aliases':['Quantized AI model'],'status':'Established deployment term','partOfSpeech':'noun','related':['quantization','gguf','local-ai'],'sources':[{'id':'hf-transformers-quantization','type':'primary','publisher':'Hugging Face','title':'Quantization','published':'2026','url':'https://huggingface.co/docs/transformers/main_classes/quantization','supports':['definition','usage','technical-definition']},{'id':'hf-bitsandbytes-quantized-model','type':'primary','publisher':'Hugging Face','title':'Bitsandbytes','published':'2026','url':'https://huggingface.co/docs/transformers/quantization/bitsandbytes','supports':['usage']}]},
{'term':'KV Cache Quantization','slug':'kv-cache-quantization','pronunciation':'kay-vee kash kwon-tuh-ZAY-shun','definition':'The reduction of numerical precision used to store a transformer’s key-value attention cache, such as using FP8, to lower cache memory consumption and potentially improve throughput or support longer contexts.','example':'The inference server enabled KV cache quantization to fit more cached tokens in GPU memory during long-context workloads.','categories':['AI Systems & Technical Concepts'],'aliases':['Quantized KV cache','KV-cache quantization'],'status':'Established inference-optimization term','partOfSpeech':'noun','related':['kv-cache','quantization','inference'],'sources':[{'id':'vllm-kv-cache-quantization-2026','type':'primary','publisher':'vLLM','title':'Quantized KV Cache','published':'2026','url':'https://docs.vllm.ai/en/stable/features/quantization/quantized_kvcache/','supports':['definition','usage','technical-definition']}]}
]
def page(t):
 u=f'{BASE}/terms/{t["slug"]}/'; n=escape(t['term']); d=escape(t['definition'],quote=True); p=escape(t['pronunciation']); ld=json.dumps({'@context':'https://schema.org','@type':'DefinedTerm','name':t['term'],'description':t['definition'],'url':u,'inDefinedTermSet':BASE+'/','inLanguage':'en'},ensure_ascii=False)
 return f'<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{n} | EpochLex</title><meta name="description" content="{d}"><link rel="canonical" href="{u}"><script type="application/ld+json">{ld}</script><link rel="stylesheet" href="../../assets/css/styles.css"><link rel="stylesheet" href="../../assets/css/term-pages.css"><link rel="stylesheet" href="../../assets/css/brand-theme.css"></head><body><main id="term-page" class="term-page shell" data-term-slug="{t["slug"]}"><div id="term-fallback" class="term-fallback"><nav class="term-breadcrumb"><a href="../../">Browse</a><span>/</span><span>{n}</span></nav><p class="eyebrow">EpochLex entry</p><h1>{n}</h1><p class="fallback-pronunciation">{p}</p><p class="fallback-definition">{escape(t["definition"])}</p></div></main><script src="../../assets/js/app.js"></script><script src="../../assets/js/term-page.js"></script></body></html>\n'
tp=R/'data/terms.json'; terms=json.loads(tp.read_text()); existing={x['slug'] for x in terms}
for b in B:
 if b['slug'] in existing: raise SystemExit('already published: '+b['slug'])
 rec={k:v for k,v in b.items() if k not in ('related','sources')}; rec.update({'added':D,'lastReviewed':D,'sources':[]}); terms.append(rec)
terms.sort(key=lambda x:x['term'].lower()); tp.write_text(json.dumps(terms,ensure_ascii=False,separators=(',',':'))+'\n')
pp=R/'data/provenance.json'; prov=json.loads(pp.read_text())
for b in B: prov[b['slug']]={'researchStatus':'pending','origin':None,'firstKnownUse':None,'history':[],'relatedTerms':b['related'],'sources':b['sources']}
pp.write_text(json.dumps(prov,ensure_ascii=False,indent=2)+'\n')
for b in B:
 p=R/'terms'/b['slug']; p.mkdir(parents=True,exist_ok=True); (p/'index.html').write_text(page(b))
cp=R/'docs/CORPUS-CANDIDATES.md'; text=cp.read_text()
for b in B: text=re.sub(r'^- '+re.escape(b['term'])+r'\s*$','',text,flags=re.M)
text=re.sub(r'\n{3,}','\n\n',text); st=text.index('## Repository roadmap candidates'); en=text.index('## Related documentation'); count=sum(1 for line in text[st:en].splitlines() if line.startswith('- ')); text=re.sub(r'\*\*Current unpublished inventory: \d+ candidates\.\*\*',f'**Current unpublished inventory: {count} candidates.**',text,count=1); cp.write_text(text)
ap=R/'docs/CORPUS-AUDIT-2026-09.md'; a=ap.read_text(); sec='\n## Research Further promotion pass 11 — Batch O (published September 8, 2026)\n\nThis batch is the eleventh evidence-based promotion from **Research Further**. Promotion records an audit decision for these entries; it does not create a permanent lifecycle state or automatic promotion rule.\n\n'
for b in B:
 src='; '.join(f"[{s['publisher']}: {s['title']}]({s['url']})" for s in b['sources']); sec+=f"### {b['term']}\n\n**Why promote and publish:** {b['definition']}\n\n**Usage evidence:** {src}\n\n**Provenance state:** `pending` — meaning/usage evidence is recorded; origin, first-known-use, and fuller history research remain open.\n\n"
a=a.replace('## Research Further',sec+'## Research Further',1); a=re.sub(r'This audit has now published \d+ candidates across Batches A–N and added 172 new research candidates\.', 'This audit has now published 143 candidates across Batches A–O and added 172 new research candidates.', a); ap.write_text(re.sub(r'\n{3,}','\n\n',a))
rp=R/'docs/ROADMAP.md'; r=rp.read_text().replace('- 255 published dictionary entries;','- 265 published dictionary entries;').replace('- 122 researched provenance records and 133 pending provenance records in the current published corpus;','- 122 researched provenance records and 143 pending provenance records in the current published corpus;'); rp.write_text(r)
sp=R/'sitemap.xml'; sm=sp.read_text(); blocks=''.join(f'  <url>\n    <loc>{BASE}/terms/{b["slug"]}/</loc>\n    <lastmod>{D}</lastmod>\n  </url>\n' for b in B); sp.write_text(sm.replace('</urlset>',blocks+'</urlset>'))
terms=json.loads(tp.read_text()); prov=json.loads(pp.read_text()); slugs={x['slug'] for x in terms}
assert len(terms)==265, len(terms); assert slugs==set(prov); assert sum(x.get('researchStatus')=='pending' for x in prov.values())==143
for rec in prov.values():
 for s in rec.get('relatedTerms',[]): assert s in slugs, s
for b in B: assert (R/'terms'/b['slug']/'index.html').exists()
assert count==607, count
print('Validated Batch O: 265 published, 143 pending, 607 candidates, related-term parity.')
