#!/usr/bin/env python3
import json,re
from pathlib import Path
from html import escape
R=Path(__file__).resolve().parents[1]; D='2026-09-08'; BASE='https://epochlex.justathoughtblog.org'
B=[
{'term':'Query Routing','slug':'query-routing','pronunciation':'KWEE-ree ROW-ting','definition':'The practice of directing an incoming query to the most suitable model, retriever, search system, tool, or processing path based on the query and the available capabilities.','example':'The RAG system used query routing to send product questions to keyword search and conceptual questions to vector retrieval.','categories':['AI Systems & Technical Concepts','AI Ways of Working'],'aliases':['Query router'],'status':'Established emerging routing term','partOfSpeech':'noun','related':['rag','contextual-retrieval','semantic-router'],'sources':[{'id':'rag-query-routing-2025','type':'research','publisher':'arXiv','title':'Query Routing for Retrieval-Augmented Language Models','published':'2025-05-29','url':'https://arxiv.org/abs/2505.23052','supports':['definition','usage','technical-definition']},{'id':'unsupervised-query-routing-2025','type':'research','publisher':'arXiv','title':'Unsupervised Query Routing for Retrieval Augmented Generation','published':'2025-01-14','url':'https://arxiv.org/abs/2501.07793','supports':['definition','usage']}]},
{'term':'Semantic Router','slug':'semantic-router','pronunciation':'seh-MAN-tik ROW-ter','definition':'A routing component that uses the semantic meaning or other interpreted signals from a request to select an appropriate model, capability, tool, or processing path.','example':'The application used a semantic router to direct simple requests to a fast model and complex requests to a more capable model path.','categories':['AI Systems & Technical Concepts','AI Ways of Working'],'aliases':['Semantic routing layer'],'status':'Established emerging routing term','partOfSpeech':'noun','related':['query-routing','model-serving','ai-agent'],'sources':[{'id':'vllm-semantic-router-2026','type':'primary','publisher':'vLLM Project','title':'vLLM Semantic Router — Introduction','published':'2026','url':'https://github.com/vllm-project/semantic-router/blob/main/website/docs/intro.md','supports':['definition','usage','technical-definition']},{'id':'semantic-router-docs','type':'primary','publisher':'Aurelio Labs','title':'Semantic Router documentation','published':'2024','url':'https://semantic-router.readthedocs.io/en/stable/','supports':['definition','usage']}]},
{'term':'Agent Authorization','slug':'agent-authorization','pronunciation':'AY-jent aw-thur-uh-ZAY-shun','definition':'The process of determining and granting what an AI agent is allowed to access or do, including which resources, scopes, actions, or delegated permissions it may use.','example':'The deployment required agent authorization before the assistant could access Microsoft 365 resources on the user’s behalf.','categories':['AI Risks, Safety & Governance','AI Ways of Working'],'aliases':['AI agent authorization'],'status':'Established emerging security term','partOfSpeech':'noun','related':['agent-identity','agent-permission','least-privilege-agent'],'sources':[{'id':'microsoft-agent-authorization-2026','type':'primary','publisher':'Microsoft Learn','title':'Grant agents access to Microsoft 365 resources','published':'2026-05-01','url':'https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/agent-id/grant-agent-access-microsoft-365.md','supports':['definition','usage','risk']}]},
{'term':'AI Risk Management','slug':'ai-risk-management','pronunciation':'A-I risk MAN-ij-ment','definition':'The coordinated practice of identifying, assessing, prioritizing, treating, monitoring, and governing risks associated with artificial-intelligence systems across their lifecycle and use context.','example':'The organization used AI risk management to connect system risks with governance controls, evaluation evidence, and ongoing monitoring.','categories':['AI Risks, Safety & Governance','AI Ways of Working'],'aliases':['Artificial intelligence risk management'],'status':'Established governance term','partOfSpeech':'noun','related':['ai-risk-assessment','ai-governance','ai-assurance'],'sources':[{'id':'nist-ai-rmf','type':'primary','publisher':'NIST','title':'AI Risk Management Framework','published':'2026','url':'https://www.nist.gov/itl/ai-risk-management-framework','supports':['definition','usage','governance']},{'id':'iso-ai-risk-management','type':'standard','publisher':'ISO','title':'ISO/IEC 23894:2023 — Artificial intelligence — Guidance on risk management','published':'2023-02','url':'https://www.iso.org/standard/77304.html','supports':['definition','usage','governance']}]},
{'term':'AI Act','slug':'ai-act','pronunciation':'A-I akt','definition':'The European Union’s Artificial Intelligence Act, Regulation (EU) 2024/1689, which establishes harmonized rules and obligations for AI systems and general-purpose AI models using a risk-based regulatory framework.','example':'The legal team reviewed the AI Act to determine which obligations applied to the company’s general-purpose AI model and downstream systems.','categories':['AI Risks, Safety & Governance'],'aliases':['EU AI Act','European Union AI Act','Artificial Intelligence Act'],'status':'Established regulatory term','partOfSpeech':'proper noun','related':['high-risk-ai','general-purpose-ai','ai-risk-management'],'sources':[{'id':'eu-ai-act-official-2026','type':'primary','publisher':'European Commission','title':'AI Act','published':'2026-08','url':'https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai','supports':['definition','usage','regulation']},{'id':'eu-ai-act-explorer','type':'primary','publisher':'AI Act Service Desk','title':'AI Act Explorer','published':'2026','url':'https://ai-act-service-desk.ec.europa.eu/en/ai-act-explorer','supports':['definition','regulation']}]},
{'term':'ONNX','slug':'onnx','pronunciation':'ON-iks','definition':'Open Neural Network Exchange: an open format and ecosystem for representing machine-learning models using a standardized computation graph, operators, and data types so models can move across compatible frameworks, tools, and runtimes.','example':'The team exported the trained model to ONNX so it could run with a different inference runtime in production.','categories':['AI Systems & Technical Concepts'],'aliases':['Open Neural Network Exchange'],'status':'Established interoperability standard and format','partOfSpeech':'proper noun','related':['model-serving','local-ai','model-license'],'sources':[{'id':'onnx-official-intro','type':'primary','publisher':'ONNX','title':'Introduction to ONNX','published':'2026','url':'https://onnx.ai/onnx/intro/','supports':['definition','usage','technical-definition']},{'id':'onnx-github','type':'primary','publisher':'ONNX','title':'Open standard for machine learning interoperability','published':'2026','url':'https://github.com/onnx/onnx','supports':['definition','usage']}]},
{'term':'Open-Source AI','slug':'open-source-ai','pronunciation':'OH-pun sors A-I','definition':'An AI system made available in a way that grants users the freedoms to use, study, modify, and share the system, with access to the preferred form for making modifications as specified by the Open Source AI Definition.','example':'The project described itself as Open-Source AI only after checking that its licensing and released materials satisfied the Open Source AI Definition.','categories':['AI Systems & Technical Concepts','AI Risks, Safety & Governance'],'aliases':['Open Source AI'],'status':'Established open-source definition term','partOfSpeech':'noun','related':['open-weight-model','model-license','local-ai'],'sources':[{'id':'osi-osaid-1','type':'primary','publisher':'Open Source Initiative','title':'The Open Source AI Definition — 1.0','published':'2024-10-28','url':'https://opensource.org/ai/open-source-ai-definition','supports':['definition','usage','governance']}]},
{'term':'Human Evaluation','slug':'human-evaluation','pronunciation':'HYOO-mun ih-val-yoo-AY-shun','definition':'Evaluation in which people directly judge, rate, compare, or otherwise assess AI outputs or behavior using defined criteria rather than relying only on automated metrics or model-based graders.','example':'The team used human evaluation to validate whether the automated quality grader agreed with expert reviewers.','categories':['AI Ways of Working','AI Systems & Technical Concepts'],'aliases':['Human eval','Human evals'],'status':'Established evaluation method','partOfSpeech':'noun','related':['eval','pairwise-evaluation','agent-evaluation'],'sources':[{'id':'google-human-evaluation-2026','type':'reference','publisher':'Google Cloud','title':'Evaluating Single LLM Outputs With Vertex AI Evaluation','published':'2026','url':'https://codelabs.developers.google.com/codelabs/production-ready-ai-with-gc/6-ai-evaluation/evaluating-single-llm-outputs-with-vertex-ai-evaluation','supports':['definition','usage']},{'id':'google-judge-human-ratings','type':'reference','publisher':'Google Cloud','title':'Evaluate a judge model','published':'2026','url':'https://docs.cloud.google.com/vertex-ai/generative-ai/docs/models/evaluate-judge-model','supports':['usage','evaluation']}]},
{'term':'Task Success Rate','slug':'task-success-rate','pronunciation':'task suk-SESS rayt','definition':'An evaluation metric measuring the proportion of attempted tasks in which an AI system or agent reaches the defined successful outcome or pass condition.','example':'The agent’s task success rate improved after the team fixed tool-selection failures and clarified the completion criteria.','categories':['AI Systems & Technical Concepts','AI Ways of Working'],'aliases':['Task success','Task completion success rate'],'status':'Established agent evaluation metric','partOfSpeech':'noun','related':['agent-evaluation','eval','human-evaluation'],'sources':[{'id':'snowflake-agent-evaluation','type':'reference','publisher':'Snowflake','title':'AI Agent Evaluation: Metrics and Methods','published':'2026','url':'https://www.snowflake.com/en/artificial-intelligence/agents/agent-evaluation/','supports':['definition','usage','evaluation']}]},
{'term':'MCP Host','slug':'mcp-host','pronunciation':'em-see-PEE hohst','definition':'The AI application in a Model Context Protocol architecture that coordinates and manages one or more MCP clients and integrates the capabilities they obtain from MCP servers into the application experience.','example':'The IDE acted as the MCP host while separate MCP clients connected it to documentation and issue-tracking servers.','categories':['AI Systems & Technical Concepts'],'aliases':['Model Context Protocol host'],'status':'Established protocol term','partOfSpeech':'noun','related':['mcp','mcp-client','mcp-server'],'sources':[{'id':'mcp-core-architecture','type':'primary','publisher':'Model Context Protocol','title':'Core architecture','published':'2026','url':'https://github.com/modelcontextprotocol/docs/blob/main/docs/concepts/architecture.mdx','supports':['definition','usage','technical-definition']},{'id':'microsoft-mcp-architecture','type':'reference','publisher':'Microsoft Learn','title':'Overview of MCP servers in Azure API Management','published':'2025','url':'https://learn.microsoft.com/en-us/azure/api-management/mcp-server-overview','supports':['definition','usage']}]}
]
def page(t):
 u=f'{BASE}/terms/{t["slug"]}/'; n=escape(t['term']); d=escape(t['definition'],quote=True); p=escape(t['pronunciation']); ld=json.dumps({'@context':'https://schema.org','@type':'DefinedTerm','name':t['term'],'description':t['definition'],'url':u,'inDefinedTermSet':BASE+'/','inLanguage':'en'},ensure_ascii=False)
 return f'<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{n} | EpochLex</title><meta name="description" content="{d}"><link rel="canonical" href="{u}"><script type="application/ld+json">{ld}</script><link rel="stylesheet" href="../../assets/css/styles.css"><link rel="stylesheet" href="../../assets/css/term-pages.css"><link rel="stylesheet" href="../../assets/css/brand-theme.css"></head><body><main id="term-page" class="term-page shell" data-term-slug="{t["slug"]}"><div id="term-fallback" class="term-fallback"><nav class="term-breadcrumb"><a href="../../">Browse</a><span>/</span><span>{n}</span></nav><p class="eyebrow">EpochLex entry</p><h1>{n}</h1><p class="fallback-pronunciation">{p}</p><p class="fallback-definition">{escape(t["definition"])}</p></div></main><script src="../../assets/js/app.js"></script><script src="../../assets/js/term-page.js"></script></body></html>\n'
tp=R/'data/terms.json'; terms=json.loads(tp.read_text()); existing={x['slug'] for x in terms}
for b in B:
 if b['slug'] in existing: raise SystemExit('already published: '+b['slug'])
 rec={k:v for k,v in b.items() if k not in ('related','sources')}; rec.update({'added':D,'lastReviewed':D,'sources':[]}); terms.append(rec)
terms.sort(key=lambda x:x['term'].lower()); tp.write_text(json.dumps(terms,ensure_ascii=False,separators=(',',':'))+'\n')
pp=R/'data/provenance.json'; prov=json.loads(pp.read_text())
for b in B: prov[b['slug']]={'researchStatus':'pending','origin':None,'firstKnownUse':None,'history':[],'relatedTerms':b['related'],'sources':b['sources']}
pp.write_text(json.dumps(prov,ensure_ascii=False,indent=2)+'\n')
for b in B:
 p=R/'terms'/b['slug']; p.mkdir(parents=True,exist_ok=True); (p/'index.html').write_text(page(b))
cp=R/'docs/CORPUS-CANDIDATES.md'; text=cp.read_text(); labels={'Query Routing':'Query Routing','Semantic Router':'Semantic Router','Agent Authorization':'Agent Authorization','AI Risk Management':'AI Risk Management','AI Act':'AI Act','ONNX':'ONNX','Open-Source AI':'Open-Source AI','Human Evaluation':'Human Evaluation','Task Success Rate':'Task Success Rate','MCP Host':'MCP Host'}
for b in B: text=re.sub(r'^- '+re.escape(labels[b['term']])+r'\s*$','',text,flags=re.M)
text=re.sub(r'\n{3,}','\n\n',text); st=text.index('## Repository roadmap candidates'); en=text.index('## Related documentation'); count=sum(1 for line in text[st:en].splitlines() if line.startswith('- ')); text=re.sub(r'\*\*Current unpublished inventory: \d+ candidates\.\*\*',f'**Current unpublished inventory: {count} candidates.**',text,count=1); cp.write_text(text)
ap=R/'docs/CORPUS-AUDIT-2026-09.md'; a=ap.read_text(); sec='\n## Research Further promotion pass 8 — Batch L (published September 8, 2026)\n\nThis batch is the eighth evidence-based promotion from **Research Further**. Promotion records an audit decision for these entries; it does not create a permanent lifecycle state or automatic promotion rule.\n\n'
for b in B:
 src='; '.join(f"[{s['publisher']}: {s['title']}]({s['url']})" for s in b['sources']); sec+=f"### {b['term']}\n\n**Why promote and publish:** {b['definition']}\n\n**Usage evidence:** {src}\n\n**Provenance state:** `pending` — meaning/usage evidence is recorded; origin, first-known-use, and fuller history research remain open.\n\n"
a=a.replace('## Research Further',sec+'## Research Further',1); a=re.sub(r'This audit has now published \d+ candidates across Batches A–K and added 172 new research candidates\.', 'This audit has now published 113 candidates across Batches A–L and added 172 new research candidates.', a); ap.write_text(re.sub(r'\n{3,}','\n\n',a))
rp=R/'docs/ROADMAP.md'; r=rp.read_text().replace('- 225 published dictionary entries;','- 235 published dictionary entries;').replace('- 122 researched provenance records and 103 pending provenance records in the current published corpus;','- 122 researched provenance records and 113 pending provenance records in the current published corpus;'); rp.write_text(r)
sp=R/'sitemap.xml'; sm=sp.read_text(); blocks=''.join(f'  <url>\n    <loc>{BASE}/terms/{b["slug"]}/</loc>\n    <lastmod>{D}</lastmod>\n  </url>\n' for b in B); sp.write_text(sm.replace('</urlset>',blocks+'</urlset>'))
terms=json.loads(tp.read_text()); prov=json.loads(pp.read_text()); slugs={x['slug'] for x in terms}
assert len(terms)==235, len(terms); assert slugs==set(prov); assert sum(x.get('researchStatus')=='pending' for x in prov.values())==113
for rec in prov.values():
 for s in rec.get('relatedTerms',[]): assert s in slugs, s
for b in B: assert (R/'terms'/b['slug']/'index.html').exists()
assert count==637, count
print('Validated Batch L: 235 published, 113 pending, 637 candidates, related-term parity.')
