#!/usr/bin/env python3
import json
from pathlib import Path
R=Path(__file__).resolve().parents[1]
RECORDS={
'latent-space':{'researchStatus':'researched','origin':'Latent space comes from the broader statistical and machine-learning tradition of representing data through underlying variables that are not directly observed. In modern deep learning and generative AI, the term refers to a learned representation space that compresses salient structure from higher-dimensional input data. EpochLex does not assign the general concept to a single AI-era coinage.','firstKnownUse':None,'history':[],'sources':[{'id':'ibm-latent-space','type':'reference','publisher':'IBM','title':'What Is Latent Space?','published':None,'url':'https://www.ibm.com/think/topics/latent-space','supports':['definition','usage','technical-definition']}]},
'rag-pipeline':{'researchStatus':'researched','origin':'“RAG pipeline” is a descriptive systems term built on retrieval-augmented generation rather than a separately established coinage. It refers to the end-to-end workflow that prepares and indexes source material, retrieves relevant context at query time, augments the model input, and generates a grounded response. Modern implementations often separate indexing or ingestion from the online query path.','firstKnownUse':None,'history':[{'date':'2020-05-22','event':'Lewis and colleagues submitted the Retrieval-Augmented Generation paper, establishing the modern RAG framework that later production pipelines operationalized.'}],'sources':[{'id':'lewis-rag-2020','type':'primary','publisher':'arXiv','title':'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks','published':'2020-05-22','url':'https://arxiv.org/abs/2005.11401','supports':['history','technical-definition']},{'id':'microsoft-rag-azure-files-2026','type':'primary','publisher':'Microsoft Learn','title':'Retrieval-Augmented Generation (RAG) with Azure Files','published':'2026','url':'https://learn.microsoft.com/en-us/azure/storage/files/artificial-intelligence/retrieval-augmented-generation/overview','supports':['definition','usage','technical-definition']}]},
'agent-loop':{'researchStatus':'researched','origin':'Agent loop is a descriptive term for the repeated control cycle in which an agent interprets its current state, plans or selects an action, uses a tool or takes another step, observes the result, and continues until completion or intervention. The pattern reflects older control-loop ideas and modern agent runtimes rather than a single established coinage.','firstKnownUse':None,'history':[],'sources':[{'id':'anthropic-trustworthy-agents-2026','type':'primary','publisher':'Anthropic','title':'Trustworthy agents in practice','published':'2026-04-09','url':'https://www.anthropic.com/research/trustworthy-agents','supports':['definition','usage']},{'id':'openai-agents-running','type':'primary','publisher':'OpenAI','title':'Running agents - OpenAI Agents SDK','published':None,'url':'https://openai.github.io/openai-agents-python/running_agents/','supports':['definition','usage','technical-definition']}]},
'autonomous-agent':{'researchStatus':'researched','origin':'Autonomous agent is an established agent-design label rather than a single modern coinage. In current generative-AI usage it describes an agent that can pursue goals, make decisions, and execute tasks with limited or no step-by-step human direction, while still operating within configured tools, permissions, triggers, and guardrails.','firstKnownUse':None,'history':[],'sources':[{'id':'anthropic-safe-agents-2025','type':'primary','publisher':'Anthropic','title':'Our framework for developing safe and trustworthy agents','published':'2025-08-04','url':'https://www.anthropic.com/news/our-framework-for-developing-safe-and-trustworthy-agents','supports':['definition','usage','risk']},{'id':'microsoft-autonomous-agents-2026','type':'primary','publisher':'Microsoft Learn','title':'Design autonomous agent capabilities','published':'2026','url':'https://learn.microsoft.com/en-us/microsoft-copilot-studio/guidance/autonomous-agents','supports':['definition','usage','technical-definition']}]},
'agent-skills':{'researchStatus':'researched','origin':'Anthropic introduced Agent Skills in 2025 as organized folders of instructions, scripts, and resources that agents can discover and load dynamically to perform specialized work. Anthropic later published Agent Skills as an open standard for cross-platform portability.','firstKnownUse':{'date':'2025-10-16','precision':'day','note':'Anthropic published “Equipping agents for the real world with Agent Skills” on October 16, 2025, explicitly introducing the named mechanism.'},'history':[{'date':'2025-10-16','event':'Anthropic introduced Agent Skills as composable folders of instructions, scripts, and resources for specialized agent capabilities.'},{'date':'2025-12-18','event':'Anthropic published Agent Skills as an open standard for cross-platform portability.'}],'sources':[{'id':'anthropic-agent-skills-2025','type':'primary','publisher':'Anthropic','title':'Equipping agents for the real world with Agent Skills','published':'2025-10-16','url':'https://www.anthropic.com/engineering/equipping-agents-for-the-real-world-with-agent-skills','supports':['origin','firstKnownUse','definition','history','usage']}]},
'browser-use':{'researchStatus':'researched','origin':'Browser use is a descriptive capability term for agents that navigate and interact with websites through a browser interface. Modern implementations may operate through screenshots, DOM information, mouse and keyboard actions, or a combination of these. EpochLex does not assign the generic phrase to a single origin.','firstKnownUse':None,'history':[{'date':'2025-01-23','event':'OpenAI introduced Operator, a browser-using agent that could navigate websites and perform tasks through a browser interface.'}],'sources':[{'id':'openai-operator-2025','type':'primary','publisher':'OpenAI','title':'Introducing Operator','published':'2025-01-23','url':'https://openai.com/index/introducing-operator/','supports':['history','usage']},{'id':'openai-cua-browser-use','type':'primary','publisher':'OpenAI','title':'Computer-Using Agent','published':'2025','url':'https://openai.com/index/computer-using-agent/','supports':['definition','usage','evaluation']},{'id':'anthropic-agent-evals-browser-2026','type':'primary','publisher':'Anthropic','title':'Demystifying evals for AI agents','published':'2026','url':'https://www.anthropic.com/engineering/demystifying-evals-for-ai-agents','supports':['definition','usage','contrast']}]},
'agent-security':{'researchStatus':'researched','origin':'Agent security is an umbrella security concept for protecting AI agents, their identities, tools, memory, data, execution environments, and interactions from misuse or compromise. Its scope has expanded as agents gained autonomy and access to external systems, but the term does not have a single established coinage.','firstKnownUse':None,'history':[{'date':'2026-06-01','event':'OWASP published version 2.01 of its State of Agentic AI Security and Governance, reflecting the maturation of agent-specific security and governance practices.'},{'date':'2026-09-01','event':'OWASP published the Agent Control Standard as an open foundation for runtime transparency and control across agent platforms.'}],'sources':[{'id':'owasp-ai-agent-security-cheat-sheet','type':'reference','publisher':'OWASP','title':'AI Agent Security Cheat Sheet','published':None,'url':'https://cheatsheetseries.owasp.org/cheatsheets/AI_Agent_Security_Cheat_Sheet.html','supports':['definition','risk','usage','technical-definition']},{'id':'owasp-agentic-security-2026','type':'primary','publisher':'OWASP GenAI Security Project','title':'State of Agentic AI Security and Governance 2.01','published':'2026-06-01','url':'https://genai.owasp.org/resource/state-of-agentic-ai-security-and-governance/','supports':['history','usage','risk']}]},
'agent-handoff':{'researchStatus':'researched','origin':'Agent handoff is a multi-agent orchestration pattern in which one agent transfers control of a task or conversation to another specialized agent. The pattern is implemented explicitly in current agent frameworks, but EpochLex does not claim a single origin for the generic term.','firstKnownUse':None,'history':[],'sources':[{'id':'openai-agent-handoffs','type':'primary','publisher':'OpenAI','title':'Handoffs - OpenAI Agents SDK','published':None,'url':'https://openai.github.io/openai-agents-python/handoffs/','supports':['definition','usage','technical-definition']},{'id':'openai-agent-orchestration','type':'primary','publisher':'OpenAI','title':'Agent orchestration - OpenAI Agents SDK','published':None,'url':'https://openai.github.io/openai-agents-python/multi_agent/','supports':['definition','usage','contrast']}]},
'agent-planning':{'researchStatus':'researched','origin':'Agent planning is the process by which an agent decomposes or organizes work before or during execution, selecting intermediate steps, tools, or subgoals toward a larger objective. Planning has deep roots in classical AI; current LLM-agent frameworks expose it through explicit plan modes, task lists, or model-directed orchestration. EpochLex does not assign the general concept to a modern coinage.','firstKnownUse':None,'history':[],'sources':[{'id':'microsoft-agent-planning-2026','type':'primary','publisher':'Microsoft Learn','title':'Planning and todos','published':'2026','url':'https://learn.microsoft.com/en-us/agent-framework/agents/planning-and-todos','supports':['definition','usage','technical-definition']},{'id':'openai-agent-orchestration','type':'primary','publisher':'OpenAI','title':'Agent orchestration - OpenAI Agents SDK','published':None,'url':'https://openai.github.io/openai-agents-python/multi_agent/','supports':['definition','usage']}]},
'on-device-ai':{'researchStatus':'researched','origin':'On-device AI describes AI models or features whose inference runs on the user’s local device rather than depending entirely on a remote server. The pattern predates today’s foundation models through mobile and edge machine learning, so EpochLex does not assign the umbrella term to one inventor.','firstKnownUse':None,'history':[{'date':'2025','event':'Apple exposed the on-device foundation model behind Apple Intelligence to developers through the Foundation Models framework, making local generative-AI inference a first-class application capability.'},{'date':'2026','event':'Apple expanded its on-device AI platform with Core AI and continued Foundation Models updates for local model execution and agentic application features.'}],'sources':[{'id':'apple-foundation-models-on-device','type':'primary','publisher':'Apple Developer','title':'Generating content and performing tasks with Foundation Models','published':None,'url':'https://developer.apple.com/documentation/FoundationModels/generating-content-and-performing-tasks-with-foundation-models','supports':['definition','usage','technical-definition']},{'id':'apple-ai-machine-learning-2026','type':'primary','publisher':'Apple Developer','title':'AI & Machine Learning','published':'2026','url':'https://developer.apple.com/machine-learning/','supports':['history','usage','technical-definition']}]}
}
pp=R/'data/provenance.json'; prov=json.loads(pp.read_text())
for slug,record in RECORDS.items():
    assert slug in prov, slug
    assert prov[slug].get('researchStatus')=='pending',(slug,prov[slug].get('researchStatus'))
    record['relatedTerms']=prov[slug].get('relatedTerms',[])
    prov[slug]=record
pp.write_text(json.dumps(prov,indent=2,ensure_ascii=False)+'\n')
terms=json.loads((R/'data/terms.json').read_text()); published={t['slug'] for t in terms}
assert len(terms)==365 and set(prov)==published
for s,p in prov.items():
    for rel in p.get('relatedTerms',[]): assert rel in published,(s,rel)
researched=sum(p.get('researchStatus')=='researched' for p in prov.values()); pending=sum(p.get('researchStatus')=='pending' for p in prov.values())
assert researched==172 and pending==193,(researched,pending)
for s in RECORDS:
    assert prov[s]['sources'] and all(src.get('supports') for src in prov[s]['sources'])
rp=R/'docs/ROADMAP.md'; road=rp.read_text().replace('162 researched provenance records and 203 pending provenance records','172 researched provenance records and 193 pending provenance records'); rp.write_text(road)
qp=R/'docs/PROVENANCE-REVIEW-QUEUE-2026-09.md'; q=qp.read_text()
q=q.replace('including **162 researched** provenance records and **203 pending** records after provenance Batch 04.','including **172 researched** provenance records and **193 pending** records after provenance Batch 05.')
q=q.replace('Provenance Batches 01–04 completed 40 of the 61 Wave 1 records, leaving **21 Wave 1 reviews** to reach that milestone.','Provenance Batches 01–05 completed 50 of the 61 Wave 1 records, leaving **11 Wave 1 reviews** to reach that milestone.')
marker='## Wave 1 — Majority milestone (61)'
section='''## Provenance Batch 05 — completed September 8, 2026\n\nThis batch concentrated on agent architecture and practical AI, with two remaining technical backbone entries. All ten records completed the initial human-reviewed provenance pass and now use `researchStatus: "researched"`.\n\n1. **Latent Space**\n2. **RAG Pipeline**\n3. **Agent Loop**\n4. **Autonomous Agent**\n5. **Agent Skills**\n6. **Browser Use**\n7. **Agent Security**\n8. **Agent Handoff**\n9. **Agent Planning**\n10. **On-Device AI**\n\n'''
assert marker in q; qp.write_text(q.replace(marker,section+marker,1))
print(json.dumps({'published':365,'researched':researched,'pending':pending,'batch':list(RECORDS)},indent=2))
