#!/usr/bin/env python3
import json,re
from pathlib import Path
from html import escape
R=Path(__file__).resolve().parents[1]; D='2026-09-08'; BASE='https://epochlex.justathoughtblog.org'
B=[
{'term':'MCP Transport','slug':'mcp-transport','pronunciation':'em-see-PEE TRANS-port','definition':'The communication mechanism used to carry Model Context Protocol messages between an MCP client and server. The protocol defines transports including standard input/output for local subprocess connections and Streamable HTTP for networked connections.','example':'The local integration used the stdio MCP transport, while the remote service exposed a Streamable HTTP endpoint.','categories':['AI Systems & Technical Concepts'],'aliases':['Model Context Protocol transport'],'status':'Established protocol term','partOfSpeech':'noun','related':['mcp','mcp-client','mcp-server'],'sources':[{'id':'mcp-transports-2025','type':'primary','publisher':'Model Context Protocol','title':'Transports','published':'2025-06-18','url':'https://modelcontextprotocol.io/specification/2025-06-18/basic/transports','supports':['definition','usage','technical-definition']}]},
{'term':'MCP Registry','slug':'mcp-registry','pronunciation':'em-see-PEE REJ-uh-stree','definition':'A registry service for publishing and discovering metadata about Model Context Protocol servers so clients, aggregators, and users can find available servers and installation information.','example':'The developer published the server metadata to the MCP Registry so compatible clients could discover it.','categories':['AI Systems & Technical Concepts'],'aliases':['Model Context Protocol Registry'],'status':'Established emerging ecosystem term','partOfSpeech':'noun','related':['mcp','mcp-server','mcp-client'],'sources':[{'id':'mcp-registry-about-2026','type':'primary','publisher':'Model Context Protocol','title':'The MCP Registry','published':'2026','url':'https://modelcontextprotocol.io/registry/about','supports':['definition','usage','technical-definition']},{'id':'mcp-registry-api-2026','type':'primary','publisher':'Model Context Protocol','title':'Official MCP Registry Reference','published':'2026','url':'https://registry.modelcontextprotocol.io/docs','supports':['usage','technical-definition']}]},
{'term':'Agent Runtime','slug':'agent-runtime','pronunciation':'AY-jent RUN-time','definition':'The execution environment that hosts, runs, and operates an AI agent or agentic application, providing infrastructure for concerns such as scaling, conversations, tool calls, lifecycle management, and durable execution.','example':'The team deployed the assistant to an agent runtime so long-running tasks could survive interruptions and scale beyond a single process.','categories':['AI Systems & Technical Concepts'],'aliases':['AI agent runtime'],'status':'Established emerging infrastructure term','partOfSpeech':'noun','related':['ai-agent','agentic-workflow','agent-state'],'sources':[{'id':'microsoft-agent-runtime-2026','type':'primary','publisher':'Microsoft Learn','title':'What is Microsoft Foundry Agent Service?','published':'2026-08-19','url':'https://learn.microsoft.com/en-us/azure/ai-services/agents/overview','supports':['definition','usage','technical-definition']},{'id':'google-agent-runtime-2026','type':'primary','publisher':'Google Cloud','title':'Agent Runtime','published':'2026-08','url':'https://docs.cloud.google.com/gemini-enterprise-agent-platform/build/runtime','supports':['definition','usage']}]},
{'term':'Agent State','slug':'agent-state','pronunciation':'AY-jent stayt','definition':'Data that represents information an agent or agent workflow needs to preserve or share across steps, turns, executors, or execution boundaries so later behavior can depend on earlier activity.','example':'The workflow stored the approved customer ID in agent state so later executors could use it without asking again.','categories':['AI Systems & Technical Concepts'],'aliases':['AI agent state'],'status':'Established emerging agent-system term','partOfSpeech':'noun','related':['ai-agent','agent-runtime','ai-memory'],'sources':[{'id':'microsoft-agent-state-2026','type':'primary','publisher':'Microsoft Learn','title':'Microsoft Agent Framework Workflows — State','published':'2026-08-25','url':'https://learn.microsoft.com/en-us/agent-framework/workflows/state','supports':['definition','usage','technical-definition']}]},
{'term':'Multi-Agent Orchestration','slug':'multi-agent-orchestration','pronunciation':'MUL-tee AY-jent or-kuh-STRAY-shun','definition':'The coordination of multiple AI agents with distinct roles or capabilities so they can exchange work, route tasks, collaborate, or execute a larger workflow using an explicit orchestration pattern.','example':'The support system used multi-agent orchestration to hand requests from a triage agent to specialized billing or technical agents.','categories':['AI Ways of Working','AI Systems & Technical Concepts'],'aliases':['Multiagent orchestration'],'status':'Established emerging agent architecture term','partOfSpeech':'noun','related':['ai-agent','agentic-workflow','agent-runtime'],'sources':[{'id':'microsoft-multi-agent-orchestration-2026','type':'primary','publisher':'Microsoft Agent Framework','title':'Microsoft Agent Framework Version 1.0','published':'2026-04-03','url':'https://devblogs.microsoft.com/agent-framework/microsoft-agent-framework-version-1-0/','supports':['definition','usage']},{'id':'microsoft-orchestration-patterns-2026','type':'primary','publisher':'Microsoft Agent Framework','title':'Microsoft Agent Framework at BUILD 2026: Agent Harness, Hosted Agents, CodeAct, and more','published':'2026','url':'https://devblogs.microsoft.com/agent-framework/microsoft-agent-framework-at-build-2026-announce/','supports':['usage','technical-definition']}]},
{'term':'Pointwise Evaluation','slug':'pointwise-evaluation','pronunciation':'POINT-wyze ih-val-yoo-AY-shun','definition':'An evaluation method that scores or judges one model response at a time against defined criteria or a rubric, rather than directly comparing it with another candidate response.','example':'The team used pointwise evaluation to assign each response a quality score from one to five against the same rubric.','categories':['AI Ways of Working','AI Systems & Technical Concepts'],'aliases':['Pointwise eval'],'status':'Established evaluation method','partOfSpeech':'noun','related':['eval','pairwise-evaluation','grader'],'sources':[{'id':'google-pointwise-evaluation-2026','type':'reference','publisher':'Google Cloud','title':'View and interpret evaluation results','published':'2026','url':'https://docs.cloud.google.com/vertex-ai/generative-ai/docs/models/eval-python-sdk/view-evaluation','supports':['definition','usage','technical-definition']},{'id':'google-pointwise-metric-2026','type':'reference','publisher':'Google Cloud','title':'Vertex AI evaluation package — PointwiseMetric','published':'2026-05-30','url':'https://docs.cloud.google.com/python/docs/reference/vertexai/latest/vertexai.evaluation','supports':['definition','usage']}]},
{'term':'Tool-Use Evaluation','slug':'tool-use-evaluation','pronunciation':'tool yoos ih-val-yoo-AY-shun','definition':'Evaluation of how an AI model or agent selects, calls, and uses tools during a task, including whether required tools are invoked appropriately and whether tool interactions contribute to successful outcomes.','example':'The agent suite added tool-use evaluation checks for whether the correct refund and identity-verification tools were called.','categories':['AI Ways of Working','AI Systems & Technical Concepts'],'aliases':['Tool use evaluation','Tool-use eval'],'status':'Established emerging evaluation term','partOfSpeech':'noun','related':['agent-evaluation','tool-calling','grader'],'sources':[{'id':'anthropic-agent-evals-tool-use-2026','type':'primary','publisher':'Anthropic','title':'Demystifying evals for AI agents','published':'2026-01-09','url':'https://www.anthropic.com/engineering/demystifying-evals-for-ai-agents','supports':['definition','usage','evaluation']}]},
{'term':'Human Oversight','slug':'human-oversight','pronunciation':'HYOO-mun OH-ver-site','definition':'Human supervision of an AI system intended to enable people to understand, monitor, intervene in, override, or stop the system when needed, with the level of oversight shaped by the system’s risks, autonomy, and context of use.','example':'The high-risk deployment included human oversight so trained staff could disregard unsafe outputs or interrupt the system.','categories':['AI Risks, Safety & Governance','AI Ways of Working'],'aliases':['Human oversight of AI'],'status':'Established governance and safety term','partOfSpeech':'noun','related':['ai-governance','high-risk-ai','ai-risk-management'],'sources':[{'id':'eu-ai-act-human-oversight','type':'primary','publisher':'EUR-Lex','title':'Regulation (EU) 2024/1689 — Article 14 Human oversight','published':'2024-07-12','url':'https://eur-lex.europa.eu/eli/reg/2024/1689/oj?locale=en','supports':['definition','usage','regulation']}]},
{'term':'AI Incident','slug':'ai-incident','pronunciation':'A-I IN-suh-dent','definition':'An event or circumstance involving an AI system that results in, contributes to, or creates a meaningful risk of harm to people, organizations, property, rights, safety, security, or the environment, depending on the reporting framework being used.','example':'The organization logged the discriminatory lending outcome as an AI incident and began a root-cause review.','categories':['AI Risks, Safety & Governance'],'aliases':['Artificial intelligence incident'],'status':'Established governance and risk term','partOfSpeech':'noun','related':['ai-risk-management','ai-assurance','ai-governance'],'sources':[{'id':'oecd-ai-incidents-2026','type':'primary','publisher':'OECD','title':'AI risks and incidents','published':'2026','url':'https://www.oecd.org/en/topics/ai-risks-and-incidents.html','supports':['definition','usage','governance']},{'id':'oecd-defining-ai-incidents-2024','type':'research','publisher':'OECD','title':'Defining AI incidents and related terms','published':'2024','url':'https://www.oecd.org/content/dam/oecd/en/publications/reports/2024/05/defining-ai-incidents-and-related-terms_88d089ec/d1a8d965-en.pdf','supports':['definition','governance']}]},
{'term':'AI Incident Reporting','slug':'ai-incident-reporting','pronunciation':'A-I IN-suh-dent ree-POR-ting','definition':'The structured practice or regulatory process of documenting and communicating information about AI incidents to designated internal teams, regulators, or shared reporting systems so incidents can be investigated, learned from, and addressed.','example':'The provider’s AI incident reporting process required severe events to be escalated to the regulator within the applicable deadline.','categories':['AI Risks, Safety & Governance','AI Ways of Working'],'aliases':['Artificial intelligence incident reporting'],'status':'Established emerging governance term','partOfSpeech':'noun','related':['ai-incident','ai-risk-management','ai-act'],'sources':[{'id':'eu-ai-act-incident-reporting','type':'primary','publisher':'EUR-Lex','title':'Regulation (EU) 2024/1689 — Article 73 Reporting of serious incidents','published':'2024-07-12','url':'https://eur-lex.europa.eu/eli/reg/2024/1689/oj?locale=en','supports':['definition','usage','regulation']},{'id':'oecd-ai-incident-reporting-2026','type':'primary','publisher':'OECD','title':'AI risks and incidents','published':'2026','url':'https://www.oecd.org/en/topics/ai-risks-and-incidents.html','supports':['definition','usage','governance']}]}
]
def page(t):
 u=f'{BASE}/terms/{t["slug"]}/'; n=escape(t['term']); d=escape(t['definition'],quote=True); p=escape(t['pronunciation']); ld=json.dumps({'@context':'https://schema.org','@type':'DefinedTerm','name':t['term'],'description':t['definition'],'url':u,'inDefinedTermSet':BASE+'/','inLanguage':'en'},ensure_ascii=False)
 return f'<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{n} | EpochLex</title><meta name="description" content="{d}"><link rel="canonical" href="{u}"><script type="application/ld+json">{ld}</script><link rel="stylesheet" href="../../assets/css/styles.css"><link rel="stylesheet" href="../../assets/css/term-pages.css"><link rel="stylesheet" href="../../assets/css/brand-theme.css"></head><body><main id="term-page" class="term-page shell" data-term-slug="{t["slug"]}"><div id="term-fallback" class="term-fallback"><nav class="term-breadcrumb"><a href="../../">Browse</a><span>/</span><span>{n}</span></nav><p class="eyebrow">EpochLex entry</p><h1>{n}</h1><p class="fallback-pronunciation">{p}</p><p class="fallback-definition">{escape(t["definition"])}</p></div></main><script src="../../assets/js/app.js"></script><script src="../../assets/js/term-page.js"></script></body></html>\n'
tp=R/'data/terms.json'; terms=json.loads(tp.read_text()); existing={x['slug'] for x in terms}
for b in B:
 if b['slug'] in existing: raise SystemExit('already published: '+b['slug'])
 rec={k:v for k,v in b.items() if k not in ('related','sources')}; rec.update({'added':D,'lastReviewed':D,'sources':[]}); terms.append(rec)
terms.sort(key=lambda x:x['term'].lower()); tp.write_text(json.dumps(terms,ensure_ascii=False,separators=(',',':'))+'\n')
pp=R/'data/provenance.json'; prov=json.loads(pp.read_text())
for b in B: prov[b['slug']]={'researchStatus':'pending','origin':None,'firstKnownUse':None,'history':[],'relatedTerms':b['related'],'sources':b['sources']}
pp.write_text(json.dumps(prov,ensure_ascii=False,indent=2)+'\n')
for b in B:
 p=R/'terms'/b['slug']; p.mkdir(parents=True,exist_ok=True); (p/'index.html').write_text(page(b))
cp=R/'docs/CORPUS-CANDIDATES.md'; text=cp.read_text(); labels={'MCP Transport':'MCP Transport','MCP Registry':'MCP Registry','Agent Runtime':'Agent Runtime','Agent State':'Agent State','Multi-Agent Orchestration':'Multi-Agent Orchestration','Pointwise Evaluation':'Pointwise Evaluation','Tool-Use Evaluation':'Tool-Use Evaluation','Human Oversight':'Human Oversight','AI Incident':'AI Incident','AI Incident Reporting':'AI Incident Reporting'}
for b in B: text=re.sub(r'^- '+re.escape(labels[b['term']])+r'\s*$','',text,flags=re.M)
text=re.sub(r'\n{3,}','\n\n',text); st=text.index('## Repository roadmap candidates'); en=text.index('## Related documentation'); count=sum(1 for line in text[st:en].splitlines() if line.startswith('- ')); text=re.sub(r'\*\*Current unpublished inventory: \d+ candidates\.\*\*',f'**Current unpublished inventory: {count} candidates.**',text,count=1); cp.write_text(text)
ap=R/'docs/CORPUS-AUDIT-2026-09.md'; a=ap.read_text(); sec='\n## Research Further promotion pass 9 — Batch M (published September 8, 2026)\n\nThis batch is the ninth evidence-based promotion from **Research Further**. Promotion records an audit decision for these entries; it does not create a permanent lifecycle state or automatic promotion rule.\n\n'
for b in B:
 src='; '.join(f"[{s['publisher']}: {s['title']}]({s['url']})" for s in b['sources']); sec+=f"### {b['term']}\n\n**Why promote and publish:** {b['definition']}\n\n**Usage evidence:** {src}\n\n**Provenance state:** `pending` — meaning/usage evidence is recorded; origin, first-known-use, and fuller history research remain open.\n\n"
a=a.replace('## Research Further',sec+'## Research Further',1); a=re.sub(r'This audit has now published \d+ candidates across Batches A–L and added 172 new research candidates\.', 'This audit has now published 123 candidates across Batches A–M and added 172 new research candidates.', a); ap.write_text(re.sub(r'\n{3,}','\n\n',a))
rp=R/'docs/ROADMAP.md'; r=rp.read_text().replace('- 235 published dictionary entries;','- 245 published dictionary entries;').replace('- 122 researched provenance records and 113 pending provenance records in the current published corpus;','- 122 researched provenance records and 123 pending provenance records in the current published corpus;'); rp.write_text(r)
sp=R/'sitemap.xml'; sm=sp.read_text(); blocks=''.join(f'  <url>\n    <loc>{BASE}/terms/{b["slug"]}/</loc>\n    <lastmod>{D}</lastmod>\n  </url>\n' for b in B); sp.write_text(sm.replace('</urlset>',blocks+'</urlset>'))
terms=json.loads(tp.read_text()); prov=json.loads(pp.read_text()); slugs={x['slug'] for x in terms}
assert len(terms)==245, len(terms); assert slugs==set(prov); assert sum(x.get('researchStatus')=='pending' for x in prov.values())==123
for rec in prov.values():
 for s in rec.get('relatedTerms',[]): assert s in slugs, s
for b in B: assert (R/'terms'/b['slug']/'index.html').exists()
assert count==627, count
print('Validated Batch M: 245 published, 123 pending, 627 candidates, related-term parity.')
