#!/usr/bin/env python3
import json,re
from pathlib import Path
from html import escape
R=Path(__file__).resolve().parents[1]; D='2026-09-08'; BASE='https://epochlex.justathoughtblog.org'
B=[
{'term':'Multi-Query Retrieval','slug':'multi-query-retrieval','pronunciation':'MUL-tee KWEER-ee ree-TREE-vul','definition':'A retrieval approach that generates or decomposes an information need into multiple search queries, runs them separately or in parallel, and combines their results to improve coverage or grounding.','example':'The research agent used multi-query retrieval to split a broad question into several focused searches before combining the evidence.','categories':['AI Systems & Technical Concepts'],'aliases':['Multiple-query retrieval','Multi-query search'],'status':'Established retrieval pattern','partOfSpeech':'noun','related':['retrieval-pipeline','query-rewriting','retrieval-fusion'],'sources':[{'id':'microsoft-agentic-retrieval-multi-query-2026','type':'primary','publisher':'Microsoft Learn','title':'Retrieval augmented generation (RAG) and indexes in Microsoft Foundry','published':'2026','url':'https://learn.microsoft.com/en-us/azure/foundry/concepts/retrieval-augmented-generation','supports':['definition','usage','technical-definition']},{'id':'microsoft-rag-multiple-queries-2026','type':'primary','publisher':'Microsoft Learn','title':'Develop a RAG Solution on Azure - Information-Retrieval Phase','published':'2026','url':'https://learn.microsoft.com/en-us/azure/architecture/ai-ml/guide/rag/rag-information-retrieval','supports':['usage','technical-definition']}]},
{'term':'Retrieval Fusion','slug':'retrieval-fusion','pronunciation':'ree-TREE-vul FYOO-zhun','definition':'The process of combining ranked results or scores from multiple retrieval methods or queries into a single ranked result set.','example':'The search system used retrieval fusion to combine keyword and vector-search results before reranking the merged list.','categories':['AI Systems & Technical Concepts'],'aliases':['Result fusion','Search result fusion'],'status':'Established information-retrieval technique','partOfSpeech':'noun','related':['reciprocal-rank-fusion','hybrid-retrieval','multi-query-retrieval'],'sources':[{'id':'elastic-fuse-2026','type':'primary','publisher':'Elastic','title':'ES|QL FUSE command','published':'2026','url':'https://www.elastic.co/docs/reference/query-languages/esql/commands/fuse','supports':['definition','usage','technical-definition']},{'id':'elastic-rrf-2026','type':'primary','publisher':'Elastic','title':'Reciprocal rank fusion','published':'2026','url':'https://www.elastic.co/docs/reference/elasticsearch/rest-apis/reciprocal-rank-fusion','supports':['usage','technical-definition']}]},
{'term':'ColBERT','slug':'colbert','pronunciation':'KOHL-bert','definition':'A neural information-retrieval model that independently encodes query and document tokens and then scores relevance through late interaction between their token-level representations.','example':'The team used ColBERT as a late-interaction reranker to improve retrieval quality without the full cost of a cross-encoder.','categories':['AI Systems & Technical Concepts'],'aliases':['Contextualized Late Interaction over BERT'],'status':'Established retrieval model family','partOfSpeech':'noun','related':['late-interaction','reranker','dense-retrieval'],'sources':[{'id':'khattab-colbert-2020','type':'research','publisher':'Stanford University / arXiv','title':'ColBERT: Efficient and Effective Passage Search via Contextualized Late Interaction over BERT','published':'2020','url':'https://arxiv.org/abs/2004.12832','supports':['definition','technical-definition','origin']},{'id':'pinecone-late-interaction-colbert-2026','type':'reference','publisher':'Pinecone','title':'Cascading retrieval with multi-vector representations: balancing efficiency and effectiveness','published':'2026','url':'https://www.pinecone.io/blog/cascading-retrieval-with-multi-vector-representations/','supports':['usage','technical-definition']}]},
{'term':'Late Interaction','slug':'late-interaction','pronunciation':'LAYT in-ter-AK-shun','definition':'A retrieval-model design in which query and document representations are encoded separately and combined only at a later scoring stage, often through token-level similarity rather than a single pooled embedding.','example':'Late interaction let the retriever precompute document representations while still comparing query and document tokens in detail at scoring time.','categories':['AI Systems & Technical Concepts'],'aliases':['Late-interaction retrieval','Late interaction model'],'status':'Established retrieval architecture term','partOfSpeech':'noun','related':['colbert','bi-encoder','reranker'],'sources':[{'id':'khattab-colbert-2020-late-interaction','type':'research','publisher':'Stanford University / arXiv','title':'ColBERT: Efficient and Effective Passage Search via Contextualized Late Interaction over BERT','published':'2020','url':'https://arxiv.org/abs/2004.12832','supports':['definition','technical-definition','origin']},{'id':'pinecone-late-interaction-2026','type':'reference','publisher':'Pinecone','title':'Cascading retrieval with multi-vector representations: balancing efficiency and effectiveness','published':'2026','url':'https://www.pinecone.io/blog/cascading-retrieval-with-multi-vector-representations/','supports':['usage','technical-definition']}]},
{'term':'Capability Evaluation','slug':'capability-evaluation','pronunciation':'kay-puh-BIL-uh-tee ih-val-yoo-AY-shun','definition':'An evaluation designed to measure what a model or AI system is able to do in a defined domain or task area, including the level, reliability, or limits of that capability.','example':'The system card included capability evaluations for cybersecurity, biology, coding, and autonomous task completion.','categories':['AI Ways of Working','AI Systems & Technical Concepts'],'aliases':['Capability eval','Capabilities evaluation'],'status':'Established model-evaluation term','partOfSpeech':'noun','related':['eval','automated-evaluation','system-card'],'sources':[{'id':'openai-gpt55-capabilities-2026','type':'primary','publisher':'OpenAI','title':'GPT-5.5 System Card','published':'2026-04-23','url':'https://openai.com/index/gpt-5-5-system-card/','supports':['definition','usage','evaluation']},{'id':'openai-gpt54-capabilities-2026','type':'primary','publisher':'OpenAI','title':'GPT-5.4 Thinking System Card','published':'2026-03-05','url':'https://deploymentsafety.openai.com/gpt-5-4-thinking','supports':['usage','evaluation']}]},
{'term':'Safety Benchmark','slug':'safety-benchmark','pronunciation':'SAYF-tee BENCH-mark','definition':'A benchmark or evaluation dataset used to measure safety-relevant behavior, such as policy compliance, refusal quality, robustness to attacks, or performance on defined risk categories.','example':'The model was tested on safety benchmarks covering disallowed content, prompt injection, and jailbreak robustness before deployment.','categories':['AI Risks, Safety & Governance','AI Systems & Technical Concepts'],'aliases':['AI safety benchmark'],'status':'Established evaluation term','partOfSpeech':'noun','related':['safety-evaluation','eval','system-card'],'sources':[{'id':'openai-gpt55-safety-benchmarks-2026','type':'primary','publisher':'OpenAI','title':'GPT-5.5 System Card','published':'2026-04-23','url':'https://deploymentsafety.openai.com/gpt-5-5/monorepo-bench','supports':['definition','usage','evaluation']},{'id':'anthropic-system-cards-2026','type':'primary','publisher':'Anthropic','title':'Model system cards','published':'2026','url':'https://www.anthropic.com/system-cards','supports':['usage','evaluation']}]},
{'term':'AI Security Testing','slug':'ai-security-testing','pronunciation':'A-I sih-KYOOR-uh-tee TEST-ing','definition':'Structured testing that probes AI systems for security weaknesses, attack susceptibility, unsafe tool or data flows, and failures of security controls across the model, application, data, and infrastructure layers.','example':'The release process included AI security testing for prompt injection, unauthorized tool use, data leakage, and privilege escalation.','categories':['AI Risks, Safety & Governance','AI Ways of Working'],'aliases':['Artificial intelligence security testing'],'status':'Established AI security practice','partOfSpeech':'noun','related':['ai-security','prompt-injection-defense','agent-security'],'sources':[{'id':'owasp-aisvs-2026','type':'primary','publisher':'OWASP','title':'Artificial Intelligence Security Verification Standard (AISVS)','published':'2026-06-24','url':'https://owasp.org/www-project-artificial-intelligence-security-verification-standard-aisvs-docs/','supports':['definition','usage','security']},{'id':'owasp-ai-testing-guide-2025','type':'primary','publisher':'OWASP','title':'AI Testing Guide','published':'2025-11-26','url':'https://owasp.org/www-project-ai-testing-guide/','supports':['usage','security','evaluation']}]},
{'term':'Agent Delegation','slug':'agent-delegation','pronunciation':'AY-jent del-uh-GAY-shun','definition':'The assignment or transfer of a task, subtask, or authority from one AI agent to another agent or specialized component while the larger workflow continues.','example':'The manager agent used delegation to send a tax question to a specialist agent and then incorporated the result into the final answer.','categories':['AI Systems & Technical Concepts','AI Ways of Working'],'aliases':['AI agent delegation'],'status':'Established multi-agent orchestration term','partOfSpeech':'noun','related':['agent-handoff','supervisor-agent','multi-agent-orchestration'],'sources':[{'id':'openai-agent-delegation-2026','type':'primary','publisher':'OpenAI','title':'A practical guide to building agents','published':'2026','url':'https://openai.com/business/guides-and-resources/a-practical-guide-to-building-ai-agents/','supports':['definition','usage','technical-definition']},{'id':'microsoft-agent-delegation-2026','type':'primary','publisher':'Microsoft Learn','title':'Workflows','published':'2026-08-25','url':'https://learn.microsoft.com/en-us/agent-framework/journey/workflows','supports':['usage','technical-definition']}]},
{'term':'Model Extraction','slug':'model-extraction','pronunciation':'MOD-ul ek-STRAK-shun','definition':'An attack that attempts to recover details of a machine-learning model, such as its architecture, parameters, or functional behavior, through access to the model or its outputs.','example':'The security team rate-limited repeated probing after detecting behavior consistent with a model extraction attack.','categories':['AI Risks, Safety & Governance','AI Systems & Technical Concepts'],'aliases':['Model extraction attack'],'status':'Established adversarial-ML security term','partOfSpeech':'noun','related':['ai-security','model-audit','ai-security-testing'],'sources':[{'id':'nist-model-extraction-2025','type':'primary','publisher':'NIST CSRC','title':'model extraction - Glossary','published':'2025','url':'https://csrc.nist.gov/glossary/term/model_extraction','supports':['definition','technical-definition','security']},{'id':'owasp-secure-model-ops-extraction-2026','type':'primary','publisher':'OWASP Cheat Sheet Series','title':'Secure AI/ML Model Ops Cheat Sheet','published':'2026','url':'https://cheatsheetseries.owasp.org/cheatsheets/Secure_AI_Model_Ops_Cheat_Sheet.html','supports':['usage','security']}]},
{'term':'Model Inversion','slug':'model-inversion','pronunciation':'MOD-ul in-VER-zhun','definition':'A privacy attack that uses access to a trained model, its outputs, confidence information, gradients, or parameters to reconstruct representative or sensitive information about the data used to train the model.','example':'The security assessment tested whether confidence scores made the classifier vulnerable to model inversion attacks.','categories':['AI Risks, Safety & Governance','AI Systems & Technical Concepts'],'aliases':['Model inversion attack'],'status':'Established adversarial-ML privacy term','partOfSpeech':'noun','related':['model-extraction','ai-security','ai-security-testing'],'sources':[{'id':'nist-model-inversion-2025','type':'primary','publisher':'NIST','title':'Adversarial Machine Learning: A Taxonomy and Terminology of Attacks and Mitigations','published':'2025-03','url':'https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.100-2e2025.pdf','supports':['definition','usage','technical-definition','security']},{'id':'nist-ai-metrology-inversion-2026','type':'primary','publisher':'NIST AI Resource Center','title':'AI Metrology Center - Inversion Recall','published':'2026','url':'https://airc.nist.gov/metrology/','supports':['usage','evaluation','security']}]}
]
def page(t):
 u=f'{BASE}/terms/{t["slug"]}/'; n=escape(t['term']); d=escape(t['definition'],quote=True); p=escape(t['pronunciation']); ld=json.dumps({'@context':'https://schema.org','@type':'DefinedTerm','name':t['term'],'description':t['definition'],'url':u,'inDefinedTermSet':BASE+'/','inLanguage':'en'},ensure_ascii=False)
 return f'<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{n} | EpochLex</title><meta name="description" content="{d}"><link rel="canonical" href="{u}"><script type="application/ld+json">{ld}</script><link rel="stylesheet" href="../../assets/css/styles.css"><link rel="stylesheet" href="../../assets/css/term-pages.css"><link rel="stylesheet" href="../../assets/css/brand-theme.css"></head><body><main id="term-page" class="term-page shell" data-term-slug="{t["slug"]}"><div id="term-fallback" class="term-fallback"><nav class="term-breadcrumb"><a href="../../">Browse</a><span>/</span><span>{n}</span></nav><p class="eyebrow">EpochLex entry</p><h1>{n}</h1><p class="fallback-pronunciation">{p}</p><p class="fallback-definition">{escape(t["definition"])}</p></div></main><script src="../../assets/js/app.js"></script><script src="../../assets/js/term-page.js"></script></body></html>\n'
tp=R/'data/terms.json'; terms=json.loads(tp.read_text()); existing={x['slug'] for x in terms}
for b in B:
 if b['slug'] in existing: raise SystemExit('already published: '+b['slug'])
 rec={k:v for k,v in b.items() if k not in ('related','sources')}; rec.update({'added':D,'lastReviewed':D,'sources':[]}); terms.append(rec)
for t in terms:
 if t['slug']=='grader':
  a=t.setdefault('aliases',[])
  if 'Model Grader' not in a: a.append('Model Grader')
 if t['slug']=='llm-as-a-judge':
  a=t.setdefault('aliases',[])
  if 'Judge Model' not in a: a.append('Judge Model')
terms.sort(key=lambda x:x['term'].lower()); tp.write_text(json.dumps(terms,ensure_ascii=False,separators=(',',':'))+'\n')
pp=R/'data/provenance.json'; prov=json.loads(pp.read_text())
for b in B: prov[b['slug']]={'researchStatus':'pending','origin':None,'firstKnownUse':None,'history':[],'relatedTerms':b['related'],'sources':b['sources']}
pp.write_text(json.dumps(prov,ensure_ascii=False,indent=2)+'\n')
for b in B:
 p=R/'terms'/b['slug']; p.mkdir(parents=True,exist_ok=True); (p/'index.html').write_text(page(b))
cp=R/'docs/CORPUS-CANDIDATES.md'; text=cp.read_text()
for label in [b['term'] for b in B]+['Model Grader','Judge Model']:
 text=re.sub(r'^- '+re.escape(label)+r'\s*$','',text,flags=re.M)
text=re.sub(r'\n{3,}','\n\n',text); st=text.index('## Repository roadmap candidates'); en=text.index('## Related documentation'); count=sum(1 for line in text[st:en].splitlines() if line.startswith('- ')); text=re.sub(r'\*\*Current unpublished inventory: \d+ candidates\.\*\*',f'**Current unpublished inventory: {count} candidates.**',text,count=1); cp.write_text(text)
ap=R/'docs/CORPUS-AUDIT-2026-09.md'; a=ap.read_text(); sec='\n## Research Further promotion pass 18 — Batch V (published September 8, 2026)\n\nThis batch is the eighteenth evidence-based promotion from **Research Further**. Promotion records an audit decision for these entries; it does not create a permanent lifecycle state or automatic promotion rule.\n\n'
for b in B:
 src='; '.join(f"[{s['publisher']}: {s['title']}]({s['url']})" for s in b['sources']); sec+=f"### {b['term']}\n\n**Why promote and publish:** {b['definition']}\n\n**Usage evidence:** {src}\n\n**Provenance state:** `pending` — meaning/usage evidence is recorded; origin, first-known-use, and fuller history research remain open.\n\n"
sec+='### Alias dispositions: Model Grader and Judge Model\n\n- **Model Grader** is represented as an alias of the published **Grader** entry.\n- **Judge Model** is represented as an alias of the published **LLM-as-a-Judge** entry.\n\nThese labels do not provide enough distinct reader value to justify duplicate pages.\n\n'
a=a.replace('## Research Further',sec+'## Research Further',1); a=re.sub(r'This audit has now published \d+ candidates across Batches A–U and added 172 new research candidates\.', 'This audit has now published 213 candidates across Batches A–V and added 172 new research candidates.', a); ap.write_text(re.sub(r'\n{3,}','\n\n',a))
rp=R/'docs/ROADMAP.md'; r=rp.read_text().replace('- 325 published dictionary entries;','- 335 published dictionary entries;').replace('- 122 researched provenance records and 203 pending provenance records in the current published corpus;','- 122 researched provenance records and 213 pending provenance records in the current published corpus;'); rp.write_text(r)
sp=R/'sitemap.xml'; sm=sp.read_text(); blocks=''.join(f'  <url>\n    <loc>{BASE}/terms/{b["slug"]}/</loc>\n    <lastmod>{D}</lastmod>\n  </url>\n' for b in B); sp.write_text(sm.replace('</urlset>',blocks+'</urlset>'))
terms=json.loads(tp.read_text()); prov=json.loads(pp.read_text()); slugs={x['slug'] for x in terms}
assert len(terms)==335, len(terms); assert slugs==set(prov); assert sum(x.get('researchStatus')=='pending' for x in prov.values())==213
assert count==533, count
assert any(x['slug']=='grader' and 'Model Grader' in x.get('aliases',[]) for x in terms)
assert any(x['slug']=='llm-as-a-judge' and 'Judge Model' in x.get('aliases',[]) for x in terms)
for b in B: assert (R/'terms'/b['slug']/'index.html').exists()
for slug,p in prov.items():
 for rel in p.get('relatedTerms',[]): assert rel in slugs,(slug,rel)
print('Validated Batch V: 335 published, 213 pending, 533 candidates.')
