#!/usr/bin/env python3
import json,re
from pathlib import Path
from html import escape
R=Path(__file__).resolve().parents[1]; D='2026-09-08'; BASE='https://epochlex.justathoughtblog.org'
B=[
{'term':'MCP Prompt','slug':'mcp-prompt','pronunciation':'em-see-PEE prompt','definition':'A prompt template exposed by a Model Context Protocol server for clients to discover, retrieve, and optionally customize with arguments before use with a language model.','example':'The documentation server exposed an MCP Prompt that users could select to generate a structured release-note draft.','categories':['AI Systems & Technical Concepts'],'aliases':['Model Context Protocol prompt'],'status':'Established protocol term','partOfSpeech':'noun','related':['mcp','mcp-server','mcp-client'],'sources':[{'id':'mcp-prompts-draft-2026','type':'primary','publisher':'Model Context Protocol','title':'Prompts','published':'2026','url':'https://modelcontextprotocol.io/specification/draft/server/prompts','supports':['definition','usage','technical-definition']}]},
{'term':'MCP OAuth','slug':'mcp-oauth','pronunciation':'em-see-PEE OH-auth','definition':'The OAuth-based authorization profile used by HTTP-based Model Context Protocol implementations so MCP clients can obtain appropriately scoped access to restricted MCP servers on behalf of resource owners.','example':'The remote server used MCP OAuth so the client could request a token that was bound specifically to that MCP server.','categories':['AI Risks, Safety & Governance','AI Systems & Technical Concepts'],'aliases':['MCP authorization OAuth','Model Context Protocol OAuth'],'status':'Established protocol authorization term','partOfSpeech':'noun','related':['mcp','agent-authorization','mcp-client'],'sources':[{'id':'mcp-auth-draft-2026','type':'primary','publisher':'Model Context Protocol','title':'Authorization','published':'2026','url':'https://modelcontextprotocol.io/specification/draft/basic/authorization','supports':['definition','usage','technical-definition','risk']},{'id':'mcp-spec-july-2026','type':'primary','publisher':'Model Context Protocol','title':'The 2026-07-28 Specification','published':'2026-07-28','url':'https://blog.modelcontextprotocol.io/posts/2026-07-28/','supports':['usage','technical-definition']}]},
{'term':'MCP Elicitation','slug':'mcp-elicitation','pronunciation':'em-see-PEE ih-lis-ih-TAY-shun','definition':'A Model Context Protocol interaction in which a server requests additional information, confirmation, or other user input through the client while processing a request.','example':'The provisioning tool used MCP Elicitation to ask the user to confirm the projected cost before creating the resource.','categories':['AI Systems & Technical Concepts','AI Ways of Working'],'aliases':['Model Context Protocol elicitation'],'status':'Established protocol term','partOfSpeech':'noun','related':['mcp','mcp-client','mcp-server'],'sources':[{'id':'mcp-elicitation-draft-2026','type':'primary','publisher':'Model Context Protocol','title':'Elicitation','published':'2026','url':'https://modelcontextprotocol.io/specification/draft/client/elicitation','supports':['definition','usage','technical-definition']},{'id':'mcp-spec-july-2026','type':'primary','publisher':'Model Context Protocol','title':'The 2026-07-28 Specification','published':'2026-07-28','url':'https://blog.modelcontextprotocol.io/posts/2026-07-28/','supports':['usage','technical-definition']}]},
{'term':'MCP Security','slug':'mcp-security','pronunciation':'em-see-PEE sih-KYOOR-uh-tee','definition':'The security practices and controls used to protect Model Context Protocol clients, servers, authorization flows, tools, resources, and data from threats such as token misuse, confused-deputy attacks, unsafe tool invocation, and unauthorized access.','example':'The team reviewed MCP Security before deployment, including token audience validation, user consent, tool safety, and access controls.','categories':['AI Risks, Safety & Governance','AI Systems & Technical Concepts'],'aliases':['Model Context Protocol security'],'status':'Established emerging protocol-security term','partOfSpeech':'noun','related':['mcp','mcp-oauth','mcp-server'],'sources':[{'id':'mcp-spec-security-2025','type':'primary','publisher':'Model Context Protocol','title':'Specification — Security and Trust & Safety principles','published':'2025-11-25','url':'https://modelcontextprotocol.io/specification/2025-11-25','supports':['definition','usage','risk']},{'id':'mcp-auth-security-2026','type':'primary','publisher':'Model Context Protocol','title':'Authorization — Security Considerations','published':'2026','url':'https://modelcontextprotocol.io/specification/draft/basic/authorization','supports':['usage','risk','technical-definition']}]},
{'term':'Human Approval Gate','slug':'human-approval-gate','pronunciation':'HYOO-mun uh-PROO-vul gayt','definition':'A control point in an AI or agent workflow that pauses a proposed action until a person explicitly approves, rejects, or modifies it before execution continues.','example':'The deployment added a human approval gate before the agent could delete production resources or contact external customers.','categories':['AI Risks, Safety & Governance','AI Ways of Working'],'aliases':['Human approval checkpoint','Human approval step'],'status':'Established emerging agent-control term','partOfSpeech':'noun','related':['human-oversight','tool-approval','ai-agent'],'sources':[{'id':'openai-codex-safety-2026','type':'primary','publisher':'OpenAI','title':'Running Codex safely at OpenAI','published':'2026-05-08','url':'https://openai.com/index/running-codex-safely/','supports':['definition','usage','risk']}]},
{'term':'Tool Permission','slug':'tool-permission','pronunciation':'tool per-MISH-un','definition':'A rule or authorization that determines whether an AI model or agent may use a particular tool, capability, resource, or class of actions, often with restrictions based on scope, context, or risk.','example':'The workspace granted the agent tool permission to read deployment logs but not to modify production infrastructure.','categories':['AI Risks, Safety & Governance','AI Ways of Working'],'aliases':['Tool permissions'],'status':'Established emerging agent-control term','partOfSpeech':'noun','related':['tool-approval','agent-permission','least-privilege-agent'],'sources':[{'id':'openai-codex-safety-2026','type':'primary','publisher':'OpenAI','title':'Running Codex safely at OpenAI','published':'2026-05-08','url':'https://openai.com/index/running-codex-safely/','supports':['definition','usage','risk']},{'id':'mcp-spec-tool-safety-2025','type':'primary','publisher':'Model Context Protocol','title':'Specification — Tool Safety','published':'2025-11-25','url':'https://modelcontextprotocol.io/specification/2025-11-25','supports':['usage','risk']}]},
{'term':'Systemic Risk','slug':'systemic-risk','pronunciation':'sis-TEM-ik risk','definition':'In the EU AI Act context, risk associated with the high-impact capabilities or broad reach of a general-purpose AI model that can have significant effects on public health, safety, security, fundamental rights, or society at scale.','example':'The provider evaluated whether the model met the AI Act criteria for a general-purpose AI model with systemic risk.','categories':['AI Risks, Safety & Governance'],'aliases':['AI systemic risk'],'status':'Established regulatory term','partOfSpeech':'noun','related':['ai-act','general-purpose-ai','frontier-ai'],'sources':[{'id':'eu-ai-act-systemic-risk','type':'primary','publisher':'EUR-Lex','title':'Regulation (EU) 2024/1689 — General-purpose AI models with systemic risk','published':'2024-07-12','url':'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex%3A32024R1689','supports':['definition','usage','regulation']}]},
{'term':'Prohibited AI Practice','slug':'prohibited-ai-practice','pronunciation':'proh-HIB-ih-tid A-I PRAK-tis','definition':'An AI practice that is forbidden under a governing legal framework; in the EU AI Act, Article 5 identifies specified practices that may not be placed on the market, put into service, or used under the conditions described by the regulation.','example':'The compliance review checked whether the proposed use could fall within a prohibited AI practice under Article 5 of the AI Act.','categories':['AI Risks, Safety & Governance'],'aliases':['Prohibited AI practice under the EU AI Act','Prohibited AI practices'],'status':'Established regulatory term','partOfSpeech':'noun','related':['ai-act','ai-risk-management','high-risk-ai'],'sources':[{'id':'eu-ai-act-prohibited-practices','type':'primary','publisher':'EUR-Lex','title':'Regulation (EU) 2024/1689 — Article 5 Prohibited AI practices','published':'2024-07-12','url':'https://eur-lex.europa.eu/legal-content/EN/ALL/?uri=CELEX%3A32024R1689','supports':['definition','usage','regulation']}]},
{'term':'AI Impact Assessment','slug':'ai-impact-assessment','pronunciation':'A-I IM-pakt uh-SESS-ment','definition':'A structured assessment used to identify and evaluate the potential consequences of an AI system’s deployment, intended use, and foreseeable misuse, including impacts on people, rights, safety, organizations, society, or the environment.','example':'The organization completed an AI impact assessment before launch to document likely effects, affected groups, and mitigation measures.','categories':['AI Risks, Safety & Governance','AI Ways of Working'],'aliases':['Artificial intelligence impact assessment','AIIA'],'status':'Established governance and assurance term','partOfSpeech':'noun','related':['ai-risk-assessment','ai-risk-management','ai-governance'],'sources':[{'id':'uk-ai-management-essentials-impact','type':'primary','publisher':'UK Department for Science, Innovation and Technology','title':'AI Management Essentials tool — Impact assessment','published':'2026','url':'https://www.gov.uk/government/consultations/ai-management-essentials-tool/ai-management-essentials-tool-accessible','supports':['definition','usage','governance']},{'id':'nist-ai-impact-assessment-tasks','type':'primary','publisher':'NIST AI Resource Center','title':'Descriptions of AI Actor Tasks — AI Impact Assessment','published':'2026','url':'https://airc.nist.gov/airmf-resources/airmf/appendices/app-a-descriptions-of-ai-actor-tasks/','supports':['usage','governance']}]},
{'term':'Agent Security','slug':'agent-security','pronunciation':'AY-jent sih-KYOOR-uh-tee','definition':'The practice of protecting AI agents, their identities, sessions, tools, data flows, permissions, and execution paths from misuse, unauthorized access, prompt injection, data exfiltration, and other threats created or amplified by agentic behavior.','example':'The security review treated agent security as more than model safety by examining tool access, session data, identity, prompt injection, and runtime controls.','categories':['AI Risks, Safety & Governance','AI Systems & Technical Concepts'],'aliases':['AI agent security'],'status':'Established emerging security term','partOfSpeech':'noun','related':['ai-agent','agent-identity','agent-sandbox'],'sources':[{'id':'microsoft-agent-security-2026','type':'primary','publisher':'Microsoft Learn','title':'Agent Security with FIDES','published':'2026-08-25','url':'https://learn.microsoft.com/en-us/agent-framework/agents/security','supports':['definition','usage','risk']},{'id':'microsoft-agent-safety-2026','type':'primary','publisher':'Microsoft Learn','title':'Agent Safety','published':'2026-08-25','url':'https://learn.microsoft.com/en-us/agent-framework/concepts/agents/safety','supports':['usage','risk']}]}
]
def page(t):
 u=f'{BASE}/terms/{t["slug"]}/'; n=escape(t['term']); d=escape(t['definition'],quote=True); p=escape(t['pronunciation']); ld=json.dumps({'@context':'https://schema.org','@type':'DefinedTerm','name':t['term'],'description':t['definition'],'url':u,'inDefinedTermSet':BASE+'/','inLanguage':'en'},ensure_ascii=False)
 return f'<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{n} | EpochLex</title><meta name="description" content="{d}"><link rel="canonical" href="{u}"><script type="application/ld+json">{ld}</script><link rel="stylesheet" href="../../assets/css/styles.css"><link rel="stylesheet" href="../../assets/css/term-pages.css"><link rel="stylesheet" href="../../assets/css/brand-theme.css"></head><body><main id="term-page" class="term-page shell" data-term-slug="{t["slug"]}"><div id="term-fallback" class="term-fallback"><nav class="term-breadcrumb"><a href="../../">Browse</a><span>/</span><span>{n}</span></nav><p class="eyebrow">EpochLex entry</p><h1>{n}</h1><p class="fallback-pronunciation">{p}</p><p class="fallback-definition">{escape(t["definition"])}</p></div></main><script src="../../assets/js/app.js"></script><script src="../../assets/js/term-page.js"></script></body></html>\n'
tp=R/'data/terms.json'; terms=json.loads(tp.read_text()); existing={x['slug'] for x in terms}
for b in B:
 if b['slug'] in existing: raise SystemExit('already published: '+b['slug'])
 rec={k:v for k,v in b.items() if k not in ('related','sources')}; rec.update({'added':D,'lastReviewed':D,'sources':[]}); terms.append(rec)
terms.sort(key=lambda x:x['term'].lower()); tp.write_text(json.dumps(terms,ensure_ascii=False,separators=(',',':'))+'\n')
pp=R/'data/provenance.json'; prov=json.loads(pp.read_text())
for b in B: prov[b['slug']]={'researchStatus':'pending','origin':None,'firstKnownUse':None,'history':[],'relatedTerms':b['related'],'sources':b['sources']}
pp.write_text(json.dumps(prov,ensure_ascii=False,indent=2)+'\n')
for b in B:
 p=R/'terms'/b['slug']; p.mkdir(parents=True,exist_ok=True); (p/'index.html').write_text(page(b))
cp=R/'docs/CORPUS-CANDIDATES.md'; text=cp.read_text(); labels={b['term']:b['term'] for b in B}
for b in B: text=re.sub(r'^- '+re.escape(labels[b['term']])+r'\s*$','',text,flags=re.M)
text=re.sub(r'\n{3,}','\n\n',text); st=text.index('## Repository roadmap candidates'); en=text.index('## Related documentation'); count=sum(1 for line in text[st:en].splitlines() if line.startswith('- ')); text=re.sub(r'\*\*Current unpublished inventory: \d+ candidates\.\*\*',f'**Current unpublished inventory: {count} candidates.**',text,count=1); cp.write_text(text)
ap=R/'docs/CORPUS-AUDIT-2026-09.md'; a=ap.read_text(); sec='\n## Research Further promotion pass 10 — Batch N (published September 8, 2026)\n\nThis batch is the tenth evidence-based promotion from **Research Further**. Promotion records an audit decision for these entries; it does not create a permanent lifecycle state or automatic promotion rule.\n\n'
for b in B:
 src='; '.join(f"[{s['publisher']}: {s['title']}]({s['url']})" for s in b['sources']); sec+=f"### {b['term']}\n\n**Why promote and publish:** {b['definition']}\n\n**Usage evidence:** {src}\n\n**Provenance state:** `pending` — meaning/usage evidence is recorded; origin, first-known-use, and fuller history research remain open.\n\n"
a=a.replace('## Research Further',sec+'## Research Further',1); a=re.sub(r'This audit has now published \d+ candidates across Batches A–M and added 172 new research candidates\.', 'This audit has now published 133 candidates across Batches A–N and added 172 new research candidates.', a); ap.write_text(re.sub(r'\n{3,}','\n\n',a))
rp=R/'docs/ROADMAP.md'; r=rp.read_text().replace('- 245 published dictionary entries;','- 255 published dictionary entries;').replace('- 122 researched provenance records and 123 pending provenance records in the current published corpus;','- 122 researched provenance records and 133 pending provenance records in the current published corpus;'); rp.write_text(r)
sp=R/'sitemap.xml'; sm=sp.read_text(); blocks=''.join(f'  <url>\n    <loc>{BASE}/terms/{b["slug"]}/</loc>\n    <lastmod>{D}</lastmod>\n  </url>\n' for b in B); sp.write_text(sm.replace('</urlset>',blocks+'</urlset>'))
terms=json.loads(tp.read_text()); prov=json.loads(pp.read_text()); slugs={x['slug'] for x in terms}
assert len(terms)==255, len(terms); assert slugs==set(prov); assert sum(x.get('researchStatus')=='pending' for x in prov.values())==133
for rec in prov.values():
 for s in rec.get('relatedTerms',[]): assert s in slugs, s
for b in B: assert (R/'terms'/b['slug']/'index.html').exists()
assert count==617, count
print('Validated Batch N: 255 published, 133 pending, 617 candidates, related-term parity.')
