#!/usr/bin/env python3
import json,re
from pathlib import Path
from html import escape
R=Path(__file__).resolve().parents[1]; D='2026-09-08'; BASE='https://epochlex.justathoughtblog.org'
B=[
{'term':'Contextual Retrieval','slug':'contextual-retrieval','pronunciation':'kun-TEKS-choo-ul ree-TREE-vul','definition':'A retrieval approach that adds chunk-specific context before indexing so retrieved passages retain information about where they came from and what they refer to within the larger source.','example':'The team used contextual retrieval so short chunks preserved the document context needed to find the correct passage.','categories':['AI Systems & Technical Concepts'],'aliases':[],'status':'Established emerging retrieval term','partOfSpeech':'noun','related':['rag','reranker','hybrid-search'],'sources':[{'id':'anthropic-contextual-retrieval-2024','type':'primary','publisher':'Anthropic','title':'Introducing Contextual Retrieval','published':'2024-09-19','url':'https://www.anthropic.com/engineering/contextual-retrieval','supports':['definition','usage','technical-definition']}]},
{'term':'BM25','slug':'bm25','pronunciation':'B-M twenty-five','definition':'A statistical text-ranking function used in information retrieval to score how well a document matches a query using term frequency, inverse document frequency, and document-length normalization.','example':'The retrieval pipeline used BM25 to find passages containing the exact product names in the query.','categories':['AI Systems & Technical Concepts'],'aliases':['Best Match 25','Okapi BM25'],'status':'Established technical term','partOfSpeech':'noun','related':['hybrid-search','rag','reciprocal-rank-fusion'],'sources':[{'id':'elastic-bm25','type':'reference','publisher':'Elastic','title':'Similarity settings — BM25 similarity','published':'2026','url':'https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-similarity.html','supports':['definition','usage','technical-definition']}]},
{'term':'HNSW','slug':'hnsw','pronunciation':'H-N-S-W','definition':'A graph-based approximate nearest-neighbor search algorithm that organizes vectors in hierarchical navigable small-world layers to enable fast similarity search at scale.','example':'The vector database used HNSW to search millions of embeddings without comparing every stored vector.','categories':['AI Systems & Technical Concepts'],'aliases':['Hierarchical Navigable Small World'],'status':'Established technical term','partOfSpeech':'noun','related':['vector-search','vector-database','embedding'],'sources':[{'id':'redis-hnsw','type':'reference','publisher':'Redis','title':'Vector search concepts — HNSW index','published':'2026','url':'https://redis.io/docs/latest/develop/ai/search-and-query/vectors/','supports':['definition','usage','technical-definition']}]},
{'term':'Online Inference','slug':'online-inference','pronunciation':'ON-line IN-fer-ens','definition':'On-demand model inference performed synchronously in response to individual application requests, typically when a timely prediction or generated result is needed.','example':'The recommendation service used online inference to score each request as the user interacted with the application.','categories':['AI Systems & Technical Concepts'],'aliases':['Dynamic inference','Real-time inference'],'status':'Established deployment term','partOfSpeech':'noun','related':['inference','model-serving','inference-server'],'sources':[{'id':'google-online-inference','type':'reference','publisher':'Google for Developers','title':'Production ML systems: online inference','published':'2025-08-25','url':'https://developers.google.com/machine-learning/crash-course/MCE/mc-il-production-inference-online','supports':['definition','usage']}]},
{'term':'Time to First Token','slug':'time-to-first-token','pronunciation':'time to first TOH-kun','definition':'An inference-latency metric measuring the elapsed time from submitting a generation request until the first output token is received.','example':'The team tracked time to first token to understand how quickly users began seeing a streamed response.','categories':['AI Systems & Technical Concepts'],'aliases':['TTFT'],'status':'Established inference performance metric','partOfSpeech':'noun','related':['inference','model-serving','inference-server'],'sources':[{'id':'nvidia-ttft-2026','type':'reference','publisher':'NVIDIA','title':'NIM LLMs Benchmarking — Time to First Token','published':'2026-07-20','url':'https://docs.nvidia.com/nim/benchmarking/llm/latest/metrics.html','supports':['definition','usage','technical-definition']}]},
{'term':'Tokens per Second','slug':'tokens-per-second','pronunciation':'TOH-kunz per SEK-und','definition':'An inference-throughput metric that measures how many output tokens are generated per second, either for an individual request or across a serving system depending on the measurement definition.','example':'The benchmark reported tokens per second alongside latency so the team could compare serving throughput across GPUs.','categories':['AI Systems & Technical Concepts'],'aliases':['TPS','Output token throughput'],'status':'Established inference performance metric','partOfSpeech':'noun','related':['inference','model-serving','inference-server'],'sources':[{'id':'nvidia-tps-2026','type':'reference','publisher':'NVIDIA','title':'NIM LLMs Benchmarking — Tokens Per Second','published':'2026-07-20','url':'https://docs.nvidia.com/nim/benchmarking/llm/latest/metrics.html','supports':['definition','usage','technical-definition']}]},
{'term':'Reinforcement Learning with Verifiable Rewards','slug':'reinforcement-learning-with-verifiable-rewards','pronunciation':'ree-in-FORS-ment LUR-ning with VAIR-uh-fy-uh-bul ree-WORDZ','definition':'A post-training approach that uses reinforcement learning with reward signals derived from outcomes that can be checked automatically or objectively, such as whether a mathematical answer or program is correct.','example':'The reasoning model was post-trained with reinforcement learning with verifiable rewards using automatically checked math and coding tasks.','categories':['AI Systems & Technical Concepts'],'aliases':['RLVR'],'status':'Established emerging post-training term','partOfSpeech':'noun','related':['group-relative-policy-optimization','ai-alignment','fine-tuning'],'sources':[{'id':'microsoft-rlvr-2026','type':'research','publisher':'Microsoft Research','title':'Reinforcement Learning with Verifiable Rewards Implicitly Incentivizes Correct Reasoning in Base LLMs','published':'2026','url':'https://www.microsoft.com/en-us/research/publication/reinforcement-learning-with-verifiable-rewards-implicitly-incentivizes-correct-reasoning-in-base-llms/','supports':['definition','usage','technical-definition']}]},
{'term':'Process Reward Model','slug':'process-reward-model','pronunciation':'PRAH-sess ree-WORD MOD-ul','definition':'A reward model that evaluates intermediate steps in a reasoning or decision process rather than scoring only the final response or outcome.','example':'The process reward model scored each reasoning step so the system could distinguish a sound solution path from one that reached the right answer by accident.','categories':['AI Systems & Technical Concepts'],'aliases':['PRM'],'status':'Established technical term','partOfSpeech':'noun','related':['group-relative-policy-optimization','ai-alignment','inference-time-scaling'],'sources':[{'id':'pmlr-process-reward-model-2025','type':'research','publisher':'Proceedings of Machine Learning Research','title':'Free Process Rewards without Process Labels','published':'2025','url':'https://proceedings.mlr.press/v267/yuan25c.html','supports':['definition','usage','technical-definition']}]},
{'term':'Pairwise Evaluation','slug':'pairwise-evaluation','pronunciation':'PAIR-wyze ih-val-yoo-AY-shun','definition':'An evaluation method that compares two model outputs, prompts, or system variants against the same criteria and determines which performs better rather than assigning each an independent absolute score.','example':'The team used pairwise evaluation to compare responses from the new model against the production baseline.','categories':['AI Ways of Working','AI Systems & Technical Concepts'],'aliases':['Pairwise eval'],'status':'Established evaluation method','partOfSpeech':'noun','related':['eval','llm-as-a-judge','calibration'],'sources':[{'id':'apple-pairwise-evaluation-2026','type':'reference','publisher':'Apple Developer Documentation','title':'Scoring with model-as-judge evaluators','published':'2026','url':'https://developer.apple.com/documentation/Evaluations/scoring-with-model-as-judge-evaluators','supports':['definition','usage']}]},
{'term':'Least-Privilege Agent','slug':'least-privilege-agent','pronunciation':'least PRIV-uh-lij AY-jent','definition':'An AI agent whose identity, resource access, tool access, and action permissions are intentionally limited to the minimum scope needed for its assigned tasks.','example':'The deployment used a least-privilege agent that could read the required records but could not modify unrelated systems.','categories':['AI Risks, Safety & Governance','AI Ways of Working'],'aliases':['Least-privilege AI agent'],'status':'Established emerging security pattern','partOfSpeech':'noun','related':['ai-agent','agent-permission','agent-sandbox','tool-approval'],'sources':[{'id':'microsoft-least-privilege-agents-2026','type':'primary','publisher':'Microsoft Learn','title':'Least privilege for AI agents','published':'2026-07-15','url':'https://learn.microsoft.com/en-us/security/zero-trust/sfi/least-privilege-for-ai-agents','supports':['definition','usage','risk']}]}
]
def page(t):
 u=f'{BASE}/terms/{t["slug"]}/'; n=escape(t['term']); d=escape(t['definition'],quote=True); p=escape(t['pronunciation']); ld=json.dumps({'@context':'https://schema.org','@type':'DefinedTerm','name':t['term'],'description':t['definition'],'url':u,'inDefinedTermSet':BASE+'/','inLanguage':'en'},ensure_ascii=False)
 return f'<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{n} | EpochLex</title><meta name="description" content="{d}"><link rel="canonical" href="{u}"><script type="application/ld+json">{ld}</script><link rel="stylesheet" href="../../assets/css/styles.css"><link rel="stylesheet" href="../../assets/css/term-pages.css"><link rel="stylesheet" href="../../assets/css/brand-theme.css"></head><body><main id="term-page" class="term-page shell" data-term-slug="{t["slug"]}"><div id="term-fallback" class="term-fallback"><nav class="term-breadcrumb"><a href="../../">Browse</a><span>/</span><span>{n}</span></nav><p class="eyebrow">EpochLex entry</p><h1>{n}</h1><p class="fallback-pronunciation">{p}</p><p class="fallback-definition">{escape(t["definition"])}</p></div></main><script src="../../assets/js/app.js"></script><script src="../../assets/js/term-page.js"></script></body></html>\n'
tp=R/'data/terms.json'; terms=json.loads(tp.read_text()); existing={x['slug'] for x in terms}
for b in B:
 if b['slug'] in existing: raise SystemExit('already published: '+b['slug'])
 rec={k:v for k,v in b.items() if k not in ('related','sources')}; rec.update({'added':D,'lastReviewed':D,'sources':[]}); terms.append(rec)
terms.sort(key=lambda x:x['term'].lower()); tp.write_text(json.dumps(terms,ensure_ascii=False,separators=(',',':'))+'\n')
pp=R/'data/provenance.json'; prov=json.loads(pp.read_text())
for b in B: prov[b['slug']]={'researchStatus':'pending','origin':None,'firstKnownUse':None,'history':[],'relatedTerms':b['related'],'sources':b['sources']}
pp.write_text(json.dumps(prov,ensure_ascii=False,indent=2)+'\n')
for b in B:
 p=R/'terms'/b['slug']; p.mkdir(parents=True,exist_ok=True); (p/'index.html').write_text(page(b))
cp=R/'docs/CORPUS-CANDIDATES.md'; text=cp.read_text(); labels={'Contextual Retrieval':'Contextual Retrieval','BM25':'BM25','HNSW':'HNSW','Online Inference':'Online Inference','Time to First Token':'Time to First Token (TTFT)','Tokens per Second':'Tokens per Second','Reinforcement Learning with Verifiable Rewards':'Reinforcement Learning with Verifiable Rewards (RLVR)','Process Reward Model':'Process Reward Model','Pairwise Evaluation':'Pairwise Evaluation','Least-Privilege Agent':'Least-Privilege Agent'}
for b in B: text=re.sub(r'^- '+re.escape(labels[b['term']])+r'\s*$','',text,flags=re.M)
text=re.sub(r'\n{3,}','\n\n',text); st=text.index('## Repository roadmap candidates'); en=text.index('## Related documentation'); count=sum(1 for line in text[st:en].splitlines() if line.startswith('- ')); text=re.sub(r'\*\*Current unpublished inventory: \d+ candidates\.\*\*',f'**Current unpublished inventory: {count} candidates.**',text,count=1); cp.write_text(text)
ap=R/'docs/CORPUS-AUDIT-2026-09.md'; a=ap.read_text(); sec='\n## Research Further promotion pass 6 — Batch J (published September 8, 2026)\n\nThis batch is the sixth evidence-based promotion from **Research Further**. Promotion records an audit decision for these entries; it does not create a permanent lifecycle state or automatic promotion rule.\n\n'
for b in B:
 src='; '.join(f"[{s['publisher']}: {s['title']}]({s['url']})" for s in b['sources']); sec+=f"### {b['term']}\n\n**Why promote and publish:** {b['definition']}\n\n**Usage evidence:** {src}\n\n**Provenance state:** `pending` — meaning/usage evidence is recorded; origin, first-known-use, and fuller history research remain open.\n\n"
a=a.replace('## Research Further',sec+'## Research Further',1); a=re.sub(r'This audit has now published \d+ candidates across Batches A–I and added 172 new research candidates\.', 'This audit has now published 93 candidates across Batches A–J and added 172 new research candidates.', a); ap.write_text(re.sub(r'\n{3,}','\n\n',a))
rp=R/'docs/ROADMAP.md'; r=rp.read_text().replace('- 205 published dictionary entries;','- 215 published dictionary entries;').replace('- 122 researched provenance records and 83 pending provenance records in the current published corpus;','- 122 researched provenance records and 93 pending provenance records in the current published corpus;'); rp.write_text(r)
sp=R/'sitemap.xml'; sm=sp.read_text(); blocks=''.join(f'  <url>\n    <loc>{BASE}/terms/{b["slug"]}/</loc>\n    <lastmod>{D}</lastmod>\n  </url>\n' for b in B); sp.write_text(sm.replace('</urlset>',blocks+'</urlset>'))
terms=json.loads(tp.read_text()); prov=json.loads(pp.read_text()); slugs={x['slug'] for x in terms}
assert len(terms)==215, len(terms); assert slugs==set(prov); assert sum(x.get('researchStatus')=='pending' for x in prov.values())==93
for rec in prov.values():
 for s in rec.get('relatedTerms',[]): assert s in slugs, s
for b in B: assert (R/'terms'/b['slug']/'index.html').exists()
assert count==657, count
print('Validated Batch J: 215 published, 93 pending, 657 candidates, related-term parity.')
