#!/usr/bin/env python3
import json,re
from pathlib import Path
from html import escape
R=Path(__file__).resolve().parents[1]; D='2026-09-08'; BASE='https://epochlex.justathoughtblog.org'
B=[
{'term':'Inference Runtime','slug':'inference-runtime','pronunciation':'IN-fer-ens RUN-time','definition':'Software that loads and executes trained machine-learning or AI models for inference, often providing hardware-specific execution, memory management, graph optimization, or other runtime services.','example':'The application used an inference runtime to execute the exported model across CPU and GPU targets without retraining it.','categories':['AI Systems & Technical Concepts'],'aliases':['AI inference runtime'],'status':'Established deployment term','partOfSpeech':'noun','related':['inference','model-serving','onnx'],'sources':[{'id':'onnx-runtime-inference-2026','type':'primary','publisher':'ONNX Runtime','title':'ONNX Runtime for Inferencing','published':'2026','url':'https://onnxruntime.ai/inference','supports':['definition','usage','technical-definition']}]},
{'term':'Unified Memory','slug':'unified-memory','pronunciation':'YOO-nuh-fied MEM-uh-ree','definition':'A memory architecture in which processors such as the CPU and GPU share the same physical memory pool, reducing or eliminating copies that would otherwise be needed between separate memory spaces.','example':'Unified memory let the local model use the same physical memory from both CPU and GPU operations on the Apple silicon system.','categories':['AI Systems & Technical Concepts'],'aliases':['Unified memory architecture'],'status':'Established hardware architecture term','partOfSpeech':'noun','related':['local-inference','on-device-ai','ai-pc'],'sources':[{'id':'apple-mlx-unified-memory-2025','type':'primary','publisher':'Apple Developer','title':'Get started with MLX for Apple silicon','published':'2025','url':'https://developer.apple.com/videos/play/wwdc2025/315/','supports':['definition','usage','technical-definition']}]},
{'term':'GPU Offloading','slug':'gpu-offloading','pronunciation':'G-P-U OFF-loh-ding','definition':'A model-execution technique that distributes model weights, caches, or computation between GPU memory and slower memory tiers such as CPU RAM or disk so workloads can run within limited GPU memory.','example':'GPU offloading kept the active layers on the graphics card while moving other model weights to CPU memory.','categories':['AI Systems & Technical Concepts'],'aliases':['GPU model offloading'],'status':'Established inference optimization term','partOfSpeech':'noun','related':['local-inference','model-serving','quantized-model'],'sources':[{'id':'hf-big-model-offload-2026','type':'reference','publisher':'Hugging Face','title':'Loading models — Big Model Inference','published':'2026','url':'https://huggingface.co/docs/transformers/models','supports':['definition','usage','technical-definition']}]},
{'term':'Model Telemetry','slug':'model-telemetry','pronunciation':'MOD-ul tuh-LEM-uh-tree','definition':'Operational data collected from AI model interactions—such as model identifiers, token usage, latency, errors, inputs or outputs when enabled, and related traces or metrics—to support monitoring, debugging, cost analysis, and performance assessment.','example':'The platform collected model telemetry to compare latency and token consumption across production model versions.','categories':['AI Systems & Technical Concepts','AI Ways of Working'],'aliases':['AI model telemetry'],'status':'Established emerging observability term','partOfSpeech':'noun','related':['llm-observability','agent-telemetry','latency'],'sources':[{'id':'otel-genai-telemetry-2026','type':'primary','publisher':'OpenTelemetry','title':'Inside the LLM Call: GenAI Observability with OpenTelemetry','published':'2026-05-14','url':'https://opentelemetry.io/blog/2026/genai-observability/','supports':['definition','usage','technical-definition']}]},
{'term':'MCP Connector','slug':'mcp-connector','pronunciation':'em-see-PEE kuh-NEK-ter','definition':'An integration layer that connects an AI product or API to one or more Model Context Protocol servers so the product can access MCP-exposed tools or context without implementing each server integration separately.','example':'The application used an MCP connector to reach the company’s remote documentation server from its model API.','categories':['AI Systems & Technical Concepts','AI Ways of Working'],'aliases':['Model Context Protocol connector'],'status':'Established ecosystem integration term','partOfSpeech':'noun','related':['mcp','mcp-client','mcp-server'],'sources':[{'id':'anthropic-mcp-connector','type':'primary','publisher':'Anthropic','title':'Model Context Protocol (MCP)','published':'2026','url':'https://docs.anthropic.com/en/docs/mcp','supports':['definition','usage','technical-definition']}]},
{'term':'Bi-Encoder','slug':'bi-encoder','pronunciation':'bye en-KOH-der','definition':'An embedding model architecture that encodes two inputs independently into fixed-size vector representations so their similarity can be compared efficiently, commonly for first-stage semantic retrieval.','example':'The search service used a bi-encoder to retrieve candidate passages before a cross-encoder reranked the top results.','categories':['AI Systems & Technical Concepts'],'aliases':['Bi encoder','Dual encoder'],'status':'Established retrieval model term','partOfSpeech':'noun','related':['embedding','dense-retrieval','cross-encoder'],'sources':[{'id':'sbert-bi-encoder-2026','type':'reference','publisher':'Sentence Transformers','title':'Quickstart — Sentence Transformer','published':'2026','url':'https://sbert.net/docs/quickstart.html','supports':['definition','usage','technical-definition']}]},
{'term':'Sparse Retrieval','slug':'sparse-retrieval','pronunciation':'spars ree-TREE-vul','definition':'A retrieval approach that represents queries and documents with sparse vectors in which most dimensions are zero, often preserving token- or term-associated signals and supporting efficient lexical or learned sparse search.','example':'The retrieval pipeline combined sparse retrieval with dense retrieval so exact terminology and semantic similarity could both influence results.','categories':['AI Systems & Technical Concepts'],'aliases':['Sparse vector retrieval'],'status':'Established retrieval term','partOfSpeech':'noun','related':['bm25','dense-retrieval','hybrid-search'],'sources':[{'id':'sbert-sparse-encoder-2026','type':'reference','publisher':'Sentence Transformers','title':'Sparse Encoder — Usage','published':'2026','url':'https://www.sbert.net/docs/sparse_encoder/usage/usage.html','supports':['definition','usage','technical-definition']}]},
{'term':'AI Inventory','slug':'ai-inventory','pronunciation':'A-I IN-ven-tor-ee','definition':'A maintained record of AI systems used, developed, acquired, or operated by an organization, typically capturing enough information to support ownership, governance, risk prioritization, monitoring, and lifecycle management.','example':'The governance team updated its AI inventory so every deployed system had an owner, use case, and risk-review status.','categories':['AI Risks, Safety & Governance','AI Ways of Working'],'aliases':['Artificial intelligence inventory','AI system inventory'],'status':'Established governance practice','partOfSpeech':'noun','related':['ai-governance','ai-risk-management','ai-compliance'],'sources':[{'id':'nist-ai-rmf-inventory','type':'primary','publisher':'NIST AI Resource Center','title':'AI RMF Core — Govern 1.6','published':'2026','url':'https://airc.nist.gov/airmf-resources/airmf/5-sec-core/','supports':['definition','usage','governance']}]},
{'term':'AI Incident Response','slug':'ai-incident-response','pronunciation':'A-I IN-suh-dent ree-SPONSS','definition':'The coordinated process for preparing for, detecting, containing, investigating, recovering from, and learning from incidents involving AI systems, including incidents caused by system failure, attack, misuse, or harmful behavior.','example':'The organization activated its AI incident response process after an agent began making unauthorized tool calls in production.','categories':['AI Risks, Safety & Governance','AI Ways of Working'],'aliases':['Artificial intelligence incident response'],'status':'Established emerging incident-management term','partOfSpeech':'noun','related':['ai-incident','ai-incident-reporting','ai-risk-management'],'sources':[{'id':'nist-ai-rmf-incident-response','type':'primary','publisher':'NIST AI Resource Center','title':'AI RMF Playbook — Govern','published':'2026','url':'https://airc.nist.gov/airmf-resources/playbook/govern/','supports':['definition','usage','governance','risk']},{'id':'nist-ai-incident-workshop-2026','type':'primary','publisher':'NIST','title':'Workshop on AI Incident Management','published':'2026-05','url':'https://www.nist.gov/news-events/events/2026/05/nist-workshop-ai-incident-management','supports':['usage','risk']}]},
{'term':'Trustworthy AI','slug':'trustworthy-ai','pronunciation':'TRUST-wur-thee A-I','definition':'AI developed and used in ways intended to satisfy principles such as human-centred values, fairness, transparency and explainability, robustness, security and safety, accountability, and beneficial outcomes for people and society.','example':'The organization treated trustworthy AI as a set of governance and system qualities to operationalize rather than as a marketing label.','categories':['AI Risks, Safety & Governance'],'aliases':['Trustworthy artificial intelligence'],'status':'Established governance concept','partOfSpeech':'noun','related':['responsible-ai','ai-risk-management','ai-governance'],'sources':[{'id':'oecd-trustworthy-ai-2026','type':'primary','publisher':'OECD.AI','title':'Catalogue of Tools & Metrics for Trustworthy AI — FAQ','published':'2026','url':'https://oecd.ai/en/catalogue/faq','supports':['definition','usage','governance']}]}
]
def page(t):
 u=f'{BASE}/terms/{t["slug"]}/'; n=escape(t['term']); d=escape(t['definition'],quote=True); p=escape(t['pronunciation']); ld=json.dumps({'@context':'https://schema.org','@type':'DefinedTerm','name':t['term'],'description':t['definition'],'url':u,'inDefinedTermSet':BASE+'/','inLanguage':'en'},ensure_ascii=False)
 return f'<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{n} | EpochLex</title><meta name="description" content="{d}"><link rel="canonical" href="{u}"><script type="application/ld+json">{ld}</script><link rel="stylesheet" href="../../assets/css/styles.css"><link rel="stylesheet" href="../../assets/css/term-pages.css"><link rel="stylesheet" href="../../assets/css/brand-theme.css"></head><body><main id="term-page" class="term-page shell" data-term-slug="{t["slug"]}"><div id="term-fallback" class="term-fallback"><nav class="term-breadcrumb"><a href="../../">Browse</a><span>/</span><span>{n}</span></nav><p class="eyebrow">EpochLex entry</p><h1>{n}</h1><p class="fallback-pronunciation">{p}</p><p class="fallback-definition">{escape(t["definition"])}</p></div></main><script src="../../assets/js/app.js"></script><script src="../../assets/js/term-page.js"></script></body></html>\n'
tp=R/'data/terms.json'; terms=json.loads(tp.read_text()); existing={x['slug'] for x in terms}
for b in B:
 if b['slug'] in existing: raise SystemExit('already published: '+b['slug'])
 rec={k:v for k,v in b.items() if k not in ('related','sources')}; rec.update({'added':D,'lastReviewed':D,'sources':[]}); terms.append(rec)
terms.sort(key=lambda x:x['term'].lower()); tp.write_text(json.dumps(terms,ensure_ascii=False,separators=(',',':'))+'\n')
pp=R/'data/provenance.json'; prov=json.loads(pp.read_text())
for b in B: prov[b['slug']]={'researchStatus':'pending','origin':None,'firstKnownUse':None,'history':[],'relatedTerms':b['related'],'sources':b['sources']}
pp.write_text(json.dumps(prov,ensure_ascii=False,indent=2)+'\n')
for b in B:
 p=R/'terms'/b['slug']; p.mkdir(parents=True,exist_ok=True); (p/'index.html').write_text(page(b))
cp=R/'docs/CORPUS-CANDIDATES.md'; text=cp.read_text(); labels={b['term']:b['term'] for b in B}
for b in B: text=re.sub(r'^- '+re.escape(labels[b['term']])+r'\s*$','',text,flags=re.M)
text=re.sub(r'\n{3,}','\n\n',text); st=text.index('## Repository roadmap candidates'); en=text.index('## Related documentation'); count=sum(1 for line in text[st:en].splitlines() if line.startswith('- ')); text=re.sub(r'\*\*Current unpublished inventory: \d+ candidates\.\*\*',f'**Current unpublished inventory: {count} candidates.**',text,count=1); cp.write_text(text)
ap=R/'docs/CORPUS-AUDIT-2026-09.md'; a=ap.read_text(); sec='\n## Research Further promotion pass 13 — Batch Q (published September 8, 2026)\n\nThis batch is the thirteenth evidence-based promotion from **Research Further**. Promotion records an audit decision for these entries; it does not create a permanent lifecycle state or automatic promotion rule.\n\n'
for b in B:
 src='; '.join(f"[{s['publisher']}: {s['title']}]({s['url']})" for s in b['sources']); sec+=f"### {b['term']}\n\n**Why promote and publish:** {b['definition']}\n\n**Usage evidence:** {src}\n\n**Provenance state:** `pending` — meaning/usage evidence is recorded; origin, first-known-use, and fuller history research remain open.\n\n"
a=a.replace('## Research Further',sec+'## Research Further',1); a=re.sub(r'This audit has now published \d+ candidates across Batches A–P and added 172 new research candidates\.', 'This audit has now published 163 candidates across Batches A–Q and added 172 new research candidates.', a); ap.write_text(re.sub(r'\n{3,}','\n\n',a))
rp=R/'docs/ROADMAP.md'; r=rp.read_text().replace('- 275 published dictionary entries;','- 285 published dictionary entries;').replace('- 122 researched provenance records and 153 pending provenance records in the current published corpus;','- 122 researched provenance records and 163 pending provenance records in the current published corpus;'); rp.write_text(r)
sp=R/'sitemap.xml'; sm=sp.read_text(); blocks=''.join(f'  <url>\n    <loc>{BASE}/terms/{b["slug"]}/</loc>\n    <lastmod>{D}</lastmod>\n  </url>\n' for b in B); sp.write_text(sm.replace('</urlset>',blocks+'</urlset>'))
terms=json.loads(tp.read_text()); prov=json.loads(pp.read_text()); slugs={x['slug'] for x in terms}
assert len(terms)==285, len(terms); assert slugs==set(prov); assert sum(x.get('researchStatus')=='pending' for x in prov.values())==163
assert count==587, count
for b in B: assert (R/'terms'/b['slug']/'index.html').exists()
for slug,p in prov.items():
 for rel in p.get('relatedTerms',[]): assert rel in slugs,(slug,rel)
print('Validated Batch Q: 285 published, 163 pending, 587 candidates.')